### PR TITLE
Fix for #3447

### PR DESCRIPTION
**Pull request by cra0zy**
Fix for #3447

### CODE REVIEW

**Comment by cra0zy** [comment]
@CallumDev better?

**Comment by tomspilman** [comment]
Waiting on @CallumDev to reply before merging.

**Comment by CallumDev** [comment]
Fails now on Condensed fonts (DejaVu Sans Condensed)
`/usr/share/fonts/TTF/DejaVuSansCondensed-Bold.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Bold,Bold`

**Comment by CallumDev** [comment]
Something like this (using fc-match), might be a better option

        string FindFontFileFromFontName(string fontname, string style)
		{
			System.Diagnostics.Process proc = new System.Diagnostics.Process();
			proc.StartInfo.FileName = "/bin/bash";
		        proc.StartInfo.Arguments = 
				string.Format ("-c \"fc-match -f '%{{file}}:%{{family}}\\n' '{0}:style={1}'\"", fontname, style);
			proc.StartInfo.UseShellExecute = false; 
			proc.StartInfo.RedirectStandardOutput = true;
			proc.Start();
			proc.WaitForExit ();
		        string s = proc.StandardOutput.ReadToEnd ().Trim ();
			var split = s.Split (':');
			//check font family, fontconfig might return a fallback
			if (split [1].Contains (",")) { //this file defines multiple family names
				var families = split [1].Split (',');
				foreach (var f in families) {
					if (f.ToLowerInvariant () == fontname.ToLowerInvariant ())
						return split [0];
				}
				//didn't find it
				return String.Empty;
			} else {
				if (split [1].ToLowerInvariant () != fontname.ToLowerInvariant ())
					return String.Empty;
			}
			return split [0];
		}

If you use it as `FindFontFileFromFontName("Arial","italic");` it'll return the name of the file if it can find it, or `String.Empty` otherwise

**Comment by cra0zy** [comment]
@CallumDev What if someone writes font file name instead of the font family name... Anyway with my code I forgot to take into account that there can be styles like "Condensed Bold" and "Bold", if you would search for bold both would come up as correct.

**Comment by KonajuGames** [comment]
We have a `ExternalTool` utility class in the Pipeline project with a `Run` method for running extenral runs and retrieving the output.  Saves duplicating the code for starting a process and waiting on it.

**Comment by KonajuGames** [comment]
It should check if the specified font is a filename by checking if a file by that name exists (useful for people who keep the TTFs in their project).  If not, assume it is a family name and pass it through this function to convert it to a font filename.

**Comment by cra0zy** [comment]
@KonajuGames Should it check for the filename only in the project dir, or should it check for the filename threw the system fonts too?

**Comment by KonajuGames** [comment]
If you want to use a system font, specify the font family.  If you have the TTF file in your project, then you specify the filename relative to the .spritefont file.

**Comment by cra0zy** [comment]
Once this is ok I am gonna rebase it.

**Comment by CallumDev** [comment]
This looks good

**Comment by tomspilman** [comment]
Ok... merging!

**Pull request merged**
