### PR TITLE
Move LZX decompress code from ContentManager into LzxDecoderStream

### PR DESCRIPTION
**Pull request by nkast**
Added LzxDecoderStream similar to Lz4DecoderStream and make ContentManager a bit cleanner.
Related to https://github.com/mono/MonoGame/pull/4522

### CODE REVIEW

**Comment by KonajuGames** [comment]
Why did the tests not run on this?  Do you want to do an update to this branch, and hopefully that will kick off the tests.

**Comment by tomspilman** [comment]
@KonajuGames - Looks like it is ok now...  I think when it came in the build machine was down or something.

**Comment by KonajuGames** [comment]
Ok. Merging.

**Comment by nkast** [comment]
Thanks!

**Pull request merged**
