### PR TITLE
MonoGame Portable Assemblies

### PR DESCRIPTION
**Pull request by tomspilman**
This PR introduces the Piranha tool into the build process generating PCL assemblies from the Windows build of framework, net, and pipeline assemblies.

See https://github.com/mono/MonoGame/issues/4689.

### CODE REVIEW

**Comment by tomspilman** [comment]
The nuget packaging failed... working on that.

**Comment by tomspilman** [comment]
@craftworkgames  @kjpou1 

I was told you guys maintain your own MonoGame PCL libs.  Do you mind looking at our assembly to be sure it would fit your needs too?

[MonoGame.Framework.Portable](http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/8825:id/MonoGame.Framework.zip%21/MonoGame.Framework/bin/Portable/AnyCPU/MonoGame.Framework.dll?guest=1)

Just want to be sure I didn't mess anything up in its creation.

@DDReaper - Maybe you should look too as I used your branch as the example.

**Comment by craftworkgames** [comment]
@tomspilman Seems to work just fine on Windows. Although that doesn't surprise me, I believe the issues we had used to have show up on Linux and Mac. 

Maybe @LithiumToast or @WardBenjamin could check it. All I did was replace the DLL in our repo with this one and clean / compile / run. Btw.. our current process is [documented on our wiki](https://github.com/craftworkgames/MonoGame.Extended/wiki/How-to-build-the-MonoGame-PCL)

**Comment by tomspilman** [comment]
@craftworkgames - In the doc link to your wiki I noticed you use `.NETPortable,Version=v4.5,Profile=Profile111`.  I am using `.NETPortable,Version=v4.0,Profile=Profile96` in this PR.

Is it good or bad that i'm using an older profile here?  Is this the same as the .NET 4.5 profile?

**Comment by LithiumToast** [comment]
@tomspilman

> Is it good or bad that i'm using an older profile here?

The .NET 4.0 vs 4.5 shouldn't be a big deal. The kicker is `Profile96` targets Silverlight while `Profile111` does not. Is Silverlight a thing for MonoGame?

**Comment by tomspilman** [comment]
> The kicker is  Profile96  targets Silverlight while  Profile111  does not. 

I don't think MonoGame on Silverlight is a thing...  but I could be wrong I guess.

**Comment by LithiumToast** [comment]
@tomspilman I'll double check if .NET 4.0 is a problem later today.

**Comment by KonajuGames** [comment]
> I don't think MonoGame on Silverlight is a thing... but I could be wrong I guess.

MonoGame on Silverlight is not a thing, and hasn't been for a long time.

**Comment by Helikin** [comment]
FYI, DigitalRune is currently using Profile328 but we are moving to Profile111 in the our next release.

Profile96=portable-net403+sl40+netcore45+wp71
Profile328=portable-net4+sl50+netcore45+wpa81+wp8
Profile111=portable-net45+netcore45+wpa81

Profile111 also supports netstandard1.1. (See [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md)) Therefore, I think Profile111 is a good start.

A nice list of profiles is: [PCL profiles by Steaphen Cleary](http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY)

**Comment by tomspilman** [comment]
> but we are moving to Profile111 in our next release.

Ok so both you and @craftworkgames are on 111.  What is CocosSharp on @kjpou1 ?

**Comment by tomspilman** [comment]
Looks like CocosSharp is on `Profile136`.

So not sure what is best for MonoGame then.

**Comment by LithiumToast** [comment]
`Profile136` targets Silverlight: `portable-net4+sl50+netcore45+wp8`

One of the standard profiles should probably be used like @Helikin said. `Profile111` is right choice for .NET 4.5 and no Silverlight.

**Comment by tomspilman** [comment]
> `Profile111` is the one for .NET 4.5 and no Silverlight; probably a good choice.

If everyone one else agrees i'll make the change.

**Comment by craftworkgames** [comment]
I believe the reason we went to `Profile111` and dropped silverlight support was so we could support `unsafe` code in our portable libraries. This is helpful in high performance code like particle systems.

**Comment by tomspilman** [comment]
Our PCL is the bait-and-switch type, so there is no implementation code in it to worry about.  We also never expose unsafe methods as part of the API.

**Comment by DDReaper** [comment]
The core project was a true pcl with active code. Whereas the Piranha version was a complete bait and switch plc

**Comment by tomspilman** [comment]
> The core project was a true pcl with active code

Right... that is still an open task for us.  This bait-and-switch PCL doesn't solve the same issues and doesn't keep us from adding a true PCL core library too.

**Comment by DDReaper** [comment]
Correct, it's a stepping stone which allows the project to move forward in incremental steps

**Comment by craftworkgames** [comment]
> Our PCL is the bait-and-switch type, so there is no implementation code in it to worry about. We also never expose unsafe methods as part of the API.

I'm aware of how it works with the MonoGame PCL. I was just letting you know one of the advantages of not supporting Silverlight. 

I'm not really sure what happens when you reference one PCL from another that have different profiles but based on what I've seen there's a pretty good chance it won't make much difference.

**Comment by tomspilman** [comment]
> I'm not really sure what happens when you reference one PCL from another that have different profiles 

Yeah I have no clue either...  you would think it wouldn't matter.

**Comment by DDReaper** [comment]
Simply put, it's about compatibility. Pcl's can reference each other so long as they have at least one complementary platform.
However if you try to consume them from a platform that isn't in one of them, it will error/fail.

**Comment by tomspilman** [comment]
> However if you try to consume them from a platform that isn't in one of them, it will error/fail.

Sounds like `Profile111` is safe for us then.  Thanks @DDReaper .

I'll make the change tomorrow.

**Comment by tomspilman** [comment]
Also opinions on https://github.com/mono/MonoGame/issues/4735 from NuGet users would be appreciated.

**Comment by tomspilman** [comment]
Any idea what is wrong here @dellis1972 @DDReaper ?

Do I have anything wrong in the command line?

https://github.com/SickheadGames/MonoGame/blob/portable/default.build#L82

The exception doesn't say much:
```
[17:13:41]Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
[17:13:41]   at Ark.Piranha.MethodDependency.Break() in C:\Projects\Piranha-master\Ark.Piranha\Dependencies.cs:line 143
[17:13:41]   at Ark.Piranha.RemoveExternalTypesUsageProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in C:\Projects\Piranha-master\Ark.Piranha\RemoveExternalTypesUsageProcessor.cs:line 67
[17:13:41]   at Ark.Cecil.CecilProcessor.Process(AssemblyDefinition assemblyDef) in C:\Projects\Piranha-master\Ark.Cecil\CecilProcessor.cs:line 67
[17:13:41]   at Ark.Piranha.RetargetAssemblyProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in C:\Projects\Piranha-master\Ark.Piranha\RetargetAssemblyProcessor.cs:line 29
[17:13:41]   at Ark.Cecil.CecilProcessor.Process(AssemblyDefinition assemblyDef) in C:\Projects\Piranha-master\Ark.Cecil\CecilProcessor.cs:line 67
[17:13:41]   at Ark.Piranha.MakePortableSkeletonProcessor.ProcessAssembly(AssemblyDefinition assemblyDef) in C:\Projects\Piranha-master\Ark.Piranha\MakePortableSkeletonProcessor.cs:line 22
[17:13:41]   at Ark.Cecil.CecilProcessor.Process(AssemblyDefinition assemblyDef) in C:\Projects\Piranha-master\Ark.Cecil\CecilProcessor.cs:line 67
[17:13:41]   at Ark.Cecil.CecilProcessor.ProcessAssemblyFromFile(String inputFile, ReaderParameters readerParams, String outputFile, WriterParameters writerParams) in C:\Projects\Piranha-master\Ark.Cecil\CecilProcessor.cs:line 22
[17:13:41]   at Ark.Cecil.CecilProcessor.ProcessAssemblyFromFile(String inputFile, String outputFile) in C:\Projects\Piranha-master\Ark.Cecil\CecilProcessor.cs:line 16
[17:13:41]   at Piranha.MakePortableSkeletonCommand.Execute() in C:\Projects\Piranha-master\Piranha\MakePortableSkeletonCommand.cs:line 11
[17:13:41]   at Piranha.Program.<>c.<Main>b__0_0(String v, Object o) in C:\Projects\Piranha-master\Piranha\Program.cs:line 21
[17:13:41]   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
[17:13:41]   at Piranha.Program.Main(String[] args) in C:\Projects\Piranha-master\Piranha\Program.cs:line 17
```

I guess the `Method` is null here?

https://github.com/Ark-kun/Piranha/blob/master/Ark.Piranha/Dependencies.cs#L120

**Comment by tomspilman** [comment]
Ok...  I guess maybe I'm using this tool incorrectly. I noticed this in the processing of the pipeline assembly:

```
RemoveExternalTypesUsage: Removing dependencies on type Microsoft.Xna.Framework.Rectangle:
   TypeDependency: Removing method System.Void Microsoft.Xna.Framework.Content.Pipeline.Graphics.BitmapContent::Copy(Microsoft.Xna.Framework.Content.Pipeline.Graphics.BitmapContent,Microsoft.Xna.Framework.Rectangle,Microsoft.Xna.Framework.Content.Pipeline.Graphics.BitmapContent,Microsoft.Xna.Framework.Rectangle) because a type that its signature or body depends on is being removed.
```

That is removing `BitmapContent::Copy(BitmapContent,Rectangle,BitmapContent,Rectangle)` because `Rectangle` is referenced.  I guess this is because it sees `MonoGame.Framework.dll` as not a PCL assembly.  So I guess I need to be sure processing the pipeline references the PCL `MonoGame.Framework.dll` and not the non-PCL one.

Not sure if it fixes my issue above...  but still a fix.

**Comment by tomspilman** [comment]
I have no clue what I am doing wrong:
```
RemoveExternalTypesUsage: Removing dependencies on type System.Void:
```
Why would you remove types that use a `void` return?  That basically removes most of the methods in the assembly?

**Comment by tomspilman** [comment]
So doing more research...  I think we will target `Profile 328`.

  - It is .NET 4.0 which allows people targeting 4.0+ to use it.
  - It supports the most platforms (Silverlight 5, Windows 8, Windows Phone 8.1, Windows Phone Silverlight 8)
  - It works without me fixing whatever is [wrong with Piranha](https://github.com/Ark-kun/Piranha/issues/3).

Since we are a "bait-and-switch" assembly we don't care about .NET 4.5 features as there is no implementation that needs them.

Fixing up the build now.

**Comment by tomspilman** [comment]
So at least it doesn't crash building the PCLs...  but I still have issues. For some reason Piranha still wants to strip out all the types from `MonoGame.Framework.dll` in the pipeline assembly.  Going to have to debug Piranha to figure out why and how to fix it.

**Comment by tomspilman** [comment]
So it seems our situation is just not something Piranha currently supports.  We have one assembly depending on another and both need to be stripped for PCL while retaining that reference.  I added an issue for it on the Piranha repo:  https://github.com/Ark-kun/Piranha/issues/5

**Comment by tomspilman** [comment]
So in https://github.com/Ark-kun/Piranha/issues/5 I wrote up my fix, but @Ark-kun has been too busy to respond yet.  

@dellis1972 @DDReaper - Does the solution i posted in the issue above make sense to you guys?  Should I just merge my hacked version of Piranha and use that?

**Comment by dellis1972** [comment]
Use the hacked version until in gets fixed :)

-----Original Message-----

**Comment by tomspilman** [comment]
Ok... looks like I finally have the Piranha side of things working here.  We seem to get good working PCL assemblies.

The one last thing is assembly dependencies.  `MonoGame.Framework.Content.Pipeline.dll` depends on `MonoGame.Framework.dll`.  So I guess i need to add something to the `MonoGame.Framework.Content.Pipeline.nuspec` file, so that it automatically pulls the right dependency for `MonoGame.Framework.nuspec`.  Right?

@DDReaper ?

**Comment by dellis1972** [comment]
@tomspilman the Pipeline PCL nuget needs to reference the MG PCL nuget yes.

**Comment by DDReaper** [comment]
Correct, just check out the previous nuget I did for dean that is currently published.
If you need the original nuspec, let me know and I can doc it out

**Comment by tomspilman** [comment]
@DDReaper - Thanks...  but it looks like I got it working now.

I think this PR is good to go now.

**Comment by dellis1972** [comment]
@tomspilman looks good to me. I'll merge

**Pull request merged**
