### PR TITLE
Added OcclusionQuery implementation for DirectX.

### PR DESCRIPTION
**Pull request by Helikin**
This PR splits the OcclusionQuery.cs into OcclusionQuery.*Platform*.cs files and adds an implementation for DirectX.

The PR also adds unit tests. One test uses the SpriteBatch. It should currently fail because of the SpriteBatch z value bug. It should work after following PR is merged:
- Fix: SpriteBatch writes wrong z value. #4184

Previously, OcclusionQuery.cs was excluded from iOS, Android and Ouya builds. I have tested the occlusion query on iOS and Android, and the query works if the device supports OpenGL ES 3.0. I have not tested on devices without ES 3.0 support - therefore, the OcclusionQuery files are still excluded on iOS, Android and Ouya.

This PR should also fix a bug in the OpenGL implementation: 
The pixel count was retrieved with ```QueryResultAvailable``` (which returns only true/false) instead of ```QueryResult```. (The MonoMac code path did not have this problem.)

Related issues: 
- Missing OcclusionQuery class from Graphics namespace #414
- DirectX and OcclusionQuery #4033

### CODE REVIEW

**Comment by Helikin** [comment]
With #4184 merged, the unit tests should succeed now. Is it possible to restart the build bot?

**Comment by tomspilman** [comment]
@Helikin - You need to merge the latest upstream changes into your branch to include #4184.  The build server just builds the branch... it doesn't merge with develop for you.

**Comment by Helikin** [comment]
> it doesn't merge with develop for you.

Ah yeah, right. I spend too little time with git. ;-)
Will do tomorrow.

**Comment by tomspilman** [comment]
Thanks @Helikin ... merging!

**Pull request merged**
