### PR TITLE
ModelMesh.Tag fix issue #3695

### PR DESCRIPTION
**Pull request by AndersonReyes**

### CODE REVIEW

**Comment by tomspilman** [comment]
Does anyone have time to test this change?

@tgjones - Do we have a model loading unit test?

**Comment by AndersonReyes** [comment]
@tomspilman if you tell me how to set it up I can do it myself?

**Comment by tgjones** [comment]
> Do we have a model loading unit test?

Not yet. I was thinking we could add a `CompileModel` in `AssetTestUtility.cs`, alongside the existing `CompileEffect`.

**Comment by tomspilman** [comment]
I'm really confident this won't break anything, so i'll go ahead and merge it.  We'll look to getting a better unit test for model loading here soon.

**Pull request merged**
