### PR TITLE
TitleContainer Cleanup

### PR DESCRIPTION
**Pull request by tomspilman**
This PR splits up `TitleContainer` into partial classes for platform specific implementation code.  ~~This should have no functional change in the code if I did it correctly.~~

I expanded on this PR to add some unit tests for `TitleContainer` too fixing some bugs.

### CODE REVIEW

**Comment by tomspilman** [comment]
This can wait until 3.5 is released.

**Comment by dellis1972** [comment]
@tomspiman. doh.. ok. I'll keep this around for the GetFiles stuff.

**Comment by tomspilman** [comment]
Woot... merging!

**Comment by dellis1972** [comment]
@tomspilman awesome, I can now do my bits for the ListFiles stuff :)

**Pull request merged**
