### PR TITLE
Removed the RGBA->BGRA swap in FontTextureProcessor

### LINKED ISSUE #3430: SpriteFont Texture Color are swapped from RGBA to BGRA even if processor is set to Color
This is a reproducible issue in Windows (dx AND gl).

https://www.dropbox.com/s/yuiip7y8nibry9c/FontBuildIssue.zip?dl=0

This is a project that basically shows the issue, the font is a number font from our game, i colored it to show the problem: 
1) at the top you can see the original texture from wich the font should be drawn (SpriteBatch.Draw)
2) the second and third line shows the actual result: R and B are swapped. (SpriteBatch.DrawString)

colorfontissue

### PR DESCRIPTION
**Pull request by KonajuGames**
It is already done elsewhere.

Fixes #3430

### CODE REVIEW

**Comment by tomspilman** [comment]
Could we make a unit test for this?  Something like I wrote for the `TextureProcessor`...

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/TextureProcessorTests.cs

I know you are busy with stuff, but if we're going to ask others to write unit tests we have to hold ourselves to the same standard.

**Comment by tomspilman** [comment]
Note a recommended setup up unit tests for `FontTextureProcessor` in https://github.com/mono/MonoGame/pull/3454 as well.  Lets make sure two people don't go off and do the same work.

**Comment by KonajuGames** [comment]
I will get the unit test added today.

**Comment by tomspilman** [comment]
Thanks @KonajuGames .

**Comment by tomspilman** [comment]
The test looks good.  I assume you flipped the bool in `ToXnaBitmap()` back to true to validate your test catches the original bug?

**Comment by KonajuGames** [comment]
I did, and it caught it.​

**Comment by tomspilman** [comment]
Great!  Merging!

**Pull request merged**
