### PR TITLE
Input improvements 1

### PR DESCRIPTION
**Pull request by Shqrdx**
I decided to not push all my changes to a single PR so when first pack of improvements will be merged, I continue. 
Changes:
-Removed ThumbStickDefinition,
-ButtonState - removed old license & using, added docs for members
-Buttons - removed old license, added docs for members
-GamePadType - removed old license & using, changed enum values to conform the XNA, added docs for members.
-Keys - changes docs to conform other enums, added dots to members docs
-EnumConformingTest - new tests for input enums

### CODE REVIEW

**Comment by tomspilman** [comment]
Weird...  the Mac build failed with the error:

> /Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/default.build(38,7):
Unable to download 'https://www.nuget.org/api/v2/package/MonoGame.Framework.Android/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.Android.3.3.0.nupkg'.

I'll restart the build...  it might have just been a temporary outage of the nuget service.

**Comment by tomspilman** [comment]
@Shqrdx - I said before in your PR the other day...

https://github.com/mono/MonoGame/pull/3993#issuecomment-123208620

@KonajuGames and I need to rethink how documentation tasks are handled moving forward. Do not submit any new docs until then.

I'll let this one by, but the next one will just be closed.

**Comment by Shqrdx** [comment]
Oh.. I forgot.. no docs..

**Comment by tomspilman** [comment]
Yea...  so the build failure here was that the NuGet service failed to return a package we tried to download.  That in turn failed this build.

I REALLY hate that we made NuGet a dependency of our build process.

**Comment by Shqrdx** [comment]
Should I need to close it ?

**Comment by Shqrdx** [comment]
@tomspilman Looks like it is compiled, merge ?

**Pull request merged**
