### PR TITLE
Updated Protobuild

### PR DESCRIPTION
**Pull request by cra0zy**
This fixes the Linux Pipeline Tool problem @hach-que caused with #4282

Long story short, she did not merge changes of #4243 done to xslt so LocalCopy was setting to true, and because libraries were being copied, Pipeline Tool would use local dlls instead of system ones(and this causes a crash because no config files are copied and tool tries to load Window dlls).

### CODE REVIEW

**Comment by hach-que** [comment]
Do not merge this. I haven't merged in the PR upstream, and part of merging in upstream involves rebuilding Protobuild based on the PR changes, so the final executable that gets merged will have a different hash.

And for the record, I'm a woman; she is the correct pronoun.

**Comment by hach-que** [comment]
I should clarify, technically you can merge this, but the version of Protobuild will technically be divergent from upstream since it won't ever have lived in the `master` branch.

**Comment by cra0zy** [comment]
> And for the record, I'm a woman; she is the correct pronoun.

Sorry about that.

**Comment by cra0zy** [comment]
Updated with Protobuild from Protobuild repo.

**Comment by hach-que** [comment]
Can you update this PR with the latest version before it's merged (I pushed some more changes to Protobuild and if we're updating it then we might as well put it on the latest version)?

**Comment by cra0zy** [comment]
> Can you update this PR with the latest version before it's merged (I pushed some more changes to Protobuild and if we're updating it then we might as well put it on the latest version)?

done.

**Comment by cra0zy** [comment]
@tomspilman @KonajuGames Please merge this soon, MG Linux build is broken without it :(

**Comment by KonajuGames** [comment]
Merged.

**Comment by cra0zy** [comment]
Thank you ^^

**Pull request merged**
