### PR TITLE
GamePadState.PacketNumber fix(WinDX)

### PR DESCRIPTION
**Pull request by Shqrdx**
Fix for https://github.com/mono/MonoGame/issues/4002

### CODE REVIEW

**Comment by Shqrdx** [comment]
@tomspilman @KonajuGames ? thoughts ?

**Comment by KonajuGames** [comment]
That looks good to me.  You've confirmed the behaviour in tests?

If @tomspilman agrees, I think this is good to be merged.

**Comment by Shqrdx** [comment]
@KonajuGames Yes, of course it worked like in XNA.

**Comment by KonajuGames** [comment]
> ah.. tests.. ?

This would need manual tests, which we haven't implemented yet.

I'm happy to merge this.  The fix looks good to me.

**Pull request merged**
