### PR TITLE
Win10 RTM support

### PR DESCRIPTION
**Pull request by BrianPeek**
Updated project files for MonoGame.Framework, new project templates, but
no NuGet support (yet)

### CODE REVIEW

**Comment by tomspilman** [comment]
I need to update the build box with the latest Win10 and SDK.  @BrianPeek - Should I just wait a few days for the final SDK or should the latest public available SDK be fine?

**Comment by tomspilman** [comment]
Also at some point we should fix `WindowsUAP` to something else... since `UAP` is no longer the correct term.  Thinking `WindowsAP` or `WindowsUP`.  To me `WindowsUWP` sounds redundant and `UniversalWindowsProject` is too long IMO.

**Comment by BrianPeek** [comment]
UWP is the correct/official term...Universal Windows Platform.  I was going to rename but didn't think it was worth it at this point.  :)

**Comment by KakCAT** [comment]
Hi!

I'm unable to compile monogame with the new Windows 10 RTM + VS2015 RTM + current SDK. Is this PR supposed to fix this?

(I'm getting the following errors:

Error		Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	MonoGame.Framework.WindowsUAP		

Error		Cannot resolve Assembly or Windows Metadata file 'System.Runtime.dll'	MonoGame.Framework.WindowsUAP	D:\utils\coding\monogame\monogame_2015_07_29\MonoGame\MonoGame.Framework\MonoGame.Framework.WindowsUAP.csproj	

)

**Comment by tomspilman** [comment]
> Is this PR supposed to fix this?

Yes...  i'm working on getting the build server upgraded now.

**Comment by KakCAT** [comment]
thanks, Tom. You rock! ^^

**Comment by tomspilman** [comment]
Ok... build server updated, but still some issue with the project:

> [20:21:56]  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets(19,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [C:\BuildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MonoGame.Framework.WindowsUAP.csproj]

I suspect we didn't fix the Protobuild script correctly.

**Comment by BrianPeek** [comment]
Debug and Release builds are working using the Protobuild-generated project on 2 of my machines via VS2015 IDE and just running msbuild from the command line against the .sln.  Not sure how the build system here is configured, though, so I'm sure I'm not comparing apples to apples.  :)

**Comment by tomspilman** [comment]
I think it is my fault.  I installed VS 2015 Community which seemed to say it included Windows 10 SDK... but it doesn't.  It required an additional download which i'm finishing now.

**Comment by BrianPeek** [comment]
I think I just accidentally added a 2nd commit to this PR when I merged up with the upstream MonoGame.  Let me know if this screws things up and if i need to redo the PR.  I suck at git.

**Comment by Nezz** [comment]
Tested & working :)

We should no longer reference `System` and `System.Runtime.Serialization` as they are automatically referenced and result in warnings.

**Comment by tomspilman** [comment]
> Tested & working :)

Still not sure what i'm missing in the build server:

 - Installed Win10 Pro RTM
 - Installed VS 2015 Community Edition RTM.
 - Via VS2015's "New Project" dialog I installed the Win10 SDK.
 - I was able to create a new UWP project, build, and run it.

**Comment by Nezz** [comment]
@tomspilman Try installing this one?
https://go.microsoft.com/fwlink/p/?LinkId=534599

**Comment by tomspilman** [comment]
I'll try it .... not sure why the one VS installed for me wouldn't be the same.  Too many ways to do the same thing.

**Comment by Nezz** [comment]
By not releasing dev tools with VS RTM they caused a lot of trouble. What finally solved for me was using the linked installer to install the dev tools.

There seems to be an issue though. The presence of `project.json` makes VS2015 try to restore the packages for other MonoGame platform projects, which will fail:
```
1>------ Build started: Project: MonoGame.Framework.Windows, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(83,5): error : Couldn't find the required information in the lock file. Make sure you have .NETFramework,Version=v4.0 mentioned in your targets.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by Nezz** [comment]
I also upgraded my NuGet to 3.1 (my VS 2015 RTM professional came with 3.0).

**Comment by BrianPeek** [comment]
Grr...seeing the same thing with the non-UWP projects getting confused by the project.json file just being in the directory, even if it isn't included in the project file itself.  Not sure how to solve...it needs to be in the same directory as the csproj file.  Maybe move the UWP csproj to its own directory with the project.json?

**Comment by Nezz** [comment]
We need input on this from someone who has experience with NuGet 3.

**Comment by azchohfi** [comment]
I'll call the cavalry! (Microsoft/MVPs)

**Comment by BrianPeek** [comment]
@azchohfi I work there, already on it...waiting for some responses.  Thanks!  :)

**Comment by azchohfi** [comment]
Oh, great, thanks @BrianPeek!

**Comment by Nezz** [comment]
@tomspilman Did you manage the sort out the problems with the build server?

**Comment by tomspilman** [comment]
@Nezz - Not yet... but making progress I think.

The current error is:

> C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(83,5): error : The package Microsoft.CSharp with version 4.0.0 could not be found in C:\WINDOWS\system32\config\systemprofile\.nuget\packages. Run a NuGet package restore to download the package.

**Comment by Nezz** [comment]
@tomspilman NuGet 3 no longer downloads the packages to the solution root, but downloads them to a user level storage instead. It is normally in the `C:/Users/<Username>/.nuget/packages` folder, but if a process is spawned without user information, it will end up in `C:\WINDOWS\system32\config\systemprofile`. I guess that NuGet does not join the paths correctly and a `\` is missing.

This might contain some information on fixing the build server:
http://superuser.com/questions/704749/my-user-redirected-to-system32-config-systemprofile-how-to-solve-it

**Comment by Nezz** [comment]
A workaround was to add net40 to the project.json like this:

```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"
  },
  "frameworks": {
    "uap10.0": {},
    "net40": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

However, it's rather ugly because we would need to add all platforms and nuget will try to restore the UWP packages, which happens to be a total of 79 packages:

**Comment by Amimox** [comment]
Ok, I am trying to set up an UAP Monogame Windows 10 Project in VS Enterprise and I get the error that my project should be converted to RTM.
Anyone got it work or fixed it? Where can I download fixed version of MonoGame, I am new  to Github.
My best wish is to make Windows 10 games so it would be nice to fix this issue.
Thanks !

**Comment by tomspilman** [comment]
@Nezz - Thanks... the issue was that the build server was running under the system account and NuGet sucks. :)

So this is all building now.  Is it ok to merge?

**Comment by BrianPeek** [comment]
The project.json may break the other builds if they are compiled with vs2015 as well. Otherwise, the uwp stuff seems to work...

Sent from my Windows Phone
________________________________

**Comment by tomspilman** [comment]
> The project.json may break the other builds if they are compiled with vs2015 as well. 

They are not... we have VS2015 and UWP projects only on the Win10 build slave machine.  So it won't hurt the build at the moment.

However we do need to address that issue eventually.  I have no plans to put project files in separate folders... this is really something NuGet needs to fix.  It was stupid to assume one project per-folder... it is line they never worked on a real cross platform project.

Just when i thought i couldn't hate NuGet more.

**Comment by Amimox** [comment]
Where to download the corrected Windwos 10 UAP VS template?
Please.

**Comment by tomspilman** [comment]
Ok... merging now!

**Comment by tomspilman** [comment]
> Where to download the corrected Windwos 10 UAP VS template?

You can download the new development build installer from here in 20 minutes or so:

http://www.monogame.net/downloads/

**Comment by JesseLenney** [comment]
Great work guys.

Only issue is the *Microsoft.NETCore.UniversalWindowsPlatform* NuGet package doesn't seem to be loaded in the MG UAP template when creating a fresh solution. Rebuilding the project corrects this.

Plans to fix the template? Or is this an issue with NuGet?

**Comment by Nezz** [comment]
Sounds like a nuget bug to me. Package restore should occur before building.

**Comment by Nezz** [comment]
NuGet issue regarding the package restore for projects other than UWP: https://github.com/NuGet/Home/issues/1102

**Comment by TiBall** [comment]
had the same error when building a clean project with mongame 3.4 uap nuget referenced:
Could not copy the file "C:\Users\till\.nuget\packages\MonoGame.Framework.WindowsUAP\3.4.0.459\lib\netcore\MonoGame.Framework\MonoGame.Framework.xr.xml" because it was not found.

Easy way to resolve:
copy the files from C:\Users\username\.nuget\packages\MonoGame.Framework.WindowsUAP\3.4.0.459\lib\netcore\ to C:\Users\till\.nuget\packages\MonoGame.Framework.WindowsUAP\3.4.0.459\lib\netcore\MonoGame.Framework

**Comment by KakCAT** [comment]
using monogame from sources I was having the same xr.xml missing problem when compiling the final game. 

The solution in my case was ticking in the monogame build options "Generate library layout". I think that switch would probably have to be ticked in the monogame project (and might be the cause of the problems in NuGet )

**Comment by BrianPeek** [comment]
@JesseLenney Can you provide any other details?  I'm not seeing this here so not sure where to look.  When I create a new Win10 MonoGame project, hitting build right out of the gate does the restore and the project builds without issue.  Does this repro for you on every new project creation?

@TiBall I haven't had the time to build a proper UWP NuGet package yet, so things not working there may be expected.  Hoping to find some time this weekend! :)

**Pull request merged**
