### PR TITLE
Remove raw asset support from ContentManager

### PR DESCRIPTION
**Pull request by KonajuGames**
Removes the raw asset support from ContentManager and the Normalize methods from various content readers.  Also removes DXT decompression at load time as we now have content build pipeline support for all common texture compression formats.

Raw assets should be loaded through the various methods meant for this, such as Texture2D.FromStream.

### CODE REVIEW

**Comment by tomspilman** [comment]
I would love to do this now...  but I think we should hold this PR for the release after next.  Just seems like we still have some pipeline issues to resolve.

**Comment by tomspilman** [comment]
@KonajuGames @cra0zy @dellis1972 - Seems time to finally merge this.  Agreed?

@KonajuGames - This PR needs to be rebased first.

**Comment by cra0zy** [comment]
:+1

**Comment by KonajuGames** [comment]
Damned git rebase.  Going to redo this PR.

**Comment by cra0zy** [comment]
So many colors :D

**Comment by KonajuGames** [comment]
Superceded by #4726. Closing.

**Pull request closed without merging**
