### PR TITLE
iOS: robust rotation handling for iPad/iPhone devices

### PR DESCRIPTION
**Pull request by rtabbara**
* Should address issue raised by #3271
* In particular, both iPad/iPhone devices should correctly autorotate
* The main problem was that previously, iPad devices would not receive TraitCollectionDidChange calls after a rotation, so this is an alternate solution

### CODE REVIEW

**Comment by tomspilman** [comment]
@Nezz @TheRoboZ @Andreyul

What are your thoughts on this PR?

**Comment by dellis1972** [comment]
@tomspilman this looks ok to me, but i'll let someone with a bit more experience on iOS weigh in :)

**Comment by Nezz** [comment]
I'll check this out tomorrow.

**Comment by Nezz** [comment]
Looking into it now...

**Comment by Nezz** [comment]
Works fine with an iPad running iOS 8.1.
Doesn't work correctly with an iPhone 4S running iOS 7.1. The GraphicsDevice.Viewport is 640x960 instead of 960x640

**Comment by rtabbara** [comment]
Fwiw, this change only impacts iOS 8+, so if indeed iOS 7 rotation is
broken then we'll need to do something extra. I suppose I shouldn't have
called the PR robust.

**Comment by Nezz** [comment]
The iPad running iOS 8 is broken too as I can still reproduce #3271

**Comment by rtabbara** [comment]
Thanks @Nezz for looking into this, I'll close this for now and take a look at it again with the Unified changes incorporated.

**Pull request closed without merging**
