### PR TITLE
Moved Stock Effect Resources

### PR DESCRIPTION
**Pull request by tomspilman**
This PR moves the resource loading for the stock effects to a partial class that can be overloaded for new platforms.

### CODE REVIEW

**Comment by tomspilman** [comment]
@dellis1972 - Wrote something a bit more custom here instead of `Lazy<T>`, but gives us a similar result...  the effect bytecode isn't loaded until it is first accessed.

**Comment by KonajuGames** [comment]
That sound like a good solution to me.

**Comment by tomspilman** [comment]
@KonajuGames @dellis1972 - I'm done with this one.

**Comment by KonajuGames** [comment]
Merging.

**Pull request merged**
