### PR TITLE
Updated copyright to 2016

### PR DESCRIPTION
**Pull request by aqnouch**

### CODE REVIEW

**Comment by tomspilman** [comment]
Thanks @aqnouch !

**Comment by tomspilman** [comment]
You mind fixing the year on the Nuget .nuspec files too:

https://github.com/mono/MonoGame/tree/develop/NuGetPackages

**Comment by aqnouch** [comment]
Done, and happy new year :smile:

**Comment by tomspilman** [comment]
Thanks @aqnouch .

**Pull request merged**
