### PR TITLE
Fix Song (#4666) in Windows

### PR DESCRIPTION
**Pull request by neofuji**
#4666

### CODE REVIEW

**Comment by tomspilman** [comment]
Anyone have time to test this change?  It only affects the Windows desktop DX platform.

**Comment by mrhelmut** [comment]
According to the Media Foundation documentation (https://msdn.microsoft.com/en-us/library/windows/desktop/ms704703.aspx), ```MediaEventTypes.SessionEnded``` happens when the last item queued has finished playing, not after each item ends. ```OnSongFinishedPlaying``` wouldn't be triggered by ```Song``` changes if multiple ones are queued through ```MediaPlayer.Play(SongCollection collection)```.
I can't test it, though.

@neofuji Would you mind double-checking that #4666 happens on Windows (DirectX) projects and not only on DesktopGL? I would assume that Media Foundation deals with this correctly.

**Comment by neofuji** [comment]
@mrhelmut #4666 certainly happens on Windows.
The `Song` queue depends on `MediaPlayer`, not on Media Foundation.
So queued Songs are passed to Media Foundation one by one.

**Comment by mrhelmut** [comment]
So I'm fine with this. :+1:

**Comment by KonajuGames** [comment]
Merging this.  Thanks @neofuji.

**Comment by KonajuGames** [comment]
@mrhelmut, the OggStreamer error you raised in #4666 will need a separate PR if you get around to fixing it.

**Pull request merged**
