### PR TITLE
New constructors for Rectangle

### PR DESCRIPTION
**Pull request by Shqrdx**
This constructor uses two Point's and helps developers to write their 2d games more clearly and faster. At least I found this helpful.

update : added Rectangle(Vector2,Vector2)  and Rectangle(float,float,float,float) constructors.

### CODE REVIEW

**Comment by cra0zy** [comment]
Could you add float float float float and Vector2 Vector2 constructors? I think those would be really useful.

**Comment by Shqrdx** [comment]
Of course

**Comment by Shqrdx** [comment]
@tomspilman Be sure - Last commit does not cause ambiguity, but it would not cause confusion for new developers ? What do you think ?

**Comment by Shqrdx** [comment]
@tomspilman Is it ok for merging ?

**Comment by tomspilman** [comment]
Thanks!

**Pull request merged**
