### PR TITLE
Fixes OpenTK warnings

### PR DESCRIPTION
**Pull request by prollin**
Fixes a bunch of OpenTK related warnings that were introduced by the support of Xamarin Unified API (#3382). No functionality is altered in this PR.

### CODE REVIEW

**Comment by tomspilman** [comment]
This look ok @Nezz @dellis1972 ?

**Comment by Nezz** [comment]
Works correctly on iOS. I'll check out the Android version too just to be sure.

**Comment by dellis1972** [comment]
looks ok, will wait for @Nezz test on android though.

**Comment by Nezz** [comment]
Works correctly.

**Comment by prollin** [comment]
@tomspilman do you know what went wrong there? I tried to find the source of the build failure but couldn't see anything

**Comment by tomspilman** [comment]
Looks like the Xamarin build process itself crashed building for iOS:

```
[17:19:09]Xamarin Studio Build Tool
[17:19:09]Loading solution: /Applications/buildAgent/work/f26e5a04a66fcbdb/MonoGame.Framework.iOS.sln
[17:19:09]   Loading solution: /Applications/buildAgent/work/f26e5a04a66fcbdb/MonoGame.Framework.iOS.sln
[17:19:09]      Loading projects ..
[17:19:09]
[17:19:09]Unhandled Exception:
[17:19:09]System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
[17:19:09]  at MonoDevelop.Projects.DotNetProject.CheckReferenceChange (FilePath updatedFile) [0x00015] in /Users/builder/data/lanes/monodevelop-lion-monodevelop-5.7-branch/b70bab61/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:459 
[17:19:09]  at MonoDevelop.Projects.DotNetProject.OnFileChanged (System.Object source, MonoDevelop.Core.FileEventArgs e) [0x00034] in /Users/builder/data/lanes/monodevelop-lion-monodevelop-5.7-branch/b70bab61/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:483 
[17:19:09]  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
[17:19:09]  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:230 
[17:19:09]  --- End of inner exception stack trace ---
[17:19:09]  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00069] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:238 
[17:19:09]  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/corlib/System.Reflection/MethodBase.cs:114 
[17:19:09]  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00107] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/corlib/System/Delegate.cs:462 
[17:19:09]  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00018] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/corlib/System/MulticastDelegate.cs:70 
[17:19:09]  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/corlib/System/Delegate.cs:407 
[17:19:09]  at MonoDevelop.Core.EventQueue+<RaiseEvent>c__AnonStorey0.<>m__0 (System.Object ) [0x00001] in /Users/builder/data/lanes/monodevelop-lion-monodevelop-5.7-branch/b70bab61/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs:834 
[17:19:09]
```

I'll trigger a rebuild and see what happens.

**Comment by tomspilman** [comment]
Ok... so just some random failure there.  I guess this is safe to merge now.

**Pull request merged**
