### PR TITLE
Update the build script to download the Archived Android and OUYA

### PR DESCRIPTION
**Pull request by dellis1972**
binaries from the MacBuild bot. If it can.

We'll need to update the MacBot to archive these files.

### CODE REVIEW

**Comment by dellis1972** [comment]
@tomspilman  we'll need to make the changes to the bots we talked about before we pull this in. Although it shouldn't fail atm.

**Comment by tomspilman** [comment]
> We'll need to update the MacBot to archive these files.

We build Android and OUYA on Windows... so I guess that makes this more complicated right?

**Comment by dellis1972** [comment]
@tomspilman check your email about this one. Also I found that the Mac installer is missing the following assemblies

Android
OUYA
DesktopGL

One of the other PR's fixes DesktopGL  (#4509)

**Comment by dellis1972** [comment]
Closing PR

**Pull request closed without merging**
