### PR TITLE
Added GetPickRay method to MathHelper

### PR DESCRIPTION
**Pull request by Shqrdx**
I think its good to add this method to MonoGame. This is common routine and developers should not bother himself for write it every time they want to pick object in 3d world.

### CODE REVIEW

**Comment by Shqrdx** [comment]
@tomspilma needs your opinion and suggestion how to fix it.

**Comment by cra0zy** [comment]
```
[03:41:52][Step 1/1] NAnt output
[03:41:52][NAnt output]      [exec]   C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\MGCB\bin\Windows\AnyCPU\Release\MGCB.exe", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\Pipeline\Pipeline.Windows.csproj]
[03:41:52][NAnt output]      [exec] 
[03:41:52][NAnt output]      [exec] 
[03:41:52][NAnt output]      [exec] "C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework.Windows.sln" (Build target) (1) ->
[03:41:52][NAnt output]      [exec] "C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\Pipeline\Pipeline.Windows.csproj" (default target) (9) ->
[03:41:52][NAnt output]      [exec] (CoreCompile target) -> 
[03:41:52][NAnt output]      [exec]   Windows\ContentIcons.cs(60,42): warning CS0168: The variable 'aex' is declared but never used [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\Pipeline\Pipeline.Windows.csproj]
[03:41:52][NAnt output]      [exec]   Windows\ContentIcons.cs(66,45): warning CS0168: The variable 'fnfex' is declared but never used [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\Pipeline\Pipeline.Windows.csproj]
[03:41:52][NAnt output]      [exec] 
[03:41:52][NAnt output]      [exec] 
[03:41:52][NAnt output]      [exec] "C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework.Windows.sln" (Build target) (1) ->
[03:41:52][NAnt output]      [exec] "C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj" (default target) (2) ->
[03:41:52][NAnt output]      [exec] (CoreCompile target) -> 
[03:41:52][NAnt output]      [exec]   c:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MathHelper.cs(145,52): error CS0246: The type or namespace name 'Viewport' could not be found (are you missing a using directive or an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj]
[03:41:52][NAnt output]      [exec]   c:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MathHelper.cs(165,52): error CS0246: The type or namespace name 'Viewport' could not be found (are you missing a using directive or an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj]
[03:41:52][NAnt output]      [exec]   c:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MathHelper.cs(185,54): error CS0246: The type or namespace name 'Viewport' could not be found (are you missing a using directive or an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj]
[03:41:52][NAnt output]      [exec]   c:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MathHelper.cs(204,54): error CS0246: The type or namespace name 'Viewport' could not be found (are you missing a using directive or an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj]
[03:41:52][NAnt output]      [exec] 
[03:41:52][NAnt output]      [exec]     64 Warning(s)
[03:41:52][NAnt output]      [exec]     4 Error(s)
[03:41:52][NAnt output]      [exec] 
[03:41:52][NAnt output]      [exec] Time Elapsed 00:01:17.32
[03:41:52][NAnt output] 
[03:41:52][NAnt output] BUILD FAILED
```

**Comment by Shqrdx** [comment]
@tomspilman So how you look on this ? Is it good or bad ?

**Comment by Shqrdx** [comment]
@tomspilman Do you think its a bad ?

**Pull request closed without merging**
