### PR TITLE
[Gtk Pipeline] Content file icons based on file type

### PR DESCRIPTION
**Pull request by cra0zy**
#3609 for Gtk Pipeline.. I can't believe I managed to do it...
untitled2

### CODE REVIEW

**Comment by tomspilman** [comment]
Is this usable on Mac too?

**Comment by tomspilman** [comment]
```
Tools/Pipeline/Gtk/Widgets/ProjectView.cs(189,24) : error CS0103: The name `Gio' does not exist in the current context
Tools/Pipeline/Gtk/Widgets/ProjectView.cs(278,28) : error CS0103: The name `Gio' does not exist in the current context
Tools/Pipeline/Gtk/Global.cs(49,13) : error CS0234: The type or namespace name `FileInfo' does not exist in the namespace `GLib'. Are you missing an assembly reference?
Tools/Pipeline/Gtk/Global.cs(59,34) : error CS0841: A local variable `info' cannot be used before it is declared
```

**Comment by cra0zy** [comment]
> Is this usable on Mac too?

The code is usable on Mac, the problem is I can't setup a wrapper for Mac without me actually testing it on a Mac...

Also the Mac virtual machine I talked about earlier is not good, I can't even create a new project in xamarin studio, and it crashed before I could install xcode...

**Comment by tomspilman** [comment]
> Also the Mac virtual machine I talked about earlier is not good

Unfortunately that is the experience others have had too.  It just is not something Apple wants to allow which is unfortunate for everyone.

**Comment by tomspilman** [comment]
Cool... merging!

**Pull request merged**
