### PR TITLE
Ported MonoGame to use the new Xamarin iOS Unified API

### PR DESCRIPTION
**Pull request by MarkoBL**
This is a port of MonoGame to the new Xamarin Unified API on iOS (http://developer.xamarin.com/guides/cross-platform/macios/unified/). The Classic API is a dead end on iOS, as Apple requires all apps to include a 64 bit binary, starting February 1, 2015 https://developer.apple.com/news/?id=10202014a

Protobuild doesn't support the unified api yet, so you'll have to modify the project files (MonoGame.Framework.iOS.csproj and MonoGame.Framework.Net.iOS.csproj) for now by hand. Change the ProjectTypeGuid from
 ```6BC8ED88-2882-458C-8E55-DFD12B67127B``` to ```FEACFBD2-3405-455C-9665-78FE426C6842``` 
and replace the occurence of 
```<Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.MonoTouch.CSharp.targets" />``` or ```<Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />``` 
with
 ```<Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />```

These changes need to be done on the ThirdParty/Lidgren.Network/Lidgren.Network.iOS.csproj project file too, and you need to change ```<Reference Include="monotouch" />``` to ```<Reference Include="Xamarin.iOS" />```

### CODE REVIEW

**Comment by Nezz** [comment]
We really need to get this to work soon. People won't be able to submit new apps without this from the 1st of February.

**Comment by tgjones** [comment]
Can I help? What remains to be done? I only have the Starter edition of Xamarin.iOS, I haven't tried MonoGame with it yet so I don't know whether MG fits within the Starter size limit.

**Comment by Nezz** [comment]
The issue is with the project files, which are generated by @hach-que's Protobuild.

**Comment by hach-que** [comment]
Are there identified changes to be made to the generated projects that make them work?  As I don't have Xamarin iOS (nor a Mac), there's no way I can fix issues by trial and error.  I basically need a list of changes that when made to the generated projects then allow the project to build correctly.

As far as I know, the only reported real issue is that the Xamarin.iOS reference is not resolved, but I don't know what changes are required to make the reference work correctly.

**Comment by tgjones** [comment]
> Can someone confirm that https://github.com/hach-que/Protobuild/raw/ios-change/Protobuild.exe produces the correct result for the new iOS API?

@hach-que, is that still the version of `Protobuild.exe` that I should try? And should I run that on Windows (I guess so, given the file extension)? I have read through this whole thread, but I'm not exactly sure what needs to be done. I do have a Mac, so I'll be happy to help out, just need some context to get started.

**Comment by hach-que** [comment]
Yes, that should be the version to use.  I think you'll need to clone this PR and then replace Protobuild.exe in the root of the repo with the downloaded version.  Then from a terminal run "mono Protobuild.exe --generate iOS".

Once done, open the generated solution in Xamarin Studio and build the code.  If it builds successfully, then great, everything is working.

If it doesn't build successfully, then you'll need to modify the projects so that they do build.  Once they're building successfully (make sure you do Rebuild Solution), paste the contents of the project and solution files here and I'll the be able to translate the differences into modifications for Protobuild.

**Comment by Nezz** [comment]
Make sure to test the project files on Mac. They built for me on Windows, but did not actually work on Mac.

**Comment by MarkoBL** [comment]
Well, everything is working as expected and tested on iOS, Mac and Android, and I've updated the pull request, but I guess I messed it up, it contains all the commits since my last pull :/

**Comment by tgjones** [comment]
Here's what I've done:

1. Cloned this PR.

2. Replaced `Protobuild.exe` in the root of the repo with [this version](https://github.com/hach-que/Protobuild/raw/ios-change/Protobuild.exe)

3. From a terminal, ran `mono Protobuild.exe --generate iOS`. Worked fine, showed a few lines of output, and generated `MonoGame.Framework.iOS.sln` and other project files.

4. Opened `MonoGame.Framework.iOS.sln` in Xamarin Studio. A couple of issues here, although they didn't seem to prevent successfully compilation:

  1. the Lidgren.Network.iOS project has a red cross next to it, and the tooltip says "Invalid configuration mapping". I think it's because the two configurations for that project (`Debug` / `Release`) - don't match the solution configurations.
  2. Expanding MonoGame.Framework.Net.iOS, and then the References node, I see a red cross next to the Lidgren.Network.iOS reference, and the tooltip says "Incompatible target framework (MonoTouch Framework).

5. Ignored that issue, and built the MonoGame.Framework.iOS project. That compiled successfully, with no errors, and in Finder I can see the resulting DLL.

6. Built the MonoGame.Framework.Net.iOS project. That also compiled successfully, and I can see the resulting DLL in Finder.

So it seems like the hard work is done, but there's some tidying up to do to get Lidgren fully working. Let me know if you need more info about the two issues I mentioned above.

**Comment by tgjones** [comment]
(@MarkoBL that's why it's usually a good idea to create a separate branch for pull requests, so you can keep them isolated from any other changes you might make.)

**Comment by MarkoBL** [comment]
@tgjones Yes, lesson learned. It was my first pull request on GitHub, so I didn't know that. 
Any ideas how to "fix" this?

**Comment by tgjones** [comment]
@MarkoBL Do you just want the original 3 commits, up to and including fb5ebda886735ee90631cfe995c3906177b6d700? (i.e. not 323a79ef536ab25f609e9fc93c7c78a4029974ed and not 58be976db1fa68bc625a239607a2e5a143ca340e)

I'm far from a git expert, but here's how I might do it: 

```
git checkout fb5ebda886735ee90631cfe995c3906177b6d700
git checkout -b xamarin-ios-unified-api
```

That should "rollback" to the commit you want, and then create a new branch based on that commit. But most of my git-ing is done from GUIs, so don't take my word for it :)

**Comment by MarkoBL** [comment]
Thanks for the help @tgjones. I created a new pull request from a branch with all the changes applied https://github.com/mono/MonoGame/pull/3382.

**Pull request closed without merging**
