### PR TITLE
Fixed Windows Installer Version Number

### PR DESCRIPTION
**Pull request by tomspilman**
We now pull the Windows installer version number from the TeamCity environment variable.  This ensures we can update the build version from TeamCity and have the build reflect that change.

### CODE REVIEW

**Comment by Shqrdx** [comment]
I found bug inside installer - it suggest install MonoGame to all Visual studio versions , however I have only VS2013 Community edition...

**Comment by tomspilman** [comment]
> it suggest install MonoGame to all Visual studio versions 

 Check your documents folder.  Do you have a "Visual Studio 2010" and "Visual Studio 2012" folder in there?  That is what it is looking for to detect if it should install templates for them.

> however I have only VS2013 Community edition

I haven't tested VS2013 community edition at all, so I don't know if we properly install templates for it or not.

**Comment by Shqrdx** [comment]
> Do you have a "Visual Studio 2010" and "Visual Studio 2012" folder in there? 
Nope, only Visual Studio 2013

**Comment by tomspilman** [comment]
> Nope, only Visual Studio 2013

Weird...  i'll investigate some.

**Comment by Shqrdx** [comment]
image

**Comment by tomspilman** [comment]
Thanks @Shqrdx ... that helps!

**Pull request merged**
