### PR TITLE
Implement BackgroundContext loading for DesktopGL

### PR DESCRIPTION
**Pull request by dellis1972**
@cra0zy @prollin comments welcome :)

### CODE REVIEW

**Comment by cra0zy** [comment]
:computer:  :speech_balloon: :+1: (roughly translated: everything looks good)

**Comment by prollin** [comment]
@dellis1972 using glFinish vs glFlush to synchronize the 2 contexts is something I have been looking at recently. For iOS, [glFlush is supposed to be enough ](https://developer.apple.com/library/ios/qa/qa1612/_index.html) but it might be worth experimenting on various PC GPU to have optimal background gpu upload.
FYI we also removed the extra calls to GL.Finish in `Texture2D.SetData()` since this should only be called if *not* on the UI thread. Reading data back from the gpu (glReadData) automatically flushes the pipeline already.

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy - Should we try to get this into the 3.6 release or should we wait to merge this?

**Comment by cra0zy** [comment]
3.6

**Comment by endimilojkoski** [comment]
I can confirm that loading for me is MUCH faster with this.

**Comment by dellis1972** [comment]
awesome :)

**Comment by tomspilman** [comment]
This good to merge then? @KonajuGames  @dellis1972 @cra0zy @mrhelmut ?

**Comment by cra0zy** [comment]
It is. The "glFinish vs glFlush" discussion can remain for another PR/issue.

**Comment by tomspilman** [comment]
Ok...  going for it.

**Comment by mrhelmut** [comment]
I have a GL question related to this.

I'm loading ```Texture2D``` with a thread while drawing other stuff. It can happen occasionally that OpenGL throws a 1282 (Invalid Operation) error upon loading a texture.

This also happened with OpenTK, which I assume was doing the same as this PR.

Is there a safe way to load textures from threads with GL? I always end up using a thread-safe content loader (which blocks draw calls until textures are loaded) to work around this. Before this PR, I've been able to remove the thread-safe loader, but I now need it again.

Should this be considered as an issue?

**Comment by KonajuGames** [comment]
OpenGL drivers and multi-threading don't have a good history.
http://richg42.blogspot.com.au/2014/05/things-that-drive-me-nuts-about-opengl.html

Put simply, I believe there is no 100% safe way to multi-thread OpenGL.  It was never designed for it in the first place and not all driver developers get it right.

**Comment by endimilojkoski** [comment]
I can also confirm that on initial content Loading on new Thread my game in rare cases crashes.
If I start it again it is all good.

**Comment by mrhelmut** [comment]
@KonajuGames That's what I assumed. Thanks for the clarification.

@endimilojkoski If that may be of any help: http://konaju.com/?p=27
You will have a few skipped frames during loading, but at least it's safe.

**Comment by KonajuGames** [comment]
> @endimilojkoski If that may be of any help: http://konaju.com/?p=27
> You will have a few skipped frames during loading, but at least it's safe.

That will help the C# side, but not the OpenGL driver side.

**Comment by endimilojkoski** [comment]
Thanks guys, will think about it for next update :)
It is not a big deal, it happens in very rare cases and simple retry does the job so it is not critical :)

**Comment by Scellow** [comment]
What i hate the most in games, it's when the window freeze while it load assets, it drive me crazy, if you use steam overlay and chat with someone, you are fucked up

**Comment by mrhelmut** [comment]
Turns out the error still occurs frequently despite thread-safing assets loading. It wasn't happening before or with OpenTK.

**Comment by mrhelmut** [comment]
After giving this some heavy testing, I think it exposes more issues than it would solve. While it indeed allows to load assets faster by not blocking them on the UI thread, if assets are loaded from a thread there is an uncontrollable risk of GL errors depending on driver vendors.

If you are fine with this, I'd like to add an option to disable background context.

**Comment by dellis1972** [comment]
I think adding a way to disable it might be a good idea. You can still load
stuff on a background thread, it just will marshall the GL call over to the
main context.

**Comment by tomspilman** [comment]
> It wasn't happening before or with OpenTK.

Then it shouldn't happen now with SDL2...  we are calling the same OpenGL here.  This suggests a mistake in our implementation that we really should find and fix.

> I'd like to add an option to disable background context.

IMO we have should either fix the bugs or remove the feature.

**Comment by mrhelmut** [comment]
I'm not enough into OpenGL to grasp the full picture, but the more I read about GL and context threading, the more I think that we should block all assets loading/creation on the GL/UI thread.
As @KonajuGames highlighted, even if we proof the C# thread-safety, there is nothing that ensure that everything is going well on the driver side. Based on what I read, NVIDIA drivers are more susceptible to crash because of context switching and thread races and Apple drivers are more thread-friendly (which confirms my experiences, I've only seen this problem occurring on NVIDIA cards and Windows, no matter if Flush/Finish are there). While threading GL seems to be fine for streaming data to the GPU, it seems not advisable to thread data setup.

I would be favorable to a revert. What do you think?

As to why @endimilojkoski experiences content loading this longer, there must be something else to the problem because texture loading should be something quite fast.

**Comment by KonajuGames** [comment]
> As to why @endimilojkoski experiences content loading this longer, there must be something else to the problem because texture loading should be something quite fast.

The reason for the slower loading performance is that it limits the loading to one GPU resource per frame, rather than potentially a few per frame when it's on a background thread that is not synchronized to the main thread.

Actually, I just had a thought, and fixing this would help a lot with this performance issue.  We block the background thread on a call to `Texture2D.SetData()`, but a texture load calls `Texture2D.SetData()` for each mipmap.  So it actually loads one mipmap per frame instead of the entire texture.  This could be easily remedied by adding a call to `Threading.BlockOnUIThread()` encapsulating the `levelCount` loop in `Texture2DReader`, `Texture3DReader` and `TextureCubeReader`.  Nested calls to `Threading.BlockOnUIThread()` aren't a problem as the inner calls will just execute immediately.

**Comment by mrhelmut** [comment]
Interesting, I'll try to take a look at this, thanks.

**Comment by mrhelmut** [comment]
FYI #4972

**Pull request merged**
