### PR TITLE
Remove legacy code to load "non-content" files

### LINKED ISSUE #3483: Remove code to load non-content files in ContentManager (after v3.3)
IMO, this line in ContentManager is fairly unhelpful:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentManager.cs#L315

``` csharp
if (string.IsNullOrEmpty(assetName))
{
    throw new ContentLoadException("Could not load " + originalAssetName + " asset as a non-content file!", ex);
}
```

It just covers up the original exception (unless you look at `InnerException`, but not everyone knows to do that).

If the non-content fallback file can't be found, couldn't we just re-throw the original exception?

### PR DESCRIPTION
**Pull request by tgjones**
Fixes #3483.

I think it's about time we removed this code; it's nothing but confusing, unless anyone still relies on it?

### CODE REVIEW

**Comment by tomspilman** [comment]
Let's wait for 3.5 to get out first then merge this.

**Comment by tgjones** [comment]
Sounds good to me.

**Comment by KonajuGames** [comment]
Same as my #4015. :)

**Comment by tgjones** [comment]
Oops :) I'll close this one, yours is more complete.

**Pull request closed without merging**
