### PR TITLE
Updated OpenTK Window

### PR DESCRIPTION
**Pull request by cra0zy**
With this I've done several things:
 - made the fullscreen not change the resolution but instead just stretch the viewport
   - this also fixes a bug when there are multiple monitors connected, on Linux it would disable the second monitor, and not correctly return their positions properly
 - made the fullscreen switchable during runtime
 - set the window to try and load the information from itself(assembly) if possible
 - Updated to the newest dependencies
   - contains a fix for Mouse Cursor being reset(moved) to the window bound after it looses focus

### CODE REVIEW

**Comment by dellis1972** [comment]
@cra0zy Windows DX really stretches stuff like that...? Not sure that is normal XNA behaviour, and it doesn't seem quite right to me.
@tomspilman ?

**Comment by cra0zy** [comment]
> Not sure that is normal XNA behaviour, and it doesn't seem quite right to me.

I'll look into it right away.

**Comment by cra0zy** [comment]
I thought that the WindowsDX had the correct behavior, but I was wrong... anyway I fixed the Window behavior to stretch when in fullscreen, and for while windowed to do this:  http://youtu.be/0wWpdi8El8g (I have no idea what it's called...)

**Comment by tomspilman** [comment]
Could we setup a unit test to verify the correct behavior?

**Comment by cra0zy** [comment]
> Could we setup a unit test to verify the correct behavior?

I think this should go to the manual test framework #3793, we can't really test this correctly with unit tests.

**Comment by cra0zy** [comment]
Don't merge this, I found 2 interesting things I want to add a fix for in here... different graphics drivers do different things....

**Comment by cra0zy** [comment]
Stuff done with last commit:
 - Fixed all graphics related exit errors... the only thing that is left that is close to exit error is: "AL lib: (WW) FreeContext: (0x1ee8210) Deleting 32 Source(s)", which is just an OpenAL warning, and I'll look into it in another PR
 - Improved fullscreen / window switching
 - fixed error that can occur with amd driver

**Comment by cra0zy** [comment]
@tomspilman Whats up with the build system? I looked at error that Win10 server reported and it said it couldn't find reference "System" O o

http://teamcity.monogame.net/viewLog.html?tab=buildLog&buildTypeId=MonoGame_DevelopWin10&buildId=9226#_state=71,72,73,119&focus=180

**Comment by cra0zy** [comment]
Stuff done with the last commit:
 - fixed Windows OpenTK exit error 
 - fixed Fullscreen not settable by default on Windows(was using the wrong GraphicsDevice code)
 - fixed Windows Fullscreen / Window switching behavior, window state was always normal and never false, plus resize was getting called twice....All and all, OpenTK is buggy...
 - made window border on Windows to switch immediately and not wait for delay like Linux does, since the bug only affects Linux

**Comment by bfloch** [comment]
Before submitting a new issue: With 3.4 I see a fullscreen behavior that is quite unexpected compared to XNA.

What I do is calculating a peferredbackbuffer dimension in the clientsizechanged event based on the Window.ClientBounds. When switching to fullscreen the Window.ClientBounds are not correctly updated in clientsizechanged, so that the preferredbackbuffer dimension stay at the last window's dimension = strechting in my case.

In XNA this works flawless. Wondering if you recent work solves this case?

**Comment by cra0zy** [comment]
@bfloch 
1) Are you using MonoGame DirectX? I don't remember ever seeing stretching in MonoGame OpenGL stuff... 
2) Can you post a simple Game1.cs code that shows this bug?

Also, I closed this because I made a pointless mess of stuff I was doing in this. My plan is to split it into multiple PRs for easier code reading starting with #4046 #4054. I need to wait for #4046 to be merged before continuing submitting PRs because otherwise it will create merge conflicts.

**Comment by bfloch** [comment]
@cra0zy Sorry for taking so long. Yes DirectX. Ok I got it figured. Apparently it was my mistake as I thought that ToggleFullscreen changed the Window.ClientBounds and therefore triggered an ClientSizedChanged event.
Apparently it doesn't and the only reason why XNA shows different results is because of its exclusive Fullscreen mode - therefore the small difference in behavior is not really worth mentioning.

I haven't compared to GL though.

**Pull request closed without merging**
