### PR TITLE
Fixed MacOS Installer if /usr/local/bin does not exist

### LINKED ISSUE #3791: OS X installer may need to create /usr/local/bin
OS X does not appear to have /usr/local/bin by default, even though it is in the PATH.
http://community.monogame.net/t/os-x-3-4-installer-package-issue/2355
The installer should create the directory if it does not exist and give it the appropriate permissions.

@dellis1972 Are you able to look into this?

### PR DESCRIPTION
**Pull request by dellis1972**
Fixes #3791

Can someone check the permissions please though :)

### CODE REVIEW

**Comment by tomspilman** [comment]
Anyone have time to test this?

**Comment by dellis1972** [comment]
darn... didn't work it seems :/

**Comment by dellis1972** [comment]
forgot to create /usr/local first. Will test again once the build bot finishes

**Comment by tomspilman** [comment]
@dellis1972 - So what is the status on this one?  Did it get tested?

**Comment by cra0zy** [comment]
I think doing:
```bash
if [ ! -d /usr/local/bin ]
then
	if [ ! -d /usr/local ]
	then
		mkdir /usr/local
		chgrp -R admin /usr/local
		chmod -R 755 /usr/local
	fi
	mkdir /usr/local/bin
fi
```
makes more sense

**Comment by dellis1972** [comment]
ok reworked based on @cra0zy's suggestion :)

**Pull request merged**
