### PR TITLE
Fixed incorrect color serialization using intermediate serializer.

### PR DESCRIPTION
**Pull request by Boxscape**
Fix for color serialization when using the intermediate serializer. (issue #4169 )

### CODE REVIEW

**Comment by danzel** [comment]
This looks good, but any chance of adding a test to the test project?

**Comment by tomspilman** [comment]
What @danzel means is adding a unit test which verifies this change works into here:

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/IntermediateSerializerTest.cs

**Comment by Boxscape** [comment]
Sure, i'll give it a shot.

**Comment by Boxscape** [comment]
Does this look ok?

**Comment by Boxscape** [comment]
Ok, so I learned about definition files. ;)

**Comment by tomspilman** [comment]
Looks good!  Thanks @Boxscape !

**Pull request merged**
