### PR TITLE
Split out Title Container into partial classes

### PR DESCRIPTION
**Pull request by dellis1972**
This should make porting to other platforms easier.
Also implemented the GetAssets/GetFiles functionality
from #4542

### CODE REVIEW

**Comment by dellis1972** [comment]
Will try to add unit tests.

**Comment by tomspilman** [comment]
@dellis1972 - Ughh... i already did this https://github.com/mono/MonoGame/pull/4520.  Was just waiting for 3.5 to ship to merge it.

**Comment by tomspilman** [comment]
If you are looking for platform code to break out into partials the stuff I haven't gotten to:

 - `GraphicsAdapter`
 - 'Mouse'

That is really most all that is left to cleanup like this.  We have some other stray `#if`s about the code base, but nothing as critical as these for platform extension.

**Comment by dellis1972** [comment]
@tomspilman. doh.. ok. I'll keep this around for the GetFiles stuff.

**Comment by tomspilman** [comment]
@dellis1972 - My PR is merged now... going to close this so you can resubmit a new one with the `GetFiles()` stuff.

**Pull request closed without merging**
