### PR TITLE
Fix MeasureString for texture fonts

### PR DESCRIPTION
**Pull request by nkast**
fix issue #3941

### CODE REVIEW

**Comment by tomspilman** [comment]
@nkast - Could we add something into the existing `FontTextureProcessor` tests to ensure things are working in the future:

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/FontTextureProcessorTests.cs

@KonajuGames - Any ideas?

**Comment by nkast** [comment]
I could add Assert for `.MeasureString()` and `.LineSpacing`.

**Comment by nkast** [comment]
Added a few checks in FontTextureProcessorTests.cs, is that good enough for making into 3.5?

**Comment by tomspilman** [comment]
Thanks @nkast ... merging!

**Comment by nkast** [comment]
Thanks!

**Pull request merged**
