### PR TITLE
Fix casing in protobuild file

### PR DESCRIPTION
**Pull request by WardBenjamin**
This is a fix for the Protobuild project definition for Monogame.Framework. It fixes a small casing issue in the ZLib files.

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Sorry for the number of commits, I forgot to rebuild the solutions before committing to check if they were now correct.

**Comment by emarcotte** [comment]
This fixes builds for me.

**Comment by funkmoth** [comment]
Same for me. Can't compile MonoGame without this.

**Comment by tomspilman** [comment]
Looks good... Thanks!

**Pull request merged**
