### PR TITLE
Patch to the UAP/UWP NuGet to resolve XR.xml deployment issue

### PR DESCRIPTION
**Pull request by DDReaper**
XR.xml files have to be deployed to a sub folder of the package name

### CODE REVIEW

**Comment by azchohfi** [comment]
I was about to report this! Thanks!

**Comment by tomspilman** [comment]
Note this isn't how things are when you build MonoGame from source for Win10.  The `MonoGame.Framework.xr.xml` is in the same folder as all the rest of the assemblies.

**Comment by DDReaper** [comment]
I know. It's a NuGet thing.
Same in Win8.1/wp8.1
Also the same with the hidden Themes\generic.xr/xaml


Oh the joys of packaging and deployment

**Comment by DDReaper** [comment]
Bump @tomspilman can we get this merged and the UAP NuGet package rebuilt and published as the current UAP/UWP NuGet package doesn't work.

**Comment by tomspilman** [comment]
Going to merge.

> the UAP NuGet package rebuilt and published 

We're not updating packages published to the NuGet site again until 3.5 ships.  If you want something earlier you can hook into the develop feed for NuGet packages here:

http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/

**Comment by DDReaper** [comment]
Understood @tomspilman.
But I'd recommend a patch release for just the UAP package as the current one is faulty.  Or put a statement out to not use it via the blog and inform adopters to just use the installer.

There is a lot of movement on the Win10 front and a lot of people looking for win10 frameworks/solutions.  MG got a leg up by being one of the first to support it, wouldn't want this to hamper it

**Comment by tomspilman** [comment]
We have 30 downloads of the WindowsUAP package on NuGet... the least downloaded packages we have in fact.

Also I know of a bunch of WindowsUAP issues that also need fixes.

I think it can wait for another couple of weeks for a better 3.5 release.

**Pull request merged**
