### PR TITLE
Throw helpful exception when vertex format doesn't match vertex declaration

### LINKED ISSUE #3235: Better error when VertexFormat doesn't match shader
During MVA demo had a cased where a models vertex format mismatched with the shader input format.

The error you get is below. @tomspilman says he can make that better.

An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

### PR DESCRIPTION
**Pull request by tgjones**
Fixes #3235.

As discussed in #3235, we don't have access to the input elements from the vertex shader, so the best we can do is tell the user the elements in the current vertex declaration.

### CODE REVIEW

**Comment by tomspilman** [comment]
Looks good to me... and a unit test!

**Comment by tgjones** [comment]
Following your lead, I'm firmly subscribed to the theory that MonoGame can only support the number of platforms that it does, with the help of a large suite of unit tests :) So I'm doing my (little) bit, and adding some tests with each PR.

**Comment by tomspilman** [comment]
Absolutely....  and if everyone added even a little to the unit tests on each PR we will be in really good shape within a year.

**Comment by tomspilman** [comment]
Merging!

**Pull request merged**
