### PR TITLE
[Gtk Pipeline Tool] Reference Editor Dialog

### PR DESCRIPTION
**Pull request by cra0zy**
Things done:
<ul>
<li>Added a new reference dialog that works similar to pre MonoDevelop 5.7 reference dialog.</li>
<li>Fixed YesNoCancel dialog question mark icon</li>
</ul>

refdialog

Do tell me if you want some different design for the ref dialog, but please leave the filechooser in there, it really speeds up reference selection.

### CODE REVIEW

**Comment by tomspilman** [comment]
> but please leave the filechooser in there, it really speeds up reference selection.

If you want to do that on Mac/Linux I guess that is ok.

But on Windows we should use the standard file chooser launched from an "Add Reference" button on the dialog.

**Comment by tomspilman** [comment]
Why is the title on this new dialog "Pipeline"?  Shouldn't the title be like "References" or "Add/Remove References" or "Reference Editor"?

**Comment by cra0zy** [comment]
> On Windows we should use the standard file chooser launched from an "Add Reference" button on the dialog.
> 
> If you want to do something different on Mac/Linux I guess that is ok.

Sounds good to me :D

> Why is the title on this new dialog "Pipeline"? Shouldn't the title be like "References" or "Add/Remove References" or "Reference Editor"?

You are right. The title of the dialog was null(default value when the title is not set), so it used application name as title. The reference dialog wasn't the only dialog that was missing a title so I fixed few other dialogs as well.

**Comment by cra0zy** [comment]
@tomspilman Can this get merged?

**Comment by tomspilman** [comment]
Merged!

**Comment by cra0zy** [comment]
Yey, Thanks

**Pull request merged**
