### PR TITLE
Updated improvements.md

### PR DESCRIPTION
**Pull request by Shqrdx**
Small update for help docs.

### CODE REVIEW

**Comment by Shqrdx** [comment]
@tomspilman Is it good for merging ?

**Comment by Shqrdx** [comment]
@tomspilman @KonajuGames Could this be merged ?

**Comment by tomspilman** [comment]
I'll merge this, but I think we should reconsider having it.  

First it is 99% the same information as what is in the reference docs for each method.  It is hard enough to have one good set of docs... we don't need copies of the same info.

Second it explains dumb things.  We don't need an explanation of how `Point.ToVector2()` works...  it is self explanatory.

Third as MonoGame adds more and more features beyond XNA this document becomes huge.  It would be better to find a way to mark non-XNA APIs automatically from the doc tool.

IMO... we should copy any useful information back into the reference docs and kill this page.

**Comment by Shqrdx** [comment]
Yeah, after your explanation me too think it is useless..

**Comment by danzel** [comment]
We could have a custom attribute on such methods that the doc generator could pick up?

**Comment by tomspilman** [comment]
> We could have a custom attribute on such methods that the doc generator could pick up?

That could be possible, but i'd prefer if whatever we did didn't add something at runtime to the type.

Maybe a custom element in the doc xml is possible?  Line `<not-xna-compatible/>` or something?

**Pull request merged**
