### PR TITLE
[Pipeline Tool] Use Wpf backend for Windows

### PR DESCRIPTION
**Pull request by cra0zy**
NEEDS: https://github.com/MonoGame/MonoGame.Dependencies/pull/86

Originally I was doing this for #4872 but turns out regardless of that issue, Wpf backend is better then the WinForms one. 

Advantages that I like:
 - color selection has alpha
 - treeview icons appear full color

Temporary multiselect won't work, this will be fixed with #4872 or native Wpf implementation.

Screenshot:
wpf

### CODE REVIEW

**Comment by KonajuGames** [comment]
https://github.com/MonoGame/MonoGame.Dependencies/pull/86 is merged.

**Comment by tomspilman** [comment]
I'm hesitant to all this...  but let me review the current state of the pipeline this week and i'll see about merging this.

**Comment by cra0zy** [comment]
> I'm hesitant to all this... but let me review the current state of the pipeline this week and i'll see about merging this.

This change is not really a big deal, I'm just swapping Eto.WinForms for Eto.Wpf dll for the most part.

**Comment by tomspilman** [comment]
> This change is not really a big deal

You change is not big...  but swapping WinForms for WPF is.  Totally different technologies, requirements, etc.

**Comment by cra0zy** [comment]
Just gonna mention that I will be doing a similar thing to Mac after this PR, that is I'll swap Gtk for Xamarin.Mac which looks (I would say "way more", but Gtk does not look native on Windows/Mac) native: https://files.gitter.im/mono/MonoGame/Ox4S/nativemactool.png

**Comment by cra0zy** [comment]
So... what's the status on this?

**Comment by tomspilman** [comment]
@cra0zy 

So tried the latest Pipeline Tool and things are ok for now.  We still need a lot of work on the property grid, but at least we're fully in control of it and it is cross platform.

Going to test the last build on this branch and see how WPF feels.

And this branch needs a rebase before we can merge.

**Comment by tomspilman** [comment]
A few little things I noticed on the WPF build...

 - The icons of disabled entries in the menus do not grey out.
 - The WPF build takes 2x the memory of the old WinForms build.
 - The References Editor issues I reported (https://github.com/mono/MonoGame/issues/4912) don't occur under WPF.
 - The bottom-right resize grip renders over the Cancel button in the References Editor.

Still none of this is a big issue.

I'm fine with switching over to WPF from WinForms.  If we happen to run into issues with it later we can always consider switching back.

@KonajuGames ?

**Comment by KonajuGames** [comment]
After regarding I'm good with merging this. There are some issues to be fixed, but we they don't so functionality and we can concentrate on those after merge.

**Comment by KonajuGames** [comment]
Rebasing, not regarding. The phone's swipe keyboard doesn't know that word yet.

**Comment by cra0zy** [comment]
Something is wrong with Mac build server.

**Comment by KonajuGames** [comment]
Yes. An upgrade to latest stable didn't go well. Broke Nant.

**Comment by tomspilman** [comment]
@dellis1972 should be around soon and should be able to direct me to the right fix to the Mac build machine.

**Comment by dellis1972** [comment]
@tomspilman ok I think I fixed NAnt. Hopefully I did it in a way we won't hit this again.

**Comment by cra0zy** [comment]
Rebased.

**Comment by tomspilman** [comment]
Thanks @cra0zy !

**Comment by hach-que** [comment]
This change broke building the Windows platform under Linux.  Is support for that something that was intentionally dropped?

On Linux I get:

```
Global.Windows.cs(13,28): error CS0234: The type or namespace name `Imaging' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
Global.Windows.cs(40,24): error CS0246: The type or namespace name `BitmapSource' could not be found. Are you missing an assembly reference?
```

**Comment by KonajuGames** [comment]
Building the Windows toolchain on Linux is not something we test. I think you might be the only person doing so. It wasn't an intentional break, but wouldn't be something that would be cause to revert the change.

**Comment by cra0zy** [comment]
Mono has a replacement for Windows Forms, but doesn't have a replacement for WPF.

**Comment by hach-que** [comment]
I don't use the output of the build, I just use it to make sure MonoGame builds successfully on all platforms.

It just means updating downstream projects to not attempt to build Windows on Linux.

**Pull request merged**
