### PR TITLE
fix OpenGL Texture2D.SetData()

### LINKED ISSUE #4606: Font Rendering is broken on iOS
On the latest development branch fonts are not rendering.

On a debug build of MG when the app loads it crashes with the following 

at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError () [0x0002a] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Graphics/GraphicsExtensions.cs:919 
  at Microsoft.Xna.Framework.Graphics.Texture2D+<PlatformSetData>c__AnonStorey1`1[T].<>m__0 () [0x00291] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs:192 
  at Microsoft.Xna.Framework.Threading.BlockOnUIThread (System.Action action) [0x0001e] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Threading.cs:177 
  at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T] (Int32 level, Int32 arraySlice, Nullable`1 rect, Microsoft.Xna.Framework.Graphics.T[] data, Int32 startIndex, Int32 elementCount) [0x00038] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs:126 
  at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T] (Int32 level, Int32 arraySlice, Nullable`1 rect, Microsoft.Xna.Framework.Graphics.T[] data, Int32 startIndex, Int32 elementCount) [0x00049] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Graphics/Texture2D.cs:142 
  at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T] (Int32 level, Nullable`1 rect, Microsoft.Xna.Framework.Graphics.T[] data, Int32 startIndex, Int32 elementCount) [0x0000a] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Graphics/Texture2D.cs:155 
  at Microsoft.Xna.Framework.Content.Texture2DReader.Read (Microsoft.Xna.Framework.Content.ContentReader reader, Microsoft.Xna.Framework.Graphics.Texture2D existingInstance) [0x0043e] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReaders/Texture2DReader.cs:169 
  at Microsoft.Xna.Framework.Content.ContentTypeReader`1[T].Read (Microsoft.Xna.Framework.Content.ContentReader input, System.Object existingInstance) [0x00013] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentTypeReader.cs:181 
  at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T] (Microsoft.Xna.Framework.Content.T existingInstance) [0x00041] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReader.cs:175 
  at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T] (Microsoft.Xna.Framework.Content.T existingInstance) [0x00003] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReader.cs:162 
  at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T] () [0x0000b] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReader.cs:150 
  at Microsoft.Xna.Framework.Content.SpriteFontReader.Read (Microsoft.Xna.Framework.Content.ContentReader input, Microsoft.Xna.Framework.Graphics.SpriteFont existingInstance) [0x0005c] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReaders/SpriteFontReader.cs:74 
  at Microsoft.Xna.Framework.Content.ContentTypeReader`1[T].Read (Microsoft.Xna.Framework.Content.ContentReader input, System.Object existingInstance) [0x00013] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentTypeReader.cs:181 
  at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T] (Microsoft.Xna.Framework.Content.T existingInstance) [0x00041] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReader.cs:175 
  at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T] (Microsoft.Xna.Framework.Content.T existingInstance) [0x00003] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReader.cs:162 
  at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T] () [0x0000b] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReader.cs:150 
  at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T] () [0x00008] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentReader.cs:72 
  at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T] (System.String assetName, System.Action`1 recordDisposableObject) [0x0009b] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentManager.cs:311 
  at Microsoft.Xna.Framework.Content.ContentManager.Load[T] (System.String assetName) [0x00077] in /Users/dean/Documents/Sandbox/dellis1972/MonoGame/MonoGame.Framework/Content/ContentManager.cs:226 
  at Monkey.Tap.Game1.LoadContent () [0x00053] in /Users/dean/Projects/ff/Monkey.Tap/Complete/Monkey.Tap/Game1.cs:80

### PR DESCRIPTION
**Pull request by nkast**
fix #4606

### CODE REVIEW

**Comment by nkast** [comment]
@tomspilman , @KonajuGames, 
Something wrong with the build server?

**Comment by dellis1972** [comment]
@tomspilman something weird happened

"System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\JSIL\source\Libraries'."

**Comment by tomspilman** [comment]
@hach-que - Any clue what this is?  Why would it suddenly come up today after builds running fine for 3 weeks on the new machine?

**Comment by hach-que** [comment]
This is an artifact of running an old version of Protobuild.  The build log indicates that it is indeed an older version of Protobuild running (this logic doesn't even exist at `develop`):

image

Checking the branch on @nkast's repository shows that this branch is significantly behind the latest develop:

image

Rebasing should fix the issue.

**Comment by hach-que** [comment]
You might want to have some sort of GitHub bot that checks new PRs as they're created / updated and verifies that the base of the branch is ahead of the commit that last changed Protobuild, which should reduce these "the branch is so out of date that things are obviously broken" issues.

**Comment by nkast** [comment]
@hach-que with a rebase I also have to force the changes to the remote, correct?
something like 
```
git rebase mono/develop
git push -f origin ContentReadersCache
``` 
This is the same branch from the merged #3518 so changing the history of the branch is not good, or so I heard. I just merged the latest commits, hope this will do. If not I'll re-submit from a new branch.

**Comment by tomspilman** [comment]
> which should reduce these "the branch is so out of date that things are obviously going to be broken" issues.

Yeah...  GitHub makes checking this inconvenient.  It does not link to the PR branch... you have to go thru a few clicks to find this out.

It would be nice if GitHub just showed the commits behind at the top of all PRs.

**Comment by dellis1972** [comment]
@nkast merging thanks.

**Pull request merged**
