### PR TITLE
Prevent finalizer exception on Linux systems without libgdiplus

### PR DESCRIPTION
**Pull request by hach-que**
On my Linux system, libgdiplus doesn't load correctly.  When the type initialization exception for libgdiplus occurs inside "new Icon" it leaves an Icon object lying around in memory which is inaccessible.  When the GC comes along and attempts to finalize it, it calls Dispose which tries to access libgdiplus again, which causes the type initializer exception to occur inside a finalizer, which in turn causes the runtime to terminate because as per the .NET documentation, exceptions in finalizers have no recovery.

This fixes the issue by calling a method on the internal GDIPlus class, and jumping out of that code block if the type initializer exception is thrown before we get a chance to new up an Icon.

### CODE REVIEW

**Comment by tomspilman** [comment]
I'll let @dellis1972 and @cra0zy comment on the fix for Linux.

I assume this updated Protobuild is the latest with the platform extension features you added correct?

**Comment by hach-que** [comment]
Ah whoops, I didn't meant to include Protobuild.  I think that's from a bad rebase.

**Comment by hach-que** [comment]
@tomspilman Can we get this merged sometime soon?

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy ?

Is this safe to do?  Should I try to get it into 3.5.1?

**Comment by hach-que** [comment]
It's probably not necessary for 3.5.1 (although it is a bugfix), but we should try to merge it for 3.6.

**Comment by cra0zy** [comment]
@hach-que 3.6 will replace OpenTK with SDL so it's either this get's merged in 3.5.1, or not at all.

**Comment by cra0zy** [comment]
@hach-que This code would have a bad result if someone is using mono + Windows, tho I doubt anyone is doing it....

**Comment by tomspilman** [comment]
> The code would have a bad result if someone is using mono + Windows

Yeah...  likely on one is doing that.

>  it's either this get's merged in 3.5.1, or not at all.

True... I will add it to 3.5.1 if @cra0zy can confirm it is safe and has no unexpected side effects.

**Comment by hach-que** [comment]
No-one should seriously be using Mono on Windows for production code anyway.

**Comment by cra0zy** [comment]
@tomspilman Other then mono + Windows, I see no other problems, I am ok with this getting merged.

**Pull request merged**
