### PR TITLE
Automated NuGet packaging

### PR DESCRIPTION
**Pull request by DDReaper**
Includes all the NuSpec definitions required for automated building.

* NuGet.exe added to Tools\NuGet folder.   
Should run NuGet -update prior to build to ensure it is the latest (verify TeamCity does this) 

* New NuGetPackages folder added
This contains all the NuSpec files and dependant files needed for packages

* Removed old MonoGame.NuGetpackager system as this is now superseded by the automated NuGet's

### CODE REVIEW

**Comment by cra0zy** [comment]
SDL_mixer.dll and SDL.dll should not be included for linux because they are meant windows. On linux Tao.Sdl.dll.config points to libSDL-1.2.so.0 and libSDL_mixer-1.2.so.0

**Comment by tomspilman** [comment]
> NuGet.exe added to Tools\NuGet folder.

 We don't need it.  TeamCity will automatically provide the latest NuGet.exe.


> New NuGetPackages folder added

So why "NuGetPackages" and not just "NuGet" as the folder?

**Comment by DDReaper** [comment]
Ok, @cra0zy thanks for the info. I shall update the Linux package.  However the Linux build currently outputs them?

OK @tomspilman , I'll remove the NuGet folder from Tools then.

As for NuGetpackages, I named it that because that's what they are?
Do you want it named something else or put anywhere else?

**Comment by tomspilman** [comment]
>  I'll remove the NuGet folder from Tools then.

Do you mind recreating the PR or maybe purging the commit of that EXE from your history.  I just don't want to have that EXE pulled in...  it just further bloats the repo.

**Comment by DDReaper** [comment]
OK, no worries.
Will pull the PR and resubmit as a new one.

**Pull request closed without merging**
