### PR TITLE
[Eto Dialogs] About Dialog

### PR DESCRIPTION
**Pull request by cra0zy**
This dialog was Windows only since Gtk has a built-in dialog, I thought a bit about it and decided to use the same dialog for all systems, easier maintenance.

Disregard the version, it get's updated by the build script.

Before left, after right:
untitled

### CODE REVIEW

**Comment by KonajuGames** [comment]
This one looks good, except I have noticed that the buttons in these Eto dialogs tend to be too close to the window borders.  The position of the OK button in the original About dialog uses the correct margins.

**Comment by cra0zy** [comment]
> This one looks good, except I have noticed that the buttons in these Eto dialogs tend to be too close to the window borders. The position of the OK button in the original About dialog uses the correct margins.

#4751 fixes it.

**Comment by cra0zy** [comment]
@KonajuGames Just FYI, I don't need to change anything in here for the Close button to gain spacing, the class that adds spacing is DialogBase and it's been modified in #4751 

What I am trying to say is this can be merged, the spacing was added to all the dialogs by merging ##4751

**Comment by KonajuGames** [comment]
Ok, cool. Merging.

**Pull request merged**
