### PR TITLE
Added mipmap generation for render targets (DirectX).

### PR DESCRIPTION
**Pull request by Helikin**
Mipmaps for render targets are created in GraphicsDevice.PlatformResolveRenderTargets (similar to the already functioning mipmap generation in the OpenGL code). 

I have added a unit test which is currently set to Ignore because:
In my tests generated mipmaps are different in XNA and MonoGame. The XNA mipmaps look wrong, as if created with point sampling!? MonoGame mipmaps look correct. 
Tested mipmaps in DirectX/OpenGL and Windows/MacOS are identical but only if the texture size is a power of two. 

Related issues:
- Rendertargets are lacking mipmapping functionality #1001

### CODE REVIEW

**Comment by Helikin** [comment]
There is one problem which I have observed:

If mipmaps are created for a cube map render target, then the mips of the last (6th) side of the cube map can contain uninitialized blocks. 

Here is a cube map visualized on a sphere. The problem are the magenta colored blocks.
image
These garbage blocks change randomly after each mip generation.

The problem was only observed with AMD GPUs (AMD R9 285, Win10). There are no problems on Intel and NVIDIA GPUs.

My first idea was that GenerateMips is called to early and some conditions have to be met before GenerateMips can be called. However, I have not found a solution yet. 

At the moment I guess this is an AMD driver problem (which would not be the first...)

**Comment by tomspilman** [comment]
> In my tests generated mipmaps are different in XNA and MonoGame. 

 I suggest then adding the MonoGame image as the comparison image and leaving the test on.  Then at least we'll get a report if the feature breaks for any reason.


> The XNA mipmaps look wrong, as if created with point sampling!?

Weird... must be a card/driver specific thing.


>  the mips of the last (6th) side of the cube map can contain uninitialized blocks. 

Cubemap mipmap generation has always been sort of buggy.

I suspect the only way to ensure mipmap generation is consistent across different hardware is to generate them yourself via a custom shader.  In fact i expect that both DX12 and Vulkan do not contain a "generate mipmaps" type function.

**Comment by tomspilman** [comment]
Let's try to get this merged for 3.6.

**Comment by tomspilman** [comment]
@Helikin - Can you rebase this for merging?

**Comment by Helikin** [comment]
Will do, later today.

**Comment by Helikin** [comment]
@tomspilman I have rebased and combined commits to 1 commit.

**Comment by tomspilman** [comment]
> I have rebased and combined commits to 1 commit. 

Note in the future you don't need to squash down to one commit...  

 https://github.com/blog/2141-squash-your-commits

So we can do that here from the PR merge button moving forward.

**Comment by tomspilman** [comment]
Merging... thanks @Helikin !

**Comment by Helikin** [comment]
> Note in the future you don't need to squash down to one commit...

Good to know. Thanks for merging!

**Pull request merged**
