### PR TITLE
Fix for small size spritefonts

### PR DESCRIPTION
**Pull request by Tzenchor**
Fixes issue #4305.
Changes:
Convert ImportGlyph method from static method to instance method.
Added method ExpandByte, to convert each bit in a byte to a byte.
Added processing code inside ImportGlyph to handle the case where
glyphs' bitmaps have only 1 bit per pixel

That ExpandByte method is inside SharpfontImporter just to keep it together with the rest of the changes. My opinion is to move it to MathHelper as an extension method, but i'm open to suggestions.

### CODE REVIEW

**Comment by KonajuGames** [comment]
Ideally, we would have a `BitmapContent`-derived class that supports 1bpp bitmaps.  Then we would construct a `OneBppBitmapContent` instead of `PixelBitmapContent<byte>` for these cases and everything would still work nicely as well as being able to support importing 1bpp bitmaps for textures (if anyone ever wanted to do that).

For now though, this looks ok.  `ExpandByte` is fine to stay where it is for now.  I don't think it belongs in MathHelpers at least.  There's only one change I would suggest.  Instead of `ExpandByte` allocating a new `byte[8]` each time it is called, allocate one `byte[8]` after the check for it being a mono bitmap and pass that same array in to `ExpandByte` so it can re-use the same array.  Generates far less garbage.  Going further it could expand directly into `gpixelAlphas` using `written` and `stride` as offset and length, avoiding the `byte[8]` completely, but that's probably more complex than it needs to be for no real benefit.

**Comment by Tzenchor** [comment]
Ok, i'll do the changes

**Comment by Tzenchor** [comment]
Done the changes, i have opted for the option of copying directly to the `gPixelAlphas` array. One thing i have done but left commented is doing the checks for input parameters of the new function `ExpandByteAndCopy`

**Comment by KonajuGames** [comment]
Code is either used or not used.  Unused code should be removed.  Commented code shouldn't be left in.  This is an internal method, and as such we can guarantee that we will pass correct values to it.  The exceptions will propagate back up to the user and have no meaning to them.

- Remove `ExpandByte()` as it is no longer used.
- Remove the commented parameter validation code.

Once that is done, I'm happy to merge this.

**Comment by Tzenchor** [comment]
Changes done.

**Comment by KonajuGames** [comment]
Thanks @Tzenchor. Merging.

**Comment by Oj18** [comment]
Is this code now in MonoGame itself?
I still have this issue

**Comment by Oj18** [comment]
Fixed it now, just had to disable anti-aliasing using custom spriteBatch.Begin()
Code:
spriteBatch.Begin(SpriteSortMode.Deferred,
      BlendState.AlphaBlend,
      SamplerState.PointClamp,
      null, null, null, null);

**Pull request merged**
