### PR TITLE
Added few missing PackedVectors and Tests for them.

### PR DESCRIPTION
**Pull request by cra0zy**
#3605 @flibitijibibo is the one who wrote PackedVector classes, I've only modified documentation and added tests for them.

### CODE REVIEW

**Comment by tomspilman** [comment]
Looks like you didn't add these to the Protobuild definition file...

https://github.com/mono/MonoGame/blob/develop/Build/Projects/MonoGame.Framework.definition

**Comment by tomspilman** [comment]
@cra0zy - Did you open and run the `MonoGame.Tests.XNA.csproj` project too and verify these tests succeed on MS XNA?

**Comment by cra0zy** [comment]
Funny thing is I only tried them in xna, the question was were they gonna run in monogame

**Comment by tomspilman** [comment]
Ok... i'll merge this now then.  Thanks @cra0zy and @flibitijibibo .

**Pull request merged**
