### PR TITLE
Replaced sdl1.2 with opentk for gamepad and joystick

### PR DESCRIPTION
**Pull request by cra0zy**
I replaced all the sdl 1.2 code with opentk equivalent for joystick and gamepad, tho there is no way to get joystick name using opentk AFAIK. This PR should probably get tested a bit before merging.

### CODE REVIEW

**Comment by tomspilman** [comment]
One more error on the Mac...

> /Applications/buildAgent/work/89a1ddadcff7bf98/MonoGame.Framework/Input/GamePad.OpenTK.cs(67,42): error CS0103: The name `num' does not exist in the current context

**Comment by tomspilman** [comment]
It seems https://github.com/mono/MonoGame/pull/3119 also has some OpenTK gamepad support in it.

@groundh0g & @cra0zy - Can you guys review each others gamepad code and merge efforts into this PR?

**Comment by cra0zy** [comment]
I went over #3119 and it only replaces gamepad, but leaves joystick and other classes untouched. His gamepad offers one thing my gamepad code doesn't, and it's "PlatformSetVibration" which I'll add in 5 mins.

**Comment by cra0zy** [comment]
Soo, for OpenTk.GamePad GetState and GetCompability aren't implemented, but the SetVibration doesn't throw any errors at least..

**Comment by cra0zy** [comment]
GamePad class in OpenTK is not implemented for linux

**Comment by tomspilman** [comment]
> GamePad class in OpenTK is not implemented for Linux

Really?  Well that sort of defeats the purpose of having a GamePad class in OpenTK.

@thefiddler has this been fixed?

**Comment by cra0zy** [comment]
@tomspilman I went threw the newest source code for opentk, that's why I know that the class is not implemented. Since I have time to spare, I'll fix opentk code.

**Comment by tomspilman** [comment]
> Since I have time to spare, I'll fix opentk code.

Anything you can contribute to OpenTK to improve it for Linux would be a huge win for MonoGame.  Go for it!

**Comment by cra0zy** [comment]
Good news, there is a MappedGamePadDriver.cs class that's used under Windows, but can be used under linux and mac as well, it's just not connected...

**Pull request closed without merging**
