### PR TITLE
OpenAssetImporter now also imports node animations (not only skeleton)

### PR DESCRIPTION
**Pull request by SeriousMartin**
includes a simple unit test

### CODE REVIEW

**Comment by tomspilman** [comment]
@nkast  @mgarstenauer - What do you guys think of this change?

**Comment by mgarstenauer** [comment]
I wanted to add support for node animations, but never got around to.
PR looks good. (Though, a code comment wouldn't hurt. ;)

I recommend merging the changes. Thx @SeriousMartin.

**Comment by nkast** [comment]
I am not familiar with Node animations.
I trust @mgarstenauer opinion on this one.

**Comment by tomspilman** [comment]
Thanks guys... merging!

**Pull request merged**
