### PR TITLE
Generating tangent frames

### PR DESCRIPTION
**Pull request by Vodacek**
Added support for generating tangent frames for models.

### CODE REVIEW

**Comment by Vodacek** [comment]
@tomspilman , @KonajuGames any comment?

**Comment by tomspilman** [comment]
@mgarstenauer  - This make sense to you?

**Comment by mgarstenauer** [comment]
I suggest the following changes inside the `if (GenerateTangentFrames) { ... }`:
- The method `MeshHelper.CalculateTangentFrames` fails (throws exception) if a `GeometryContent` is missing normal vectors. Therefore, first check whether all `GeometryContent` in `mesh.Geometry` contain `VertexChannelNames.Normal()`. If not, then call `MeshHelper.CalculateNormals` first.
- The mesh may already contain valid tangents and binormals. Calling `MeshHelper.CalculateTangentFrames` in this case overwrites the existing tangent frames, which needs to be avoided. Therefore, check whether all `GeometryContent` in `mesh.Geometry` already contain a tangent or binormal channels and only call `MeshHelper.CalculateTangentFrames` if one is missing.

**Comment by tomspilman** [comment]
Thanks @mgarstenauer ... totally agree and it is obvious now this needs some fixes before we can merge.

**Comment by Vodacek** [comment]
@tomspilman done :-)

**Comment by mgarstenauer** [comment]
Looks good to me!

**Comment by Vodacek** [comment]
Thanks :-) Perhaps now Build bot will be also satisfied.

**Comment by tomspilman** [comment]
Thanks guys!

**Pull request merged**
