### PR TITLE
Window.Position for WindowsGL(and Linux?) platform

### PR DESCRIPTION
**Pull request by Shqrdx**
This property is not implemented so some users are suffer from this - https://github.com/mono/MonoGame/issues/3512

### CODE REVIEW

**Comment by tomspilman** [comment]
Seems reasonable...  @cra0zy ?

**Comment by Shqrdx** [comment]
@tomspilman Could you restart a bot. Latest fix made it correct but bot marks it invalid without checking.

**Comment by Shqrdx** [comment]
Ok, looks like Mac have something against System.Drawing... so I remade it for windows and linux only.

**Comment by cra0zy** [comment]
Now it looks good, also works on Linux

**Comment by cra0zy** [comment]
WINRT!!!

**Comment by Shqrdx** [comment]
@tomspilman I have no idea how to fix it... everything seems correct... your turn to play.

**Comment by danzel** [comment]
http://teamcity.monogame.net/viewLog.html?buildId=5296&buildTypeId=MonoGame_DevelopWin&tab=buildLog#_state=1220&focus=1237

Framework\MockWindow.cs(11,20): error CS0534: 'MonoGame.Tests.Framework.MockWindow' does not implement inherited abstract member 'Microsoft.Xna.Framework.GameWindow.Position.get' [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Test\MonoGame.Tests.WindowsGL.csproj]

**Comment by tomspilman** [comment]
@Shqrdx - You have to implement the `Position` getter in the class `Tests\Framework\MockWindow.cs`.  It doesn't need to do anything really...  but it needs to be defined.

**Comment by Shqrdx** [comment]
Oh, i was tired and didnt see this to logs. Sorry.

**Comment by Shqrdx** [comment]
@tomspilman Now, please merge ?

**Comment by tomspilman** [comment]
> didnt see this in logs. Sorry.

No problem...  it happens.  The logs are hard to read which I hope to fix soon.

**Pull request merged**
