### PR TITLE
Testing Texture2D.SetData

### PR DESCRIPTION
**Pull request by Tzenchor**
Related to #1455.
At this time I have implemented some tests for `Texture2D.SetData()` with 1 and 3 parameters, the other overloads will come later. If someone reads the code, the testCases are grouped from bottom to top as follows: XNA and Monogame passed tests, only Monogame passed tests, and failing tests.

Things pending:

- Add tests for the remaining `SetData` overloads.
- Separate the TestCases if they should pass or fail
- Fix issues found in the Monogame implementation

### CODE REVIEW

**Comment by Tzenchor** [comment]
This latest push fixes the possible writing of wrong data to the texture, but it is breaking 4 Texture2D visual tests which i'll have to review to understand them.

The fix I did allow to use longer arrays than the texture but will not write beyond the texture data. Also note that while there is some validation of the parameter `elementCount`, it has no effect on the actual writing of the data to the texture, at least on windows

**Comment by Tzenchor** [comment]
I forgot to add in the previous message the comparison of the test cases between XNA and Monogame.
[Tests setdata.xlsx](https://github.com/mono/MonoGame/files/283961/Tests.setdata.xlsx)
Column "A" contains the tests cases in XNA with its own order, column "F" tells if the test was a success or a failure, Column "H" the tests cases in Monogame, column "L" its results, and column "M" the corresponding XNA result.

**Comment by Tzenchor** [comment]
Found the problem, it occurs in the test that are accessing or texture sublevels or when accesing to values of a texture array

**Comment by Tzenchor** [comment]
Done if I have missed something.
Two assumptions I had to make:
- Each sublevel of a texture has half the size than the upper level. I have made this calculation directly inside `Texture2D.setData` where the parameters get validated but it may be useful to move it to a function.
- Each Texture in a Texture array have the same size as the first texture

**Comment by KonajuGames** [comment]
These look good to me.  Thanks @Tzenchor.  Merging.

**Comment by nkast** [comment]
@Tzenchor 
https://github.com/Tzenchor/MonoGame/blob/e4358c240d7654695232dedf01bf176cdc46fe10/MonoGame.Framework/Graphics/Texture2D.cs#L141-L144
IMO we shouldn't check the `data.Length`. What matters is the elementCount. MG for example uses a sratchbuffer to load textures, user might do the same. 

Also the line `data.Length - startIndex < resizedBounds.Width * resizedBounds.Height` doesn't account for surface format and typeof(T). You need to convert everything into bytes, something like '(elementCount - startIndex)*sizeof(T) < (resizedBounds.Width * resizedBounds.Height)*GetBytesPerPixel(surfaceFormat)'   If you have a Color texture and load from a byte array the actual data would be Width * Height * 4.

The reason most textures pass the test now is because MG uses a scratch buffer of 1M.

**Comment by Tzenchor** [comment]
True, didn't thought about that.

@Jjagg was doing changes to this and more in a recent pull request #5121. Maybe he is aware of the issue and he can solve it inside

**Comment by Jjagg** [comment]
Yeah, that's done right in my PR. I don't know how XNA handles Get/SetData for compressed texture formats. That's what still needs to happen in that PR

**Pull request merged**
