### PR TITLE
Change Shared Program.cs back to using a static to fix an issue in iOS.

### PR DESCRIPTION
**Pull request by dellis1972**
For MonoGame 3.6 we should revisit this kind of code to have platform
specific source files rather than this mess of #if statements. Generally
speaking developers do not share startup code.

### CODE REVIEW

**Comment by dellis1972** [comment]
@cra0zy I just reverted this stuff for now. I think we should revisit this after we manage to get 3.5 out of the door. Perhaps as part of the template re-write.

**Comment by cra0zy** [comment]
> @cra0zy I just reverted this stuff for now. I think we should revisit this after we manage to get 3.5 out of the door. Perhaps as part of the template re-write.

Again, you need to dispose of the game on Desktop platforms, add a preprocessor param for it.

And we won't have to talk about Program.cs because Protobuild.Manager should sort it out for us.

**Comment by tomspilman** [comment]
> And we won't have to talk about Program.cs because Protobuild.Manager should sort it out for us.

The generated template source code should always support all our platforms.  I don't want to see Protobuild.Manager copying over different source files for different platforms.

**Comment by cra0zy** [comment]
> The generated template source code should always support all our platforms. I don't want to see Protobuild.Manager copying over different source files for different platforms.

The Game.cs should be the same, but I don't think Program.cs is that important...

**Comment by tomspilman** [comment]
> but I don't think Program.cs is that important to be the same

I'd rather have it all the same if possible... and I think we could make it possible.

**Comment by KonajuGames** [comment]
Merging.

**Pull request merged**
