### PR TITLE
Mini Guide on Howto use TrueType fonts

### PR DESCRIPTION
**Pull request by FunkySanchez**
Need a general review and some pointers on the following:

1- Link at the bottom of the file should go to the API Reference
2- Github Markdown editor shows weird stuff on the images, I could not find the issue. 
3-  I may speak out of context or in a weird way, English is not my native tongue.

Hope the rest is right, thank you for the project. 
I hope I can keep on adding stuff, The project is screaming for documentation.

### CODE REVIEW

**Comment by tomspilman** [comment]
Thanks @FunkySanchez .

You can see your changes here:

http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/9531:id/Documentation.zip%21/index.html?guest=1

If you add your new page here:

https://github.com/mono/MonoGame/blob/develop/Documentation/config.xml#L34

It will then show up in the table of content as well.

**Comment by KonajuGames** [comment]
@FunkySanchez, could you add the change suggested by @tomspilman, re. config.xml?

**Comment by FunkySanchez** [comment]
@KonajuGames Added the line, should be good to go.

**Comment by KonajuGames** [comment]
I'm not sure what problem Protobuild is having.  The build failure has nothing to do with this change.  I'm going to merge this because your changes are good.

**Pull request merged**
