### PR TITLE
Moved IDE/MonoDevelop to ProjectTemplates/MonoDevelop

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by tomspilman** [comment]
@dellis1972 - This make sense to you?

**Comment by dellis1972** [comment]
@tomspilman hmmm not sure.. The ProjectTemplates contains only project templates, this stuff is an IDE extension it does more that templates. There is the Pipeline integration, and with the new MSBuild PR for Mac OS (https://github.com/mono/MonoGame/pull/3953) there is additional project processing. 

If we ever do a VS extension I would imagine it would go in IDE/VisualStudio/  ....

**Comment by cra0zy** [comment]
I feel that VS and MonoDevelop templates/extensions should be within the same folder, maybe choosing some better name for folder than ProjectTemplates?

@dellis1972 Side note for md adding, the project templates group should probably be changed from "Miscellaneous > General" to ".NET > MonoGame"

**Comment by dellis1972** [comment]
@cra0zy the reason they are under Miscellaneous->General is because of recent changes to MonoDevelop they reworked the entire template system, so the old _Category elements are invalid and the Misc->General is a catch all. PR 3953 should fix some of that.. but things are a bit fluid atm from what I can tell and things keep moving around.

on a side note, I'd rather get PR 3953 merged before we start moving stuff around if possible otherwise its going to cause a lot of conflicts my end which I'll need to pick though.

**Comment by cra0zy** [comment]
> on a side note, I'd rather get PR 3953 merged before we start moving stuff around if possible otherwise its going to cause a lot of conflicts my end which I'll need to pick though.

ok, I'll close this until than... I'll also think of a better name for the folder in the meantime

**Comment by KonajuGames** [comment]
@dellis1972 We need a MD extension that uses VS templates.  That would be ideal. :)

**Comment by dellis1972** [comment]
@KonajuGames I have a plan on that. not sure if it will work though.. need to figure it out a bit more

**Comment by cra0zy** [comment]
@KonajuGames I was thinking about that with #3954, it was influenced a bit by how libgdx creates projects...

**Pull request closed without merging**
