### PR TITLE
Quaternion docs, fixes and test

### PR DESCRIPTION
**Pull request by Shqrdx**
Rewrited version of https://github.com/mono/MonoGame/pull/3993 without changes to other tests.

### CODE REVIEW

**Comment by Shqrdx** [comment]
@tomspilman ? is this ok ? it is exact copy of all your correction from old PR.

**Comment by Shqrdx** [comment]
@tomspilman ?

**Comment by tomspilman** [comment]
Still a lot of docs I have issues with in there, but we'll revisit that later.

**Comment by Shqrdx** [comment]
Thank you !

**Pull request merged**
