### PR TITLE
SDL Controller DB update

### PR DESCRIPTION
**Pull request by mrhelmut**
This is an update to the SDL controllers database to support more gamepads. Changes come from upstream (https://github.com/gabomdq/SDL_GameControllerDB).

### CODE REVIEW

**Comment by tomspilman** [comment]
Before we update this should we investigate the Steam SDL database too?

@cra0zy - Do you have a link to that?

**Comment by cra0zy** [comment]
> Before we update this should we investigate the Steam SDL database too?

We cannot use that, it's not a static database, it contains the SDL general database (which we have a copy of), and it contains any controller the user configures within Steam Big Picture Mode.

Any SDL game launched through Steam should get autohooked to this database.

**Comment by mrhelmut** [comment]
I confirm, it's a subset of the database, plus any mapping found locally in the Steam install folder (config/config.vdf). Steam autohooks, it's basically how the Steam Controller works.

I'll try to add documentation about this in #4430 (which I'll have time to continue after getting around the few ongoing gamepad works).

**Comment by tomspilman** [comment]
Ah... I see.  As long as MonoGame supports it then we're good.

**Pull request merged**
