### PR TITLE
Correct fix for MediaFactory.GetService failure

### PR DESCRIPTION
**Pull request by MichaelDePiazzi**
This should be the correct fix for the MediaFactory.GetService failure and related volume problems* in the Windows DirectX build (See PR #3255 / Issue #2620). This PR may possibly also resolve issue #1954.

(* I was having a problem where after the first song was played, volume changes were not taking effect until the next song was started)

The problem is that GetService cannot be called until the session topology is ready. According to the SharpDX documentation (http://sharpdx.org/documentation/api/m-sharpdx-mediafoundation-mediasession-settopology), when the session is currently paused or stopped, the MediaSession.SetTopology method doesn't even take effect until the next call to Start. And because the method is asynchronous, you need to wait until you receive a "SessionTopologySet" event anyway to know that it's completed.

So I've changed the code to listen for this event. I've tested this on Windows 7 64-bit and it seems to work as expected now (i.e. no crashes on GetService, and volume changes take effect immediately).

PS. A similar fix will also likely be required for VideoPlayer.WMS as it uses the same methods, but I wanted to focus on MediaPlayer first as this is what I was having issues with and could test.

### CODE REVIEW

**Comment by tomspilman** [comment]
This is great @MichaelDePiazzi !  Love that someone has finally figure this out correctly!

Can someone give this a test with their own project first?

**Comment by MichaelDePiazzi** [comment]
@tomspilman No worries. Glad I can contribute in some way!

**Comment by mrhelmut** [comment]
I confirm that it works and that it is as clean as possible. Thanks for nailing that one @MichaelDePiazzi 

If it got merged, I'll update VideoPlayer.WMS accordingly and get rid of MediaPlayer.GetVolumeObj().

**Comment by tomspilman** [comment]
Thanks @mrhelmut ...  I'm merging it now!

**Pull request merged**
