### PR TITLE
[Eto Forms] Partial Main Window

### PR DESCRIPTION
**Pull request by cra0zy**
Moved some common stuff to Controller, and moved some MainWIndow common stuff to a partial MainWindow

PS. Next PR will fix Dialog positioning.

### CODE REVIEW

**Comment by tomspilman** [comment]
Great... going to merge this.

After we get done with the Eto refactor we really need to get to https://github.com/mono/MonoGame/issues/4558.

**Comment by cra0zy** [comment]
I wanted to chop up the replacement of MainWindow into smaller pieces, but it seems that I am gonna have to do it in one swoop.

Sorry about the next PR, it will be a bit bigger.

**Comment by tomspilman** [comment]
Yeah... I could see how that would be hard to break up.  Do what you can.

**Comment by cra0zy** [comment]
May I use Eto.Wpf instead of Eto.WinForms? Pipeline Tool looks much nicer IMO...

**Comment by tomspilman** [comment]
> May I use Eto.Wpf instead of Eto.WinForms? Pipeline Tool looks much nicer IMO...

Maybe... I would want to see how it looks and test it on some older OSs and lower end systems.

**Comment by cra0zy** [comment]
> I would want to see how it looks and test it on some older OSs and lower end systems.

I haven't really applied anything special to it so for now it looks ordinary:
untitled
untitled2
There are few kinks I need to workout, but nothing too major.

But here is the fun thing about it, we should be able to apply something like VS style, or Metro style... I got the idea from Gemini (https://github.com/tgjones/gemini).

**Comment by tomspilman** [comment]
> I haven't really applied anything special to it so for now it looks ordinary:

Ordinary is fine...  we want it to look like any other application on Windows.

What bothers me is the incorrect elements in that image:

  - The non-working property grid.
  - No sizing border on the window.
  - Tree view missing lines.
  - The unnecessary black sizer grip on the top of both windows.
  - The overlapping corner sizer grip with the cancel button.

Is this because of bugs in Eto or this is all stuff Eto doesn't handle?

> we should be able to apply something like VS style, or Metro style

 I would be hesitant to do that by default... it serves no functional purpose.

**Comment by cra0zy** [comment]
> Is this because of bugs in Eto or this is all stuff Eto doesn't handle?

> The non-working property grid.

I didn't implement it yet, I'll reuse the code from the Gtk one. I also didn't set border style for any controls in the main window so they have black outline. 

> No sizing border on the window.

The window is resizable from any border, it is the same border as the current WinForms Pipeline...

> Tree view missing lines.

Visual Studio is using the same component, and doesn't have any treeview lines either so that's not really a complaint... that's normal.

PS. I am using TreeGridView instead of TreeView, reason is selection rectangle.

> The unnecessary black sizer grip on the top of both windows.

Not a sizer grip, it's something VS adds for debugging to WPF windows while in debug mode.

> The overlapping corner sizer grip with the cancel button.

That is a bug in Eto, I submitted a bug report (https://github.com/picoe/Eto/issues/491), tho it's easily fixable by adding a style.

Haha, when I look at it only the last thing was an actual complaint...

**Comment by tomspilman** [comment]
> I didn't implement it yet, I'll reuse the code from the Gtk one.

That is going to be my ultimate issue with it...  things like the property grid where we can't use the ones that exist for WinForms or WPF... we have to build our own "custom" one.

I'm already disliking this approach.

> The window is resizable from any border,

Resizable borders in Windows have a thick edge:

border

Sometimes it includes the corner gripper... usually depends on if the window has a status bar or is a dialog or not.

> Visual Studio is using the same component, and doesn't have any treeview lines either so that's not really a complaint

As long as this is an actual native Windows tree view and not something created to mimic it we could live with that.

> it's something VS adds for debugging to WPF windows while in debug mode

Weird... It didn't do that last I used WPF 4 years ago.

**Comment by cra0zy** [comment]
> That is going to be my ultimate issue with it... things like the property grid where we can't use the ones that exist for WinForms or WPF... we have to build our own "custom" one.
> 
> I'm already disliking this approach.

Windows Forms is the only GUI that offers Property Grid out of the box.

WPF, Gtk Qt, Cocoa, UWP/Metro all don't have a property grid out of the box and need a manual implementation.

> Resizable borders in Windows have a thick edge:
> 
> 
> 
> Sometimes it includes the corner gripper... usually depends on if the window has a status bar or is a dialog or not.
> 
> Visual Studio i

This is how 3.5 Pipeline Tool looks for me:

untitled

Completely the same border :|

Also the border color comes from the system theme.

**Comment by Tzenchor** [comment]
> Resizable borders in Windows have a thick edge

That is the normal border in Windows 10, at least for me

**Comment by tomspilman** [comment]
> Windows Forms is the only GUI that offers Property Grid out of the box.

 You're right... I forgot about that issue in WPF.  There are various replacements that mimic WinForms/VisualStudio style property grids.

We should specifically aim to mimic that as well then.

> This is how 3.5 Pipeline Tool looks for me:

That may be a Windows 10 thing then.  As long as it renders correctly on non-Windows 10 systems then we're doing it right.

> Also the border color comes from the system theme.

Of course...  I've been writing Windows GUIs since 1994.  I fully understand how it works.

**Comment by cra0zy** [comment]
I figured out the border thing, maybe... I didn't really let my system update that much (I am mostly on Linux) so I still haven't gotten to installing the November update.

**Comment by Tzenchor** [comment]
> I figured out the border thing, maybe... I didn't really let my system update that much (I am mostly on Linux) so I still haven't gotten to installing the November update.

For me the border thing didn't change since release, the november update only affected the title bar, as now it shows the system color instead of being white like in your screenshots.

And for your information, look for "Snipping Tool" while using Windows, it's a great help when taking screenshots

**Comment by tomspilman** [comment]
> look for "Snipping Tool" while using Windows

Yep... snipping tool is great!  I just wish I could drag and drop the image right to GitHub without needing to save it first.

**Comment by cra0zy** [comment]
> And for your information, look for "Snipping Tool" while using Windows, it's a great help when taking screenshots

Ha, interesting, didn't know it was there, thanks for mentioning it. On Linux with GNOME there is a tool that does the same called "Screenshot".

One interesting difference between Windows and Linux is that print screen on Linux automatically saves the image.

**Comment by Tzenchor** [comment]
> One interesting difference between Windows and Linux is that print screen on Linux automatically saves the image.

Not anymore, `Windows + Print Screen`, or `Windows + Volume Down` on tablets, to take the whole desktop and it is saved to `Pictures\Screenshoots`.

**Comment by KonajuGames** [comment]
A good guide to button positioning is that the resizing handle in the bottom right corner shouldn't overlap the button (see the New File dialog in your screenshot, even though that dialog doesn't need to be resizeable).

**Comment by cra0zy** [comment]
> A good guide to button positioning is that the resizing handle in the bottom right corner shouldn't overlap the button (see the New File dialog in your screenshot, even though that dialog doesn't need to be resizeable).

As I said above, resize handle is a bug in Eto, it shouldn't be visible at all.

**Comment by cra0zy** [comment]
Some progress report on Eto Forms Main WIndow:
 - Window, Menubar, Toolbar, ContextMenu, HPanned/VPanned have been fully setup and are fully using Eto.Forms
 - ProjectView, PropertiesView and FilterView are wrappers around native controls and I am working on this part right now
 - Windows version is sticking with WinForms so I can reuse the code from the existing Pipeline Tool for the  controls above

**Comment by cra0zy** [comment]
UPDATE NO. 2
 - I skipped over the normal treeview control, but it's done much better than the treegridview, so I got ProjectView and FilterView in Eto.Forms now
  - multiselect is gonna be a pain to do for Windows :(
 - currently looking at a way to render a custom properties view

**Comment by cra0zy** [comment]
New porperty grid fully written in Eto is looking good: https://youtu.be/nZeqn9Km9eI

**Pull request merged**
