### PR TITLE
Type converters for vectors

### PR DESCRIPTION
**Pull request by nkast**
-fix https://github.com/mono/MonoGame/issues/3484
-add conversion to Vector2/3/4. [Windows] only.
-Use ';' as a seperator. Identical to XNA and fix parsing problems with floats.

### CODE REVIEW

**Comment by tomspilman** [comment]
Could we easily add some unit tests for these changes?

**Comment by tomspilman** [comment]
Failed on the windows build...

```
[18:51:58]  c:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\Vector2.cs(15,73): error CS0234: The type or namespace name 'Design' does not exist in the namespace 'Microsoft.Xna.Framework' (are you missing an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj]

[18:51:58]  c:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\Vector3.cs(13,73): error CS0234: The type or namespace name 'Design' does not exist in the namespace 'Microsoft.Xna.Framework' (are you missing an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj]

[18:51:58]  c:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\Vector4.cs(13,73): error CS0234: The type or namespace name 'Design' does not exist in the namespace 'Microsoft.Xna.Framework' (are you missing an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\Tools\2MGFX\2MGFX.Windows.csproj]
```

**Comment by nkast** [comment]
Should I add a separate TypeConvertersTest just for this or place the tests to Vector2Test and add the missing Vector3Test/Vector3Test?
I think the problem is with 2MGFX that links a few classes from MonoGame, I will check it out.

**Comment by tomspilman** [comment]
> Should I add a separate TypeConvertersTest just for this or place the tests to Vector2Test and add the missing Vector3Test/Vector4Test?

Seems like either would work...  your call.

**Comment by flibitijibibo** [comment]
For what it's worth, these checks should be okay on `LINUX || MACOS` as well; we ship with these converters without any fuss:

https://github.com/flibitijibibo/FNA/blob/master/src/Vector2.cs#L29
https://github.com/flibitijibibo/FNA/blob/master/src/Vector3.cs#L26
https://github.com/flibitijibibo/FNA/blob/master/src/Vector4.cs#L26

Not sure about the others though.

**Comment by nkast** [comment]
@flibitijibibo I can't check those changes on other platforms.
Well, I can check on WP/Win8.1 but those platforms don't need TypeConverters, only Windows =  WinForms/WPF.

**Comment by KonajuGames** [comment]
Need to add the converter source files to the WindowsGL project.

**Comment by nkast** [comment]
@KonajuGames Ok, thanks!

**Comment by nkast** [comment]
-use `CultureInfo.TextInfo.ListSeparator` as a separator.
-use culture for `float.Parse(...)`
-use Round-trip formatter for `float.ToString(...)`. (pass the "... 8192,0625" test)
-add the converter source files to the WindowsGL project 
-plus tests

**Comment by KonajuGames** [comment]
Those look like good tests, taking the cultures into account.

**Comment by nkast** [comment]
@KonajuGames I run into issues with the tests early on because I have el-gr culture on my computer.
The converter want a culture anyway otherwise it fails, so I had to instantiate cultures anyway.

**Comment by tomspilman** [comment]
This looks good to me... merging!

**Pull request merged**
