### PR TITLE
[Gtk Pipeline] Toolbar

### PR DESCRIPTION
**Pull request by cra0zy**
All icons were created by me... that explains the suckiness...

toolbar

### CODE REVIEW

**Comment by tomspilman** [comment]
Looks great @cra0zy.  Your icons totally work for now... we can always have someone else come by later and make improvements to them.

We'll have to see if anyone has time to go do the same for the Windows platform.

**Comment by cra0zy** [comment]
> We'll have to see if anyone has time to go do the same for the Windows platform.

I can do it for Windows, I just need #4272 merged before setting it up(filter output toggle).

**Comment by nkast** [comment]
| I can do it for Windows as well, I just need #4272 merged before setting it up(filter output toggle).

I rebase #4272 and clean up the code.

**Comment by KonajuGames** [comment]
#4272 has been merged.

**Comment by cra0zy** [comment]
Can this be merged before adding Toolbar to WinPipeline?

2 Reasons: 
1) I have to work from Windows on this and this PR has been modified by Linux, if I make a mistake I may have to reboot between systems
2) I want to add the settings saving (#4321) as well and it might create a bit of mess in this PR.

**Comment by tomspilman** [comment]
> Can this be merged before adding Toolbar to WinPipeline?

Sure...   is it ready to go?

**Comment by KonajuGames** [comment]
#4321 was merged a couple of days ago.  I'm not sure what you mean by wanting to add it.

**Comment by cra0zy** [comment]
> Sure... is it ready to go?

I have the code ready for settings, I don't have the code ready for Toolbar(since it depends on this), and I can get everything ready today.

Also I am not home right now.

> #4321 was merged a couple of days ago. I'm not sure what you mean by wanting to add it.

It's only for Gtk, still need to add saving settings on Windows.

**Comment by KonajuGames** [comment]
I'll merge this one.

**Pull request merged**
