### PR TITLE
Windows Phone 8.0 MSI update for .winmd file

### PR DESCRIPTION
**Pull request by DDReaper**
Updated the Installer MSI to include the .winMd (WINRT Component) file for Windows Phone 8.0

### CODE REVIEW

**Comment by tomspilman** [comment]
Ah...  this makes sense.

Do we not need this for WP8.1?

**Comment by DDReaper** [comment]
No, for WinPhone 8.1, SharpDX doesn't use a .winmd (WINRT) component.

Tested the new installer and the WinPhone 8.0 project work fine now @tomspilman 

on to the next challenge :dancer:

**Comment by Nezz** [comment]
No wonder everybody was complaining :)

**Comment by DDReaper** [comment]
Oohhhh @nezz that cuts deep 😎

**Pull request merged**
