### PR TITLE
[SpriteBatcher] Optimization of indices initialization

### PR DESCRIPTION
**Pull request by nkast**
Initialize 8192 indices. 
Release build.
StopWatch wrapping the `for` loop at https://github.com/nkast/MonoGame/blob/0013f2f184cde5b6c41b788fc663e463f6711c80/MonoGame.Framework/Graphics/SpriteBatcher.cs#L148-L168

     | x86 | x64
--- | ---- | ---
*Original* (ms): | 0.1012 | 0.0606
*this PR* (ms): | 0.0503 | 0.042
Diff (%)  | 49.7% | 69.3%

### CODE REVIEW

**Comment by nkast** [comment]
Don't merge this, there is a bug when growing the array. I must add a visual test first.

**Comment by tomspilman** [comment]
@nkast - Is this good to merge now?

**Comment by nkast** [comment]
@tomspilman
Yes, it's ok now.

**Comment by tomspilman** [comment]
Thanks @nkast ... merging!

**Pull request merged**
