### PR TITLE
Fixed DesktopGL on MacOS

### PR DESCRIPTION
**Pull request by dellis1972**
Fullscreen Toggling was not working on DesktopGL at all. 
StorageDevice on DesktopGL was not working on MacOS.

Both tested on MacOS :)

### CODE REVIEW

**Comment by dellis1972** [comment]
@mrhelmut any chance you can test this one?

**Comment by mrhelmut** [comment]
I don't have a working example to test ```StorageDevice``` but everything is fine with fullscreen toggling. :+1:

**Comment by dellis1972** [comment]
@mrhelmut thanks :) Its nice to have another MacOS person after all this time :D

**Comment by dellis1972** [comment]
@tomspilman @KonajuGames this is good to go

**Comment by tomspilman** [comment]
Thanks @dellis1972 and @mrhelmut !

**Pull request merged**
