### PR TITLE
Content Reader/Writter fixes

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by tomspilman** [comment]
So first question.  Will content built prior to the changes for DesktopGL still load correctly?

**Comment by cra0zy** [comment]
> So first question. Will content built prior to the changes for DesktopGL still load correctly?

Now they will still be loadable.

**Comment by tomspilman** [comment]
Thanks... merging!

**Comment by cra0zy** [comment]
> This has to be 'g', no?

Yes, you are right.

**Pull request merged**
