### PR TITLE
[Pipeline Tool] Fix watcher class CPU usage

### LINKED ISSUE #4548: Pipeline tool has high CPU usage while idle
Yesterday, while testing the pull #4545 I found that the pipeline was using nearly a 20% of my 4 cores CPU.
The problem is coming from the changes in #4525.

### PR DESCRIPTION
**Pull request by cra0zy**
Fixes #4548

### CODE REVIEW

**Comment by Tzenchor** [comment]
Just tried with the artifacts from the server and it works
It's incredible that by waiting before the check instead of after makes CPU usage drop to 0%

**Comment by cra0zy** [comment]
> Just tried with the artifacts from the server and it works
> It's incredible that by waiting before the check instead of after makes CPU usage drop to 0%

That is because I was dumb and replaced an if with continue https://github.com/cra0zy/MonoGame/blob/pipthread/Tools/Pipeline/Common/PipelineController.FileWatcher.cs#L57, but forgot to move the Thread.Sleep after.

**Comment by Tzenchor** [comment]
I think I were dumber to not see that continue until now

**Comment by KonajuGames** [comment]
Merging. Thanks @cra0zy

**Pull request merged**
