### PR TITLE
Dont use SDL with OpenTK on Windows

### PR DESCRIPTION
**Pull request by cra0zy**
This will affect DesktopGL Windows & Mac

@mrhelmut @dellis1972 Can you test this?

### CODE REVIEW

**Comment by mrhelmut** [comment]
I'll try it.
@endimilojkoski will most probably have feedback.

**Comment by mrhelmut** [comment]
I have tested. It doesn't work on OS X. Gamepads are not recognized.

**Comment by cra0zy** [comment]
@mrhelmut ok, so I set it Windows only

**Comment by dellis1972** [comment]
I don't think we should do that.. 
At the moment the end user has the option of using SDL as a backend through OpenTK which is required to use DesktopGL on Mac (in my tests anyway) because the code to create a native Cocos window fails. 
So I think we should left OpenTK do what it does and IF the sdl2 dll is present let it use it.

**Comment by dellis1972** [comment]
When I said DekstopGL on Mac I meant with MonoKickstarter rather than Mono normal

**Comment by dellis1972** [comment]
@cra0zy what is the reasoning for doing this?

**Comment by cra0zy** [comment]
#4252

Also look at the comment above, I set it Windows only.

**Comment by mrhelmut** [comment]
@dellis1972 OpenTK gamepad mapping is wrong with SDL (Windows) because it returns different GUID than the native implementation.

@cra0zy oh, very strange, I should have messed up while testing on OS X. I'm fine with this being Windows only.

**Comment by cra0zy** [comment]
> @cra0zy oh, very strange, I must have messed up while testing on OS X. I'm fine with this being Windows only. It removes a dependency and works fine.

It wasn't Windows only when you tested it, I updated it ^^

**Comment by cra0zy** [comment]
Reload the page!!!

**Comment by mrhelmut** [comment]
:+1:

**Comment by tomspilman** [comment]
My two cents...  using OpenTK with SDL has always seemed dumb to me.  If SDL works better why are we using OpenTK at all?

**Comment by dellis1972** [comment]
@tomspilman I would agree SDL seems to be more consistent across platforms (although opentk has improved recently), we had this discussion before when someone tried to add a SDL platform. We would still need a "OpenTK" compatible API for SDL so that we don't end up with #if SDL everywhere in the graphics apis :)

**Comment by tomspilman** [comment]
> We would still need a "OpenTK" compatible API for SDL so that we don't end up with #if SDL everywhere in the graphics apis :)

We put faith in the new OpenTK team to fix things after it went unmaintained for years.  If OpenTK still sucks after 2 years of effort... we really should reconsider dropping it completely.  This has already hurt MonoGame and we don't need to continue the damage.

**Comment by dellis1972** [comment]
>We put faith in the new OpenTK team to fix things after it went unmaintained for years. If OpenTK still
> sucks after 2 years of effort... we really should reconsider dropping it completely. This has already hurt
> MonoGame and we don't need to continue the damage.

Should we pull it out of iOS and Android too? in favour of our own PInvoke API for GL (which would be limited to what we need and nothing more).

**Comment by tomspilman** [comment]
> Should we pull it out of iOS and Android too?

Gosh that old problem.  Maybe... our own pinvoke wouldn't be too hard to maintain.  Do we still have `ref` vs `out` issues?  I know we have enum mappings we do between the different OpenGL bindings.

**Comment by cra0zy** [comment]
Would you like to see OpenTK replaced by SDL2 for DesktopGL?

**Comment by tomspilman** [comment]
> Would you like to see OpenTK replaced by SDL2 for DesktopGL?

Maybe...   it seems even after 2 years we are patching up OpenTK to fix issues with it.  IMO if they can't make it good in 2 years then why would we think it will work in another 2 years?

If we wanted to do this we would do the work in an experimental branch and see what comes out of it.

What do you think @cra0zy ?  @KonajuGames ?

**Comment by dellis1972** [comment]
@tomspilman lets run an experimental branch and see what drops out, this will be the new backend for DesktopGL :) //cc @cra0zy @KonajuGames

**Comment by cra0zy** [comment]
https://github.com/flibitijibibo/FNA-MGHistory/tree/monogame-sdl2

**Comment by tomspilman** [comment]
@cra0zy - We don't want to take the FNA code... we want our own path.

**Comment by cra0zy** [comment]
> @cra0zy - We don't want to take the FNA code... we want our own path.

Just linking it to remind everyone of it's existence.

**Comment by tomspilman** [comment]
@cra0zy @dellis1972 @KonajuGames - Let's start a separate issue for this https://github.com/mono/MonoGame/issues/4399.

As for this PR.... @cra0zy @dellis1972 ...  is it ready to merge?

**Comment by cra0zy** [comment]
It is.

**Comment by cra0zy** [comment]
Closing this since @mrhelmut managed to fix up OpenTK bugs.

**Comment by mrhelmut** [comment]
Waiting for opentk/opentk#335 & opentk/opentk#334
If anybody know who to ping on the opentk side so we can proceed with an update. :)

**Comment by WardBenjamin** [comment]
Pinging @Frassle

**Comment by dellis1972** [comment]
I pinged both Frazzle and the fiddler. Hopefully someone will respond.. It
would be really handy for someone in the MG community to get merge rights
on OpenTK .. alternatively we fork it and pull our own PR's in then submit
them upstream.

**Pull request closed without merging**
