### PR TITLE
[Pipeline] FilterView for Shader warnings/errors

### PR DESCRIPTION
**Pull request by nkast**
#4460

### CODE REVIEW

**Comment by tomspilman** [comment]
@cra0zy - This look ok to you?

**Comment by nkast** [comment]
@tomspilman Can you test it with your shader? All I did was simulating by feeding it your output and also testing it with a simple typo so far. 

The parser also keep the filename so I had to normalize it. Not sure If we still need that but it's good to keep it around.

@cra0zy, 
According to the internets all chars are valid in a unix filename even ':', so technically all this will fail in some cases under Linux/Mac/etc.

**Comment by cra0zy** [comment]
> According to the internets all chars are valid in a unix filename even ':', so technically all this will fail in some cases under Linux/Mac/etc.

":" char is not allowed on Mac. 

Technically speaking it's not the OS that blocks the character, it's the filesystem.

I am fine with it being the way you wrote it, ":" should never be used in a filename.

**Comment by cra0zy** [comment]
PS. I like using https://regex101.com/ to test and write regex.

**Comment by nkast** [comment]
For example I could do without the _reFileError and just strict _reBuildAsset to match [^\n\r:] instead of [.]. The rest lines from tom's output would then be handled by the finall check at https://github.com/nkast/MonoGame/blob/PipelineFilterOutputShaderWarnings/Tools/Pipeline/Common/OutputParser.cs#L157-L162

**Comment by cra0zy** [comment]
Tested it, and it works.

**Comment by tomspilman** [comment]
Looks good to me guys... merging!  Thanks again @nkast  and @cra0zy !

**Pull request merged**
