### PR TITLE
Pass parameters from MaterialProcessor to TextureProcessor.

### PR DESCRIPTION
**Pull request by nkast**
"PremultiplyTextureAlpha" --> "PremultiplyAlpha"
"ResizeTexturesToPowerOfTwo" --> "ResizeToPowerOfTwo"

Thanks to @mgarstenauer for the fix.

### CODE REVIEW

**Comment by nkast** [comment]
parametersred

**Comment by tomspilman** [comment]
It would be really good to get a unit test for `MaterialProcessor` in place which could have caught this sooner.  Sort of like i wrote for the `TextureProcessor`:

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/TextureProcessorTests.cs

Have any time @nkast ?

**Comment by tomspilman** [comment]
Going to merge the fix for now...  but unit tests really are needed.

**Comment by nkast** [comment]
Ok, noted.

**Comment by tomspilman** [comment]
Added an issue specific to that here: https://github.com/mono/MonoGame/issues/4333.

**Pull request merged**
