### PR TITLE
[Gtk Pipeline] Bunch of fixes

### PR DESCRIPTION
**Pull request by cra0zy**
Stuff done:
<ul>
<li>Fixed context menu containing Add menu when selecting multiple files</li>
<li>Fixed crash when selecting 3 or more objects of different type</li>
<li>Fixed [double click] / [right click > open] not launching default application for the file but instead launching the first possible application for that file type</li>
<li>Fixed some annoying errors that are being show in application output on new item dialog</li>
<li>Double clicking folder now expands/collapses them</li>
</ul>

### CODE REVIEW

**Comment by tomspilman** [comment]
Error...

```
/Applications/buildAgent/work/f26e5a04a66fcbdb/Tools/Pipeline/Gtk/Widgets/ProjectView.cs(496,35): error CS0103: The name `start' does not exist in the current context
```

**Comment by cra0zy** [comment]
You didn't notice, but I already rebased it, yes I learned how to rebase :D

**Comment by tomspilman** [comment]
i need to learn that as well...  i just merge branches. :)

**Comment by tomspilman** [comment]
Thanks! Merging!

**Pull request merged**
