### PR TITLE
[Gtk Pipeline] Added buttons to headerbar and moved menubar to it as well

### PR DESCRIPTION
**Pull request by cra0zy**
Only comes to effect if the user is running GNOME

### CODE REVIEW

**Comment by tomspilman** [comment]
@cra0zy - This has a merge conflict... could you fix it up?

**Comment by cra0zy** [comment]
> @cra0zy - This has a merge conflict... could you fix it up?

I I Captain (Spongebob....)

**Comment by WardBenjamin** [comment]
*cough* That should be "Ay, Ay, Captain" *cough*

**Comment by KonajuGames** [comment]
Aye, it should be aye.

**Comment by KonajuGames** [comment]
Merging. Thanks @cra0zy

**Pull request merged**
