### PR TITLE
Fixed up the Mac Installer #4543

### PR DESCRIPTION
**Pull request by dellis1972**
Issues

1) Missing Permissions
2) Missing files

### CODE REVIEW

**Comment by dellis1972** [comment]
@tomspilman I'm going to test the build artifacts of this one to make sure it works before we merge.

**Comment by VinnieH01** [comment]
@dellis1972 after typing : `sudo ps aux | grep console | grep -v grep | cut -d' ' -f1` in the terminal and then installing monogame it acully got my Username and installed the .mpack... but the framework itself didn't get referenced only the template (Game1.cs etc). So everything was red and full of errors.

**Comment by VinnieH01** [comment]
Changes looks good, I'd recommend merging it.

**Comment by dellis1972** [comment]
I'll give this another test later this evening.

@VinnieH01 did u test the build from this PR?

-----Original Message-----

**Comment by VinnieH01** [comment]
@dellis1972 no, do I have to build it from source or how do I test it?

**Comment by VinnieH01** [comment]
@dellis1972 I just meant that the change looks good, it worked in my terminal, the checks passed and you said that the pipeline fix worked on your machine :)

**Comment by dellis1972** [comment]
@VinnieH01 if you want to test a build for a PR, look for the "Show All checks" link in the area where the "Merge Pull request" button is. Click on it , the click the Details button next to "Package Mac and Linux". This will open the monogame team city server, log in as guest if you need too then click Artifacts. you will then see links to the MonoGame.pkg and the Pipeline.MacOS.pkg files.

**Comment by VinnieH01** [comment]
@dellis1972 ok thanks, I will do that

**Comment by dellis1972** [comment]
This seems to be working fine here. Will test on my other mac as well

**Comment by VinnieH01** [comment]
@dellis1972 The .mpack installs but there's a big red X next to the MonoGame.Framework and when I try to build it... there's errors everywhere.

**Comment by dellis1972** [comment]
@VinnieH01 I don't get that here, Can you gist the build log? http://gist.github.com/

**Comment by dellis1972** [comment]
The Red X is normally ok.. it usually says that there isn't an assembly for framework .net 4.5 .. but I suspect in your case its not finding it at all.

Which version of Xamarin Studio and Mono are you using ? (Xamarin Studios->About -> Show Details, copy and paste the data to a gist)

**Comment by VinnieH01** [comment]
https://gist.github.com/VinnieH01/f4c3e061b76ae7d79362

**Comment by VinnieH01** [comment]
@dellis1972  https://gist.github.com/VinnieH01/21dda3274d6d33236074 Xamarin Details

**Comment by dellis1972** [comment]
@VinnieH01 you'll need to turn on Diagnostic build messages.  In XS.

Xamarin Studios-> Preferences->Build change the Log Verbosity to Diagnostic.

**Comment by VinnieH01** [comment]
@dellis1972 https://gist.github.com/VinnieH01/d6c09b50d75b23964210 Thats with diagnostics on

**Comment by dellis1972** [comment]
@VinnieH01 that still doesn't look like diagnostic logs...

This is what it should look like https://gist.github.com/dellis1972/30b59efb412d1b2e3802
You might need to restart XS?

https://forums.xamarin.com/discussion/27515/how-to-obtain-diagnostic-build-logs

**Comment by VinnieH01** [comment]
@dellis1972 It still looks like that :(

**Comment by dellis1972** [comment]
@VinnieH01  "Which version of Xamarin Studio and Mono are you using ? (Xamarin Studios->About -> Show Details, copy and paste the data to a gist)"

**Comment by VinnieH01** [comment]
I pasted the gist 12 minutes ago it says Xamarin details

**Comment by dellis1972** [comment]
Also can you confirm that 

/Library/Frameworks/MonoGame.framework/v3.0/

Exists and contains a .props file a .targets files and an Assemblies directory (and a Tools one)

**Comment by dellis1972** [comment]
Also which project type are you using ? can you post the contents of the .csproj?

**Comment by VinnieH01** [comment]
/Library/Frameworks/MonoGame.framework/v3.0/ exists with props targets tools and assemblies.
Im using monomac but I tried Xamarin.Mac and that gave me the same result. Do you want me to post the whole project folder?

**Comment by VinnieH01** [comment]
[Test.zip](https://github.com/mono/MonoGame/files/136796/Test.zip)
Here the project

**Comment by dellis1972** [comment]
@VinnieH01 personally I  would stick with a "MonoGame Cross Platform Desktop Project" rather than MonoMac. It will work :) There are a number of problems with MonoMac support at the moment.

There are issues with the MonoMac support. I highly suspect we'll drop it.
The issue in this instance is that the MonoMac does NOT use the xbuild to build its projects so it skips all the stuff we have to resolve the assemblies. So you options are.. reference the assemblies manually or use the Desktop Project I mentioned above. Even then I suspect it won't run (it doesn't here)

**Comment by dellis1972** [comment]
@tomspilman @KonajuGames these changes look like they fix the issues with the Mac Installer, should be good to merge.

**Comment by VinnieH01** [comment]
@dellis1972 Yes it works thank you. You think its ready to be merged?

**Comment by VinnieH01** [comment]
@dellis1972 When I run it a window pops up with no borders, is this normal?

**Comment by VinnieH01** [comment]
its set to fullscreen

**Comment by VinnieH01** [comment]
windowed works

**Comment by VinnieH01** [comment]
It works if I change the resolution to 1920 x 1080 so I guess its not a problem

**Comment by dellis1972** [comment]
@VinnieH01  you are hitting #4538  which should be fixed by #4540

**Comment by VinnieH01** [comment]
@dellis1972 ok nice then I think this is ready to be merged :D

**Comment by dellis1972** [comment]
@VinnieH01 yup :) its protocol here that people do not merge their own PR's :) so either @tomspilman or @KonajuGames  needs to merge this.

**Comment by VinnieH01** [comment]
@dellis1972 I don't know if this is the right place to ask this but on monomac I could just go into the bin folder after building the project and find a .app file there but now I only find a .exe how do I make a .app file?

**Comment by dellis1972** [comment]
@VinnieH01 With the "DesktopGL" project you only get an exe. This PR  #4430 has some docs in progress. While developing you don't need the .app that is only for deployment. 

Note if you do want to deploy to the mac store you will need to use Xamarin.Mac which embeds the mono runtime. Someone needs to make the time to get that bit working properly.

**Comment by VinnieH01** [comment]
@dellis1972 ok its ok Im not planning on deploying an app very soon anyway

**Comment by KonajuGames** [comment]
Merging. Thanks.

**Pull request merged**
