### PR TITLE
[Eto Dialogs] Reference Dialog

### PR DESCRIPTION
**Pull request by cra0zy**
This needs: MonoGame/MonoGame.Dependencies#77

Before left, after right:
untitled

### CODE REVIEW

**Comment by tomspilman** [comment]
I just merged the dependencies.

**Comment by cra0zy** [comment]
> I just merged the dependencies.

Dependencies are updated.

**Comment by tomspilman** [comment]
Is that window still resizable?

**Comment by cra0zy** [comment]
> Is that window still resizable?

Yup.

**Comment by tomspilman** [comment]
Ok...  i'll merge this.

I'd like to see us fix the margin between the controls and the borders on this and the other new dialogs.  It is really tight... looks wrong under Windows.

**Comment by cra0zy** [comment]
> I'd like to see us fix the margin between the controls and the borders on this and the other new dialogs. It is really tight... looks wrong under Windows.

Sure, just post a screenshot of some dialog and I'll try to copy the margin.

Also I did think a head of time and made a "DialogBase" class which is responcible for positioning OK/Cancel buttons and the main Content area:
https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Eto/Dialogs/DialogBase.eto.cs so all I have to do is modify it once and it will change it for all the dialogs :)

**Comment by KonajuGames** [comment]
> Sure, just post a screenshot of some dialog and I'll try to copy the margin.

The original Windows reference dialog above has the correct margins between the window edges and the controls.

**Pull request merged**
