### PR TITLE
Multithreaded friendly PVRTexture

### PR DESCRIPTION
**Pull request by nkast**
Depends on https://github.com/KonajuGames/PVRTexLibNET/pull/1

### CODE REVIEW

**Comment by nkast** [comment]
The Test failure is excepted because it depends on a modified PVRTexLibNET.dll 
Future goal is to use all available cores to build content.

Test branch: https://github.com/mono/MonoGame/compare/develop...nkast:tncMultithreadContentPipeline?expand=1

**Comment by tomspilman** [comment]
I'm good with this getting fixed.

> Future goal is to use all available cores to build content.

Yes... this was always my goal with implementing the XNA pipeline in MonoGame.  We want to at some point re-write the core processing loop to work with `Task` or `Parallel.For`.

**Comment by nkast** [comment]
The testing branch was an afternoon play, lots of testing and work to do from here, hopefully with the help from others that know the build pipeline better. I have to say that it was very satisfying to seen the pipeline output scroll down as all my 4 cores were crunching assets!

The PVRTexture currently doesn't cause any problems so I am OK if you have to look into this PR after the 3.5 release.

**Comment by tomspilman** [comment]
> I have to say that it was very satisfying to seen the pipeline output scroll down as all my 4 cores were crunching assets!

We have projects that take 40 minutes to build content single core... so we feel the pain here too.

Most importers/processors/writers should work fine in parallel.  We probably just need to review all the code for statics and look for potential threading problems.  We will need to figure out how to group the logging so that we don't get interleaved build output from multiple files.  Also need to take extra special care about dependent content and be sure it is only built once.

Still totally possible to make work... just needs a little effort behind it.

**Comment by KonajuGames** [comment]
Just added some comments on the related PR.  Easily fixed issues, then I'm good with this.

**Comment by nkast** [comment]
@KonajuGames I assume the changes in this PR are already part of #4496 and coupled with the related submodule update, right? Can I close this?

**Comment by KonajuGames** [comment]
Yes. It no longer uses a global variable for PVRTexLib.

**Pull request closed without merging**
