### PR TITLE
Update texture compression in content build pipeline for Mac and Linux

### PR DESCRIPTION
**Pull request by KonajuGames**
Revert back to NVTT for DXT. More reliable on Mac and Linux, but a lot slower.
Update PVRTexLibNET and PVRTexLibWrapper.
Remove use of internal global variable in PVRTexLibNET.

### CODE REVIEW

**Comment by KonajuGames** [comment]
I'll look into the failure closer tomorrow night.

**Comment by cra0zy** [comment]
Tested from Linux, worked without problems.

**Comment by dellis1972** [comment]
@KonajuGames just waiting for #4503 to get merged before I can full test this. will report back asap. If it works I'll merge

**Comment by dellis1972** [comment]
@KonajuGames there was a bug that stopped me testing this. Can you rebase against the latest develop and ill test again

**Comment by dellis1972** [comment]
This is good and it looks like the tests passed.

**Comment by KonajuGames** [comment]
@tomspilman, if you're good with this it should be right to merge.  @cra0zy and @dellis1972 have tested on Linux and Mac.

**Pull request merged**
