### PR TITLE
Windows 10 Support Pt. 4 - Build 2015 Edition  

### PR DESCRIPTION
**Pull request by tomspilman**
This PR has a bunch of fixes to support the new Windows 10 toolset release at Build 2015 tomorrow.

 - Support for fullscreen.
 - Dpi scaling fixes.
 - Fixed bug with list key up events.

Our Windows 10 support is still in its early stages, but it is closer to fully working now.

### CODE REVIEW

**Comment by tomspilman** [comment]
Gonna test this installer on Win10 and if all is good i'll merge!

**Comment by KonajuGames** [comment]
When does the new SDK become available?

**Comment by tomspilman** [comment]
@KonajuGames - My guess is sometime today, but I don't know when exactly.  So we're sort of ahead of the curve on this release for a few more hours.

**Comment by tomspilman** [comment]
This seems good to go.. merging!

I'm off to get the 3.4 release up now.

**Pull request merged**
