### PR TITLE
Use VisualStudio coding policy when opening the project from MonoDevelop

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by tomspilman** [comment]
@dellis1972 - So you know what this MonoDevelop policy file is?  Does it extend to XamarinStudio too?

**Comment by tomspilman** [comment]
@dellis1972 - Looking at the error in this PR I found this:

```
[15:44:21]if (17s)
[15:44:21]call (17s)
[15:44:21]checkos
[15:44:21]if (running for 22s)
[15:44:21]if (running for 22s)
[15:44:21]mdtool : /Applications/Xamarin Studio.app/Contents/MacOS
[15:44:21]Detected : MacOS
[15:44:21]buildaddin (17s)
[15:44:21]get (1s)
[15:44:21]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.Android/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.Android.3.3.0.nupkg'.
[15:44:22]get
[15:44:22]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.iOS/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.iOS.3.3.0.nupkg'.
[15:44:22]get
[15:44:23]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.Linux/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.Linux.3.3.0.nupkg'.
[15:44:23]get (1s)
[15:44:24]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.MacOS/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.MacOS.3.3.0.nupkg'.
[15:44:25]get
[15:44:26]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.Ouya/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.Ouya.3.3.0.nupkg'.
[15:44:26]get
[15:44:26]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.WindowsDX/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.WindowsDX.3.3.0.nupkg'.
[15:44:26]get
[15:44:27]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.WindowsGL/3.3.0' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.WindowsGL.3.3.0.nupkg'.
[15:44:27]get
[15:44:27]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.Portable/3.2.99.1-Beta' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.Portable.3.2.99.1-Beta.nupkg'.
[15:44:27]get
[15:44:28]Retrieving 'https://www.nuget.org/api/v2/package/MonoGame.Framework.Content.Pipeline.Portable/3.2.99.1-Beta' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/MonoGame.Framework.Content.Pipeline.Portable.3.2.99.1-Beta.nupkg'.
[15:44:28]get
[15:44:28]Retrieving 'https://www.nuget.org/api/v2/package/Ouya.Console.Api/1.0.13.1' to '/Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame/packages/Ouya.Console.Api.1.0.13.1.nupkg'.
[15:44:28]if (9s)
[15:44:28]exec (2s)
[15:44:29]Xamarin Studio Build Tool
[15:44:29]Loading solution: /Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame.Addin.sln
[15:44:29]   Loading solution: /Applications/buildAgent/work/f26e5a04a66fcbdb/IDE/MonoDevelop/MonoDevelop.MonoGame.Addin.sln
[15:44:29]      Loading projects ..
```

What is all this nuget download stuff?  Is the XS addin not using the assemblies just built?

**Comment by cra0zy** [comment]
I know I am not @dellis1972 but I do know the answers..

> So you know what this MonoDevelop policy file is?

This file can do stuff related to MonoDevelop/Xamarin Studio coding policies and naming policies. If you want to see what it can do, create a new project using MD/XS, go right click > Options > Source Code, and this file can change anything under there for the current project. In this case I only change Code Format > C# source code to use Microsoft Visual Studio Policy.

> Does it extend to XamarinStudio too?

Xamarin Studio is Monodevelop with few custom addins for android, monomac, ios and name/logo change, so yea, it extends Xamarin Studio too.

**Comment by tomspilman** [comment]
@cra0zy - As far as the error occurring in this build... you will want to rebase/merge the latest changes in about an hour.  A fix @dellis1972 made to the Xamarin addin is what is causing your error.

**Comment by dellis1972** [comment]
This is a good thing :) will fix some of the code formatting issues in future PR's from XS/MD users.

With regards to the NuGet stuff, at the moment the XS addin uses the Nuget packages, this is because of the issues with assembly resolution under MD/XS its something I might be able to solve in the future. But for now we use the NuGets. when we finally get the NuGet publishing build into the system we can use those rather than downloading them, that way we can use the latest packages. We could get away with not including the packages in the addin itself, but that would mean the templates would not work offline which was a requirement. The good news is that if some is online and there is a newer package they will be notified to update.

**Comment by tomspilman** [comment]
@dellis1972 - Thanks...  now I remember.  This further solidifies my hate of nuget. :)

**Comment by tomspilman** [comment]
Ok... merging!

**Pull request merged**
