### PR TITLE
KeyboardInput and MessageBox converted to static form

### PR DESCRIPTION
**Pull request by Shqrdx**
These classes intended to be static. They are partial but it is not a problem for combine static and partial in one place.

### CODE REVIEW

**Comment by tomspilman** [comment]
@Nezz - This seem right to you?

**Comment by KonajuGames** [comment]
That makes sense.  It prevents someone from trying to create an instance of that class, which is pointless if all members are static.

**Comment by Nezz** [comment]
Yes, this is correct.

**Comment by tomspilman** [comment]
Thanks guys!

**Pull request merged**
