### PR TITLE
refactor of wiki page to doc page

### PR DESCRIPTION
**Pull request by ralfjansson**
Moved text from wiki concerning Android manifest requirements and added
to Platform specific notes for Android.

My first PR ever. I hope this works.

### CODE REVIEW

**Comment by KonajuGames** [comment]
That worked well.  Thanks @ralfjansson.  Merging.

**Comment by tomspilman** [comment]
@ralfjansson - You should probably clear out that info from the wiki page now or do something to mark it as now in the main docs.

**Comment by ralfjansson** [comment]
Ok. Forgive me for asking, but that means I need to fork the wiki as it is in another Project?

**Comment by tomspilman** [comment]
> but that means I need to fork the wiki as it is in another Project?

No... you can edit the wiki directly from github site.  You should see an `Edit` button to the right of the title on each page.

**Comment by ralfjansson** [comment]
Ok. Got it. I changed the old wiki page as you suggested by adding a commonent on "stale information" as has been done on some other wiki pages. The change seam to have taken effect at once?

**Comment by tomspilman** [comment]
> adding a commonent on "stale information"

Actually I think we remove the information entirely and just link to the new doc.  Just want no confusion from duplicate info floating out there.  The wiki retains history... so if we ever really need the old info back we can get it.

**Comment by ralfjansson** [comment]
Ok. Fixed that. Now there is only a link to the new documentation on that page.

**Comment by tomspilman** [comment]
Yep... perfect.

https://github.com/mono/MonoGame/wiki/Android-Manifest-Requirements

Thanks @ralfjansson !

**Pull request merged**
