### PR TITLE
[Win Pipeline] Toolbar and saving settings

### PR DESCRIPTION
**Pull request by cra0zy**
Implements #4389 and #4321 for Windows Pipeline Tool.

winpiptool

### CODE REVIEW

**Comment by tomspilman** [comment]
Looks great... merging!

**Comment by Jankamp** [comment]
Correct me if I'm wrong, I'm new to monogame:
I think the change on the MainView designer file broke the update of the propertygrid when selecting assets in the treeview. I'm no longer able to update the settings of an fbx because TreeViewAfterSelect doesn't fire, so the propertygrid is always showing the project settings.

I'm talking about the removal of the following line:
```this._treeView.AfterSelect += new 
System.Windows.Forms.TreeViewEventHandler(this.TreeViewAfterSelect);```

![pipelinetool](https://cloud.githubusercontent.com/assets/16737937/12374790/7af4fe1e-bca7-11e5-8846-9a10be2778cc.png)

**Comment by cra0zy** [comment]
> I'm talking about the removal of the following line:
> this._treeView.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.TreeViewAfterSelect);

You are right. That shouldn't have gotten removed at all. 'MainView.Designer.cs' file is edited by VS GUI designer and the only thing I did in it was move some components to make room for the toolbar... well from now on I think I will stick with editing stuff by hand, much more precise...

I'll submit a fix tomorrow unless someone beats me to it.

**Comment by tomspilman** [comment]
The sooner the better.

We really need to think about how to setup automated testing for the Pipeline tool.

**Pull request merged**
