### PR TITLE
Ogg end of stream fix

### PR DESCRIPTION
**Pull request by mrhelmut**
A little path of code I forgot to revert from a previous PR. This fixes the end of stream handling.

It's the last remaining issue I've been encountering with OpenAL. :)

@dellis1972

### CODE REVIEW

**Comment by dellis1972** [comment]
This looks ok to me.. the test failure looks unrelated.

**Comment by mrhelmut** [comment]
Didn't even noticed that a test failed on this one. Any way to relaunch them?

**Comment by dellis1972** [comment]
@tomspilman is the only one that can afaik

-----Original Message-----

**Comment by KonajuGames** [comment]
Or do an rebase/pull from upstream and submit to the branch.  This will trigger a new build and checks.

**Comment by mrhelmut** [comment]
Not sure I did that correctly. ^^'

**Comment by dellis1972** [comment]
@mrhelmut its fine now :)

**Pull request merged**
