### PR TITLE
Added event for form move.

### PR DESCRIPTION
**Pull request by cuddlyogre**
The form move event is now implemented.

### CODE REVIEW

**Comment by tomspilman** [comment]
@KonajuGames @dellis1972 - Do you think we need a `GameWindow.Moved` event?

@cuddlyogre - What was the need you had which required this new feature?

**Comment by cuddlyogre** [comment]
The application I am building requires that the window redraw continuously on move and resize. To bypass #3995 / #4211, I set up a second tick that runs with those events. It works perfectly on resize and after I added a move event, that worked as well.

I imagine there are more game-related uses for this as well, like an etch-a-sketch type game.

**Comment by cuddlyogre** [comment]
Out of curiosity, has this been discussed any further?

**Comment by tomspilman** [comment]
Bump!

@KonajuGames @dellis1972 @cra0zy - Do you think we need a `GameWindow.Moved` event?  Seems like something that is only useful on desktops.

**Comment by cra0zy** [comment]
#4662 

I think this should be closed as well.

**Comment by tomspilman** [comment]
Thanks for reminding me of that out @cra0zy .  We've already ruled on not wanting to expose this type of event to MonoGame.

@cuddlyogre - Take a look at the comments in https://github.com/mono/MonoGame/pull/4662 for our reasoning.

**Comment by cuddlyogre** [comment]
Are there any thoughts behind solving issue #3995 so as to render my work around unnecessary? It seems counterproductive to keep a known bug in place only so tests will pass.

**Pull request closed without merging**
