### PR TITLE
Added Ubuntu 15.04 to dependencies

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by KonajuGames** [comment]
Do you have to add each version of Ubuntu separately? Can it be >= 14 so you don't have to modify it each time they release a new version?

**Comment by cra0zy** [comment]
I could, but it may fail on newer releases, I only add platforms on which I actually try running it

**Comment by cra0zy** [comment]
If you still want me to setup >= just say it, and I'll add it.

**Comment by KonajuGames** [comment]
@tomspilman what are your thoughts?  I'm leaning towards making it a >= check for Ubuntu version.  If any future version breaks then it can be dealt with at that time.

**Comment by tomspilman** [comment]
I don't know enough about Linux to say.  Whatever you guys think is best.

**Comment by cra0zy** [comment]
Silly me, yesterday I forgot to push changes, I just noticed

**Comment by KonajuGames** [comment]
Thanks for that @cra0zy

**Comment by KonajuGames** [comment]
Merged.

**Pull request merged**
