### PR TITLE
[Eto Forms] Pipeline Tool Main Window

### PR DESCRIPTION
**Pull request by cra0zy**
NEEDS: #79

There are still stuff to do around here, but most of them are per platform, so I think it will be easier to just merge this and get some help by other members because this is huge change and I could really use some help on it.

Notes:
 - No drag & drop, will be implemented in a future PR
   - move action should be rewritten before this is done
 - perplatform stuff is located in 3 files, and those are:
   - Style.Platform - some basic styling for controls
   - Global.Platform - some functions that are per platform, like OpenWith dialog and loading native Icons for files and folders
   - ProjectControl.platform - ProjectControl uses treeview which is not multiselectable, the only point of this file is to make it able to select multiple items
 - Mac only has a shell implemented for it's platfom stuff instead of using a copy of gtk stuff, this is because we can switch to Xamarin.Mac, @dellis1972 If you have time please try and compile Pipeline Tool with Eto.XamMac instead of Eto.Gtk2, look at ProjectControl.gtk.cs to see how to load stuff into property grid
 - ~~some perplatform stuff is missing, this will be added in a future PR, I skipped adding it because of above, that is it can be done for Mac by someone else while I am working on Windows/Linux sides~~
 - Full Eto.Forms propertygrid custom drawn :D
   - text editing and selection editing is launching a dialog with a textbox/combobox, I would like to replace this with a control inside the propertygrid itself
   - ~~there is no way to set separator position~~
 - ProjectControl.win.cs is a dirty copy of the MultiselectTreeview control
 - moved as much stuff as I could from the View to the Controller

No screenshoots :(, download and try the tool from the installer, do tell me what you think about the property grid.

### CODE REVIEW

**Comment by cra0zy** [comment]
I found few minor bugs, I'll add a fix for them plus implement some per platform stuff.

**Comment by cra0zy** [comment]
Update NO. 1:
 - fixed treeview expanding
 - fixed property grid not able to edit multiple objects if they have different values
 - fixed property grid width not shrinkable
 - improved about dialog so it does not require any per platform code
 - implemented native icons in treeview for Windows and Linux
 - implemented open with dialog for Windows and Linux
 - implemented base treeview for Mac, it can't multiselect
 - implemented native toolbar icons for Linux
   - if someone wants to point me to some icons for Windows toolbar I won't mind adding them

Current ToDo (not counting Drag & Drop):
 - Linux:
   - implement HeaderBar
 - Windows:
   - add native icons for toolbar
   - some more styling might be nice, WinForms look so outdated on Windows 10
 - Mac: (I can't do this one)
   - switch to Eto.XamMac
   - missing all the native stuff

**Comment by dellis1972** [comment]
@cra0zy I'm at Evolve all week plus I have to GL/AL stuff to finish I won't get to Eto on mac or a while. perhaps someone else can take a crack at it?

**Comment by cra0zy** [comment]
Just want to mention that Mac side of the tool will work with the way I set it up now, but projectView is not multiselectable and it's using Gtk 2.

@mrhelmut Are you maybe interested in this?

**Comment by cra0zy** [comment]
@tomspilman @KonajuGames Should I continue adding commits to this or should I wait for this to get merged?

**Comment by tomspilman** [comment]
> Should I continue adding commits to this 

No... lets not add any more changes here... it is way big as it is.

**Comment by cra0zy** [comment]
Well I did something fun using this PR locally:
content

**Comment by cra0zy** [comment]
Also sorry about the commit, I just needed few classes public so the addin can work without any modifications to the Pipeline Tool.

**Comment by KonajuGames** [comment]
Double-clicking a boolean property should toggle the property value rather than bring up a separate dialog box containing a combobox dropdown.
Enumerated type properties should have the combobox dropdown in the property cell, not show a separate dialog box containing the combobox dropdown.  Same for the Importer and Processor properties.

**Comment by cra0zy** [comment]
> Double-clicking a boolean property should toggle the property value rather than bring up a separate dialog box containing a combobox dropdown.

Ok, that is easy to do.

> Enumerated type properties should have the combobox dropdown in the property cell, not show a separate dialog box containing the combobox dropdown. Same for the Importer and Processor properties.

As I said before:

> text editing and selection editing is launching a dialog with a textbox/combobox, I would like to replace this with a control inside the propertygrid itself

**Comment by cra0zy** [comment]
@tomspilman @KonajuGames Want me to rebase this to 1 commit?

**Comment by tomspilman** [comment]
> Want me to rebase this to 1 commit?

No need...  the problem isn't that there are too many commits.  The problem is there are 126 files changed.  That makes it hard to review and approve.

**Comment by KonajuGames** [comment]
I've got a local branch of this PR, so I'll check it again now.

**Comment by KonajuGames** [comment]
While there are still some small usability issues (should have in-cell combobox for enums rather than separate dialog, first click in treeview after dismissing dialog box is ignored), it does fix two larger issues that currently affect the pipeline tool (crash due to missing call to Init() in MainView, process never terminates on closing window).  That being the case, I'm in favour of merging this now and fixing the usability issues later.

**Comment by tomspilman** [comment]
> That being the case, I'm in favour of merging this now and fixing the usability issues later.

As long as we get to these quickly after merge... i'm good with that.  We do have a lot of people using the develop branch on a daily basis, so we can't leave anything badly broken for weeks.

Sound good @cra0zy ?

**Comment by cra0zy** [comment]
> Sound good @cra0zy ?

Sounds good.

**Comment by KonajuGames** [comment]
Pulling the trigger.

**Comment by cra0zy** [comment]
> first click in treeview after dismissing dialog box is ignored

Can you give me steps to reproduce? I've been unable to get that bug.

**Comment by KonajuGames** [comment]
> Can you give me steps to reproduce? I've been unable to get that bug.

Select an item in the treeview.  Double click an enum property to show the dialog.  Cancel the dialog.  Click on a different item in the treeview.  The item won't select.  Click it again or another item and it will select.

**Comment by cra0zy** [comment]
> Select an item in the treeview. Double click an enum property to show the dialog. Cancel the dialog. Click on a different item in the treeview. The item won't select. Click it again or another item and it will select.

#4837 fixes it :)

**Pull request merged**
