### PR TITLE
Implement VertexTextures and VertexSamplerStates for Direct3D

### LINKED ISSUE #2602: Vertex Texture Fetch Not Supported
Vertex Texture Fetch is not currently supported by Monogame. It would be great to have support for it. High-priority platforms for me are Windows (DirectX) and PS4.

### PR DESCRIPTION
**Pull request by tgjones**
Matches XNA API for vertex textures, including `GraphicsDevice.VertexTextures` and `GraphicsDevice.VertexSamplerStates`.

Fixes #2602, and partially replaces #2998.

### CODE REVIEW

**Comment by tomspilman** [comment]
This looks great... going to leave it open a little longer for others to give feedback, but I think it looks good to merge.

**Comment by tomspilman** [comment]
Ok... going to merge this!  Thanks @tgjones ... we owe you many beers.

**Comment by tgjones** [comment]
Cool! A couple of things that I'll note here, as a reminder for me or whoever implements OpenGL support in the future:

* I haven't done anything to differentiate between `Reach` and `HiDef`-  in fact I have yet to look at how MonoGame uses graphics profiles. IIRC, XNA didn't allow vertex textures in the `Reach` profile. Perhaps we'll need to do something similar for the various OpenGL-based platforms.
* I haven't tested on Windows Phone, so I'm not sure if vertex textures are supported there.

**Comment by tomspilman** [comment]
> how MonoGame uses graphics profiles.

We use them pretty loosely.  We for certain have missing asserts and stuff for features that only work under `HiDef`.

**Pull request merged**
