### PR TITLE
Added LocationChanged API for the GameWindow.

### PR DESCRIPTION
**Pull request by nilllzz**
Added OnLocationChanged event for Windows DX and OpenTK platform, which
reacts to changes in the location of the game window.

### CODE REVIEW

**Comment by tomspilman** [comment]
I don't know about adding this.  It only is relevant for the 3 desktop platforms and I see little use for it in games.  Unless there is some critical need for window move events I think this should be closed.

@KonajuGames @dellis1972 @cra0zy ?

**Comment by cra0zy** [comment]
> I don't know about adding this. It only is relevant for the 3 desktop platforms and I see little use for it in games. Unless there is some critical need for window move events I think this should be closed.

Agreed. Also #4605

**Comment by KonajuGames** [comment]
Agreed.  We need to keep focus on things that affect a game, and the
changing of the window position does not affect the game.  There is no
issue with you doing this in your own fork of MonoGame, but we don't
believe it belongs in the core framework.

**Comment by cra0zy** [comment]
> There is no
> issue with you doing this in your own fork of MonoGame, but we don't
> believe it belongs in the core framework.

He doesn't really need to even fork it, he just needs to check window position on "Update" method and fire up an event when it gets moved...

**Pull request closed without merging**
