### PR TITLE
Pipeline indicator for missing files

### PR DESCRIPTION
**Pull request by cra0zy**
I liked the idea from #3322 so I added it.

### CODE REVIEW

**Comment by cra0zy** [comment]
@tomspilman @dellis1972 That failed test makes no sense, did I do something wrong?

**Comment by tgjones** [comment]
@cra0zy No, it's not you - that test has been failing intermittently ever since I added it.

@tomspilman I'll take a look at it now. I don't think I materially changed `GetData` (only `SetData`) so I suspect this new test probably exposes some underlying issue that has been present for a while. I'll know more when I find out what the actual problem is.

**Comment by cra0zy** [comment]
@tgjones Thanks for the info!!!

**Comment by tgjones** [comment]
I think I've fixed this intermittent test failure: #3402. (It turned out to be a long-standing issue in a little-if-at-all-used code path in `GetData`, that happened to be uncovered by the tests I wrote for my `SetData` changes.)

**Comment by KonajuGames** [comment]
@cra0zy If you merge latest from develop into this branch, it will re-run the test.

**Comment by cra0zy** [comment]
It would be nice if someone could merge this. After this PR I am changing to using other branches for PR instead of develop branch so I can setup multiple PRs at the same time.

**Comment by KonajuGames** [comment]
I'll merge this now.  We can fix the path separators in a later PR (there are constants in .NET for path separators on a platform).

**Comment by cra0zy** [comment]
Thanks @KonajuGames !!!

**Pull request merged**
