### PR TITLE
Implemented DrawInstancedPrimitives(), SetVertexBuffers() and improved input layout caching for DirectX.

### PR DESCRIPTION
**Pull request by Helikin**
This PR adds the DirectX implementation for **DrawInstancedPrimitives** and **SetVertexBuffers**. The hashing and caching of vertex input layouts is also fixed/improved.

Before writing this code, we have reviewed the related issues for these topics:
- GraphicsDevice.DrawInstancedPrimitives API not yet implemented. #913
- GraphicsDevice.SetVertexBuffers API is not yet implemented #914
- Implemented GraphicsDevice.SetVertexBuffers(...) #3276

This implementation is used successfully in the DigitalRune Engine for mesh instancing and morph target animation. We have also added some simple unit tests.

There is one important change regarding the vertex attribute semantics **SV_Position** and **POSITION** in shaders:
The recommended semantic for the vertex input element which describes the vertex position is **POSITION**. However, the XNA stock effects use **SV_Position**. This is allowed in DirectX but it is better to use **SV_Position** ("system-value position") only for the vertex shader output and pixel shader input. 
This is important when using morph targets. Each morph target mesh has a **POSITION0** element. At runtime the morph target vertex streams are matched and combined to a single input layout with **POSITION0/1/2/3**. This is not possible with **SV_Position** because **SV_Position1/2/3** is not a valid semantic.
Therefore, we have changed the C# code and shaders to use **POSITION** for vertex inputs. 
The new code contains a fallback to handle shaders with **SV_Position**, but we recommend to only use **POSITION** for vertex shader input for all future MonoGame shaders.

The vertex input type for BLENDINDICES has been changed from int4 to uint4. This prevents SharpDX warnings when run on debug device. (The problem is that the MonoGame content pipeline outputs Byte4 for BLENDINDICES. MonoGame does not have a signed integer format that matches int4.)

This PR also fixes a minor bug in the GraphicsDevice OpenGL code: The flag **_vertexBufferDirty** was never reset to false.

### CODE REVIEW

**Comment by Vodacek** [comment]
Good job! It will be awesome to have this merged soon.

**Comment by Discosultan** [comment]
This is awesome! Thanks a ton for this PR.

**Comment by tomspilman** [comment]
This looks good on my first pass thru it.

@KonajuGames  @tgjones  - Can you guys take a look thru this and report anything you see.

**Comment by tgjones** [comment]
This is great - good job, @Helikin, this is a very high quality pull request.

I'm particularly happy to see my pet peeve, the `SV_Position` input semantic thing, being fixed - that's bothered me for a while :)

I haven't run the new tests against XNA, but I assume they pass?

**Comment by Helikin** [comment]
@tgjones Thanks for the feedback. The majority of the code was written by @mgarstenauer. So he deserves most of the praise.

All tests pass on my test machine and as I can see on the builds server. To check for any sideeffects on the OpenGL builds, I have also run the Linux build (in Win 10 not in Linux) and the Mac build on my Mac.

**Comment by KonajuGames** [comment]
You have both done well on this one.  It's a big addition that we have needed for a long time.

**Comment by KonajuGames** [comment]
I'll merge this now.

**Comment by Helikin** [comment]
@tomspilman @tgjones @KonajuGames Thanks for reviewing and the quick merge.

**Comment by kvenkateshan** [comment]
Helikin, any chance you are also working on bringing this over to PS4? We have major features relating to instanced based rendering and are curious to know about any timelines around this feature making it over to PS4. Thanks for your help!

**Comment by tomspilman** [comment]
DX instancing is a bit different than on PS4, but some of this work should help get things started there.

**Comment by kvenkateshan** [comment]
Where would I find the documentation for the GL instancing calls? PS4 sdk? If there's no movement on this by end of this year, I will have to locally take a crack at it. Any info you can give me is highly appreciated.

**Comment by tomspilman** [comment]
> Where would I find the documentation for the GL instancing calls?

I don't know much at all about the GL side.  For sure someone needs to address that.  But this has nothing to do with PS4.  You should look thru the PS4 sdk for instancing.

**Comment by kvenkateshan** [comment]
Well, I will started digging into this and will probably open a new thread to ask for public help if I am blocked on specific bits.

**Comment by tomspilman** [comment]
> ask for public help if I am blocked on specific bits.

Remember if you want to talk about PS4 specifically it can't be here in public.  It has to happen on the private repo for it.

**Comment by kvenkateshan** [comment]
Got it, thanks!

**Comment by pzgulyas** [comment]
One think is missing from SetVertexBuffers() implementation: When XNA is fed with a list of VertexBuffer-s, they get implicitly converted to VertexBufferBinding-s, while MonoGame doesn't do this. 

Example:
``graphicsDevice.SetVertexBuffers(vertexBuffer1, vertexBuffer2);`` works with XNA, but fails with MonoGame.

**Comment by mgarstenauer** [comment]
@pzgulyas That's true. But I don't miss that feature. You should always pass your own `VertexBufferBinding[]` when calling `SetVertexBuffers` and reuse the array. Otherwise, .NET allocates a new array each time, which creates unnecessary garbage.

**Comment by tomspilman** [comment]
> Otherwise, .NET allocates a new array each time, which creates unnecessary garbage

I agree.  When we can avoid adding an API that requires garbage generation we should.

I wonder if we could simply add overloads for 2, 3, and 4 VBs which internally use a scratch array.  Gives you a similar behavior without any garbage.

**Comment by mgarstenauer** [comment]
Yes, new method overloads are a possible solution. However, for morphing I need up to 6 VBs (base mesh + 5 morph targets). So I would need overloads for 2, 3, ... 6 VBs, which sounds a bit much.

**Comment by SeriousMartin** [comment]
Awesome! Thanks a lot!

**Pull request merged**
