### PR TITLE
Updating all the Project templates to have the same MG styled Game page template

### PR DESCRIPTION
**Pull request by DDReaper**
Updated the Game.cs in all templates to use @theZMan 's fantastic new MG theme :D

All templates now have the same start point, with only a few platform variances for resolution or platform specific requirements (like Ouya)

### CODE REVIEW

**Comment by tomspilman** [comment]
@KonajuGames  @dellis1972 - How do you feel about this lerping color in the templates?

**Comment by dellis1972** [comment]
It looks great, I like the fade from the xna cornflower to the mg color. 
That said will it be confusing for people new to XNA/MG.... 

Side note  : We should probably add a Color.MonoGameRed/Orange :P

**Comment by Shqrdx** [comment]
@DDReaper You could use Color.Lerp instead Vector3.Lerp - it is more compact and clever. If my addition is accepted you could use Color.MonoGame instead "new Vector3(0.9059f, 0.2353f, 0f)".

**Comment by DDReaper** [comment]
Was talking with Dom and a better name for MonoGame orange would be "Clockwork" 
What do you think guys?

**Comment by Shqrdx** [comment]
> Was talking with Dom

You mean Tom ?

**Comment by DDReaper** [comment]
Rofl, no, I meant Dominique Louis 😆 @softsavage

**Comment by theZMan** [comment]
Hilarious but Color.Clockwork doesn't really follow the standards of the other color names so I think it wold be more confusing than MonoGameOrange

**Comment by tomspilman** [comment]
As funny as you might think it is we don't need "Clockwork Orange" in MonoGame.

**Comment by tomspilman** [comment]
So I checked out the effect today.  I personally feel like just making it MonoGameOrange is more than enough, but i'll let @KonajuGames make the call on that.

Regardless of what is decided we should use the new `Color.MonoGameOrange` constant as suggested in https://github.com/mono/MonoGame/issues/3584.

**Comment by DDReaper** [comment]
Ok, if #3674 is merged, I'll update the templates to use that style instead

**Comment by tomspilman** [comment]
@DDReaper - You can maybe try rebasing to squash the commits into a single one if that is your concern here.  I've never done it myself, but I know others have.

**Comment by tomspilman** [comment]
So as a test a set this up today...

logo

It is just a modification of the spinning cube code from the existing Windows Universal templates.  I generated a 3D model of the extruded MonoGame logo and embedded the index and vertex data right into the code.   I also switched it to be implemented via a `GameComponent`...
```
        protected override void Initialize()
        {
            Components.Add(new MonoGameLogo(this));
            base.Initialize();
        }
```
This leaves the `Game.cs` clean and the model can be removed via a single line comment when starting a new project.

It also serves to remind people MonoGame isn't just about 2D games.

Thoughts?

**Comment by KonajuGames** [comment]
Looks great. All self contained which is good. Perhaps add a comment above
the creation of the component to comment/remove it when staying the project.

**Comment by dellis1972** [comment]
Can we put that logo component in the framework :P

**Comment by Shqrdx** [comment]
Yeah with cube,sphere and teapot please : )

**Comment by tomspilman** [comment]
> Can we put that logo component in the framework :P

Yeah... we could I guess.  At least then it is always available for demos and such.

> Yeah with cube,sphere and teapot please : )

My original idea was to make this component into a VS template item.  If we wanted to provide premade primitives for rendering maybe we offer that way.

**Comment by theZMan** [comment]
While its cool to have it in a API adding it to the template is just code people have to delete every time... total waste IMO.

**Comment by tomspilman** [comment]
> code people have to delete every time... total waste IMO.

I have to delete that unused `SpriteBatch` in XNA's template every time... still hasn't impacted my productivity.  :)

And when literally the removal is:

```
// Components.Add(new MonoGameLogo(this));
```

Then there really isn't a lot to complain about I don't think.

**Comment by DDReaper** [comment]
Sounds like there is no need for the color changing startup code now then. I'll delete that PR

**Comment by DDReaper** [comment]
So did you push your change @tomspilman ?
If so I can drop this PR and recreate it with the updated template if need be, let me know.

**Pull request closed without merging**
