### PR TITLE
Fixed MGCB Crashes 

### LINKED ISSUE #3960: PipelineTool build canceled abruptly with no message
I have on occasion had a build be abruptly canceled with no feedback to me that it occurred, or any error messages. In fact it looks as if it is still building, perhaps hanging within an individual processor. However that is not what is actually happening. Actually it isn't even building anymore, since the 'build' menu item is enabled and 'cancel' is disabled. I do not know how to reliably reproduce this issue but it happens to me from time to time, and building again will skip past what is already built and start on the next item, and continue onward as expected this time.

### PR DESCRIPTION
**Pull request by ChewyMoon**
MGCB would crash when there was an item that did not have an importer, fixes #3960

### CODE REVIEW

**Comment by ChewyMoon** [comment]
Why hasn't this been accepted yet? Clearly fixes the following stack trace from MGCB:

```
Unhandled Exception: System.Exception: Couldn't find a default importer for 'E:/
Coding/Projects/C#/Games/Zeroed/Zeroed/Content/Title/KenVector Future Thin.ttf'!

   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ResolveImporte
rAndProcessor(String sourceFilepath, String& importerName, String& processorName
)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(S
tring sourceFilepath, String outputFilepath, String importerName, String process
orName, OpaqueDataDictionary processorParameters)
   at MGCB.BuildContent.Build(Int32& successCount, Int32& errorCount)
   at MGCB.Program.Main(String[] args)
```

**Comment by KonajuGames** [comment]
Sorry for that.  Both @tomspilman and myself are very busy at the moment and small PRs like this can often go unnoticed for a while.

To fit the coding style of MonoGame, the statement for an `if` must be on the next line, in the manner of the `if` statement that was already there.  If you fix that and push to this PR, once the build tests pass I'll merge it.

**Comment by ChewyMoon** [comment]
Strange, my VS did that for me somehow, I'll fix.

**Comment by KonajuGames** [comment]
Thanks @ChewyMoon .  Merging.

**Pull request merged**
