### PR TITLE
Clean up some code that potentially was reflected.

### PR DESCRIPTION
**Pull request by dellis1972**
After an incident with a contributor and auditing their contributions we
have a strong suspicion that some bits of their code came from either a
copyrighted source or from a reflection tool.

While we do not have definitive proof of this and cannot be certain of
the code's origin, we feel it is just better for the project to remove
those chunks of code.

 The code in question is in the following functions:

   - BoundingFrustum.Intersects(ref Ray ray, out float? result)
   - Vector4.Transform(ref Vector2 value, ref Quaternion rotation, out Vector4 result)
   - Vector4.Transform(ref Vector3 value, ref Quaternion rotation, out Vector4 result)
   - Vector4.Transform(ref Vector4 value, ref Quaternion rotation, out Vector4 result)

We hope that someone in the community can contribute their own implementations
to fix these holes soon (of course without reading or reusing any of the code removed in this PR).

We will also follow up with an update to the existing CONTRIBUTING.md to help further clarify what we require from them.

### CODE REVIEW

**Comment by amerkoleci** [comment]
SharpDX  has implementation for thoose, we can take code from there

**Comment by tomspilman** [comment]
> SharpDX has implementation for thoose, we can take code from there

Generally we would prefer to get code that isn't tired to another project's license.  In particular for how simple and little code this is, It seems unnecessary to do that.

**Comment by amerkoleci** [comment]
Dude SharpDX is MIT licensed and anyway if you write it from scratch it Will be the same, we can check also System.Numerics.Vectors from corefx

**Comment by tomspilman** [comment]
> Dude SharpDX is MIT licensed and anyway if you write it from scratch it Will be the same

I understand, but disagree.  We don't want our list of licenses to grow even further for something so trivial.

> we can check also System.Numerics.Vectors from corefx

Actually we've been keeping an eye out for that.  We're hoping to eventually replace all of our math implementation with `System.Numerics.Vectors`, but they lack of the `ref` optimization which is holding us back at the moment.  It is an interesting read... https://github.com/dotnet/corefx/issues/157#issuecomment-99787924.

**Comment by flibitijibibo** [comment]
I just had a look at this and it seems like the Vector4 work was _already_ taken from SharpDX, based on who had what first:

https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Mathematics/Vector4.cs#L1005

BoundingFrustum wouldn't surprise me though, especially with lines like this one:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/BoundingFrustum.cs#L493

Seems... really specific. Not Epsilon?

**Comment by tomspilman** [comment]
> Seems... really specific. Not Epsilon?

Things like that are what tipped us off and made us nervous about those particular contributions.

**Comment by tomspilman** [comment]
@dellis1972 - My rewrite of the contributing doc.... https://github.com/mono/MonoGame/pull/4500.

**Comment by tomspilman** [comment]
@KonajuGames - If you are good with this feel free to merge it.

**Comment by KonajuGames** [comment]
Merging.

**Pull request merged**
