### PR TITLE
Conversion of MonoMacGameView to OpenTK equivalent.

### PR DESCRIPTION
**Pull request by groundh0g**
OpenTK for `MONOMAC` platform. Now MacOS is a peer to `WINDOWS` and `LINUX` platforms. Common code for desktop platforms.

I think it's ready for review / testing. RE: #2154.

**NOTES:**

* OpenTK controller mappings can replace SDL on other desktop platforms. Didn't consider that in scope for this PR.
* Media / Video needs some love. I need to compare how the other desktop platforms interface to `GameWindow` and try to emulate.
* Three intentional `#warning DISABLED DURING MONOMAC OPENTK CONVERSION` messages were added.
 * One in `OpenTKGameWindow.cs` to bypass icon extraction from assembly
 * One in `MacOS/GamerServices/Guide.cs` for `Window.ClearKeyCacheState()` which may not be needed now that we're using a different game loop.
 * One in `Media/VideoPlayer.MacOS.cs` for `_game.Window.AddSubview(_currentVideo.MovieView);`. That's the one that need some love.

### CODE REVIEW

**Comment by tomspilman** [comment]
@dellis1972 @KonajuGames @prollin @tgjones @cra0zy

So @thefiddler , who maintains OpenTK, has been MIA for the MonoGame project for a few months now.  For a good part of the last year he was able to make a lot of improvements to OpenTK and keep MonoGame's usage up to date.

We really need someone else to jump in here and help on this front.

Any ideas?

**Comment by groundh0g** [comment]
I honestly think it's ready. (Or was ready when the PR was submitted.)

* When OpenTK gets rev'ed, it'll be poised to take advantage.
* ALL desktop platforms share same codebase, no more game view for OS X.

**Comment by tgjones** [comment]
@tomspilman in principle I'd like to help, but I'm still learning my way around OpenTK, and how it's used by MonoGame (although as homework, I did read all the way through this [this mega-thread / mini-novella](https://github.com/mono/MonoGame/issues/1567)). I don't think I'm able to contribute much to this specific PR, but I'll keep my eyes open for smaller OpenTK-related issues to cut my teeth on.

**Comment by cra0zy** [comment]
@tomspilman I don't know that much about OpenTK(or OpenGL for that matter), but I'll try to help where I can. Also I won't be able to help on PRs like this since I don't have a Mac, but I went threw the code and it seems alright.

**Comment by cra0zy** [comment]
@tomspilman This can be closed, reason is DesktopGL... for the third time.

**Pull request closed without merging**
