### PR TITLE
Fix for importing RGBA16 bitmap

### LINKED ISSUE #4592: Pipeline (3.5.x, under Mac) failing for 16 bit PNG files.
Check the file in attach.
I get 

```
/Users/ambs/Desktop/Aulas/2015-2016/TDJ/Sokoban/Sokoban/Content/Character.png
/Users/ambs/Desktop/Aulas/2015-2016/TDJ/Sokoban/Sokoban/Content/Character.png: error: Importer 'TextureImporter' had unexpected failure!
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import (System.String filename, Microsoft.Xna.Framework.Content.Pipeline.ContentImporterContext context) <0x3079168 + 0x00459> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1[T].Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import (System.String filename, Microsoft.Xna.Framework.Content.Pipeline.ContentImporterContext context) <0x30790d0 + 0x0002e> in <filename unknown>:0 
  at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent (MonoGame.Framework.Content.Pipeline.Builder.PipelineBuildEvent pipelineEvent) <0x3078818 + 0x000f7> in <filename unknown>:0 
````
character

### PR DESCRIPTION
**Pull request by Tzenchor**
Fixes #4592.
This is the simplest fix for the problem, convert the bitmap to 32 bits and continue from there.
Future bitmaps that are not contemplated in the special cases are treated as bitmaps, and converted to 32 bits bitmaps.
I have tried to preserve the higher color resolution of the original image, but `PixelBitmapContent.TryGetFormat` can't handle that option at this time, and this exposed a bug in `PixelBitmapContent.SetPixelData` it ignores the return value of `TryGetFormat`, using the default value.

In game test of the texture, it is a bit cropped at bottom because the window ended there
ingametex

This can be merged now, or I can try to enable the RGBA64 format later

### CODE REVIEW

**Comment by tomspilman** [comment]
Leaving this for @KonajuGames to review as he was doing changes to the texture pipeline last.

**Comment by KonajuGames** [comment]
I'll look through this tonight. It's quite difficult on the phone.

**Comment by KonajuGames** [comment]
From the diff of the unit test, you probably realize that it's clearer to add new tests to the end instead of in the middle.  No worries this time.  I think this change looks ok.  Having PixelBitmapContent support Rgba64 properly can be done later.

**Comment by ambs** [comment]
Thank you all!

**Comment by KonajuGames** [comment]
I've added PR #4603 to add proper support for importing 16-bit per channel images.

**Pull request merged**
