### PR TITLE
[Don't merge] WIP replace OpenTK

### PR DESCRIPTION
**Pull request by mrhelmut**
This is basically #4874 + https://github.com/mrhelmut/MonoGame/tree/SDLDep which includes installer and template updates.

This PR is meant to check if everything is fine and that the artifacts build and pass the tests. Hope you don't mind.

The legit PR is #4874.

### CODE REVIEW

**Comment by cra0zy** [comment]
I don't know what you did here but you made a mess of commits... hot did you get "[Pipeline Tool] Linux Headerbar :)" commit it has nothing to do with SDL replacement. Anyway don't push directly to my branch I'll try to cherry pick when I get the chance.

**Comment by mrhelmut** [comment]
Yes, I know... but don't worry, I would only cherry pick the relevant commits if I had to push them to your branch (I can squash them into one commit if need be).

**Comment by cra0zy** [comment]
> Yes, I know... I don't know how it got there... but don't worry, I would only cherry pick the relevant commits if I had to push them to your branch (I can squash them into one commit if need be).

If you know how to do it, go for it.

**Comment by mrhelmut** [comment]
Squashed the relevant commits into one on my local NewSDL branch: https://github.com/mrhelmut/MonoGame/commit/65b8481868c69ede5e55a4688e5ea96d87dac500

Should I push it to yours?

I'm closing this PR, I branched from the wrong commit (I shouldn't branch using the sourcetree GUI, I just clicked one commit ahead when branching...).

**Pull request closed without merging**
