### PR TITLE
Xamarin iOS Unified API

### PR DESCRIPTION
**Pull request by MarkoBL**
This is a working pull request for the Xamarin iOS Unified API (https://github.com/mono/MonoGame/pull/3139), as the old pull request was messed up with wrong files.

### CODE REVIEW

**Comment by Nezz** [comment]
The build has failed because of WP8.1, which is really strange.

**Comment by tomspilman** [comment]
> The build has failed because of WP8.1, which is really strange.

I suspect the Protobuild.exe added in this PR has fixes for iOS, but doesn't include the fixes added for WP8.1 projects.  

Someone needs to merge the latest Protobuild master branch changes into whatever branch this Protobuild EXE was generated from.  @hach-que ??

**Comment by hach-que** [comment]
Yeah that's correct.  I didn't want to merge the changes into master upstream until we'd confirmed that the project generation for iOS was working.  As I understand WP8 happens after iOS, so it sounds like it is?

**Comment by tomspilman** [comment]
> As I understand WP8 happens after iOS, so it sounds like it is?

Yeah... The Mac and iOS build succeeded.

**Comment by hach-que** [comment]
I merged the iOS changes into Protobuild, so grab the latest exe from the master branch and it should work for WP8.

**Comment by tomspilman** [comment]
@MarkoBL - As soon as you update the Protobuild.exe in this PR and it successfully builds i'll merge this.

**Comment by MarkoBL** [comment]
Done

**Comment by KonajuGames** [comment]
Merging.  Thanks everyone.

**Pull request merged**
