### PR TITLE
Make the Title Container resolve resources properly on WinRT

### PR DESCRIPTION
**Pull request by jakepoz**
When you call the TitleContainer.OpenStream method on Windows platforms,
it needs to lookup the location of the specified resource. This is
because on Windows 10, resources may be stored outside of the main
application folder when using an "application bundle" (now the default
setting).

### CODE REVIEW

**Comment by jakepoz** [comment]
How can I get this to rebuild? It seems like the bot just had an internal error.

**Comment by tomspilman** [comment]
@jakepoz - Actually I see some errors in the WindowsPhone build that seem to come from your changes:

```
[exec] Build FAILED.
[14:44:45][exec] 
[14:44:45][exec] "C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework.WindowsPhone.sln" (Build target) (1) ->
[14:44:45][exec] "C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MonoGame.Framework.WindowsPhone.csproj" (default target) (2) ->
[14:44:45][exec] (CoreCompile target) -> 
[14:44:45][exec]   TitleContainer.cs(9,32): error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'Windows.ApplicationModel' (are you missing an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MonoGame.Framework.WindowsPhone.csproj]
[14:44:45][exec]   TitleContainer.cs(52,25): error CS0246: The type or namespace name 'ResourceContext' could not be found (are you missing a using directive or an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MonoGame.Framework.WindowsPhone.csproj]
[14:44:45][exec]   TitleContainer.cs(53,25): error CS0246: The type or namespace name 'ResourceMap' could not be found (are you missing a using directive or an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MonoGame.Framework.WindowsPhone.csproj]
[14:44:45][exec]   TitleContainer.cs(55,59): error CS0246: The type or namespace name 'ResourceCandidate' could not be found (are you missing a using directive or an assembly reference?) [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MonoGame.Framework.WindowsPhone.csproj]
```

**Comment by jakepoz** [comment]
Got it, will take a look.

**Comment by jakepoz** [comment]
I'm closing this one as it has been left open too long and Title Container changed a bit since then. Will look at this again and submit a fresh PR.

**Pull request closed without merging**
