### PR TITLE
[DesktopGL] Rewrite OpenTK Game Window and Platform

### PR DESCRIPTION
**Pull request by cra0zy**
This should fix the following things:
 - no more hacking around borders
 - no more hacking the exit loop
 - #4538
 - makes opentk window act more stable
 - simplifies code by a lot

~~Do note that it's missing a resolution change, this is because I am looking into how to make that work correctly with multiple displays, I am just putting this out early so it can be tested and so that people can tell me what they think while I figure out this last problem.~~ Linux resolution bug is present only under X11 backend, this is something that's gonna have to be fixed within OpenTK.

@dellis1972 Can you test this on Mac?

### CODE REVIEW

**Comment by dellis1972** [comment]
will try to take a look over the weekend.

**Comment by tomspilman** [comment]
Is it really worth making these changes with the SDL2 move right around the corner?

We really need to get 3.5 out the door in the coming weeks.

**Comment by cra0zy** [comment]
> Is it really worth making these changes with the SDL2 move right around the corner?
> 
> We really need to get 3.5 out the door in the coming weeks.

That is the reason why I decided to make this change, so 3.5 DesktopGL wouldn't have a buggy window.

This should be the last change I do to the OpenTK backend.

**Comment by tomspilman** [comment]
If @mrhelmut and @dellis1972 agree this is stable and better for 3.5 then i'm good with it then.

**Comment by cra0zy** [comment]
@tomspilman @mrhelmut @dellis1972 OpenTK has 2 backends, native and SDL, and with SDL backend the window resizable parameter is not changeable. Do you want it to be always on, always off, or should we do something else about it (I can't do the same thing I did for SDL)?

**Comment by mrhelmut** [comment]
Sounds interesting, I'll test that by Monday.

**Comment by mrhelmut** [comment]
Back at the office, I tested this on a Mac Retina and Windows 4K, and they both have problems with cropped viewport (SDL backend).

**Comment by cra0zy** [comment]
@mrhelmut That bug is not related to Window/Platform code, it' related to GraphicsDeviceManager/OpenTK, and therefore I cannot fix it in here.

**Comment by mrhelmut** [comment]
I know, it's quite entangled together. The current implementation somehow works with Retina/4K, your changes make the situation worst unfortunately. :(

**Comment by cra0zy** [comment]
How do they make it worse?

**Comment by mrhelmut** [comment]
The window size end up being twice as big as it should be on OS X with DPI scaling enabled (only 1/4 of the game is displayed when fullscreen).

**Comment by dellis1972** [comment]
Is this just for the SDL2 backend or native as well?
I've not had a chance to test it yet.

**Comment by cra0zy** [comment]
> The window size end up being twice as big as it should

Let me get this straight, in windowed mode, without this PR window size is correct, but with this PR window size is doubled?

If I got that right, I think I know how to fix it.

**Comment by mrhelmut** [comment]
@dellis1972 I've only tested the SDL2 backend.

@cra0zy It works as intended in windowed mode (the size _is_ doubled, but that's what OS X expect it to be). Once in fullscreen, the viewport is twice bigger and goes behind the screen space.

**Comment by cra0zy** [comment]
> @cra0zy It works as intended in windowed mode (the size is doubled, but that's what OS X expect it to be). Once in fullscreen, the viewport is twice bigger and goes behind the screen space.

Oh, so what you are saying is that the reverse of #4431 is happening. Well that isn't too bad.

**Comment by mrhelmut** [comment]
Not quite, because the viewport was still usable with resolutions below the virtual OS X desktop size (e.g. a 2880x1200 display has a reported resolution of 1440x600, anything equal or lower than this works just fine). These changes make all resolutions to have this issue.

**Comment by cra0zy** [comment]
@dellis1972 Did you get the chance to try this PR out?

**Comment by dellis1972** [comment]
@cra0zy I haven't yet. The build archives are missing so we'll need to get a new build somehow (do a rebase and push?), I don't really have time to compile this myself atm.

**Comment by cra0zy** [comment]
@dellis1972 Done :)

**Comment by cra0zy** [comment]
I just saw what is used for retina scaling code, `float scale = window.ClientSize.Width / (float)window.Size.Width;` we should be able to use it to get the correct fullscreen rendering on Retina, tho I can't do anything about it, I have no Mac or Retina display.

**Comment by dellis1972** [comment]
@cra0zy this works for me on my test game, I can flick between full/windowed and it renders correctly on Mac and windows. But I'm not using the SDL2 backend like @mrhelmut is.

**Comment by mrhelmut** [comment]
The easiest way is indeed to use the returned scale when using SDL2. I think this would make this PR on par with the current implementation.

(The other Retina issues can wait for OpenTK replacement IMO.)

**Comment by cra0zy** [comment]
@mrhelmut Since I don't have a Mac, can you add the missing piece of code to this PR? (I will give you push privileges to my repo)

**Comment by mrhelmut** [comment]
I'll take a look. :) (I won't have access to a retina until Monday)

**Comment by cra0zy** [comment]
> I'll take a look. :) (I won't have access to a retina until Monday)

Ok, I gave you push privileges to my repo.

**Comment by dellis1972** [comment]
I have a Retina... can you post a sample which shows the problem? then the
code and I can fix it :) (if I get time ;) )

**Comment by cra0zy** [comment]
@dellis1972 Just FYI, you still have push privileges to my repo.

**Comment by dellis1972** [comment]
cool ta :)

**Comment by cra0zy** [comment]
I don't know what to do with this PR...

**Comment by tomspilman** [comment]
@cra0zy - Likely we should just focus on the future...  @dellis1972 is working this weekend on the GL/AL bindings.  As soon as that is ready we will merge your branch and we're free of OpenTK for good.

**Pull request closed without merging**
