### PR TITLE
.NET project UAP solution

### LINKED ISSUE #4193: Missing UWP .NET project
Will submit a PR to fill this gap soon.

For now, confirmed the Windows 8 .NET project works fine

### PR DESCRIPTION
**Pull request by DDReaper**
Updated .NET project build definitions to include a MonoGame.Framework.Net.WindowsUAP project.

based on the Windows 8 .NET project, tested working.

Resolves #4193

### CODE REVIEW

**Comment by DDReaper** [comment]
Resolved outstanding issue. Guide Messageboxes now compatible with UAP.
ShowKeyboard not compatible however so disabled for now.

Ready for Merge

**Comment by DDReaper** [comment]
Any chance of getting this Merged before it get's too out of Sync @tomspilman ?

**Comment by dellis1972** [comment]
this looks ok to me. @tomspilman ? @KonajuGames ?

**Comment by KonajuGames** [comment]
Merging.

**Pull request merged**
