### PR TITLE
Gtk Pipeline Multiselect

### PR DESCRIPTION
**Pull request by cra0zy**
Things added:
<ul>
<li>Ability to select folders</li>
<li>Full multiselect support</li>
<li>Mimicking #3324</li>
</ul>

With this PR the gtk pipeline is finally at equal position with the windows pipeline.

### CODE REVIEW

**Comment by cra0zy** [comment]
Found a bug while I was making linux installer scripts so I added a fix for it in this PR, hope it's ok.

**Comment by tomspilman** [comment]
Looks good to me...  @dellis1972 ?

**Comment by dellis1972** [comment]
Looks ok to me too… I thought I'd replied to this already.. weird

**Comment by tomspilman** [comment]
Great... merged!

**Pull request merged**
