### PR TITLE
Fix Ogg Importer

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by tomspilman** [comment]
@cra0zy - Two more things we need here.

We need to fix this block to detect Ogg and return the right `AudioFileType`:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Audio/DefaultAudioProfile.cs#L168

We need to add a unit test for Ogg import just like we have for MP3 import:

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/Mp3ImporterTests.cs

This test will only run under MonoGame, but it will ensure no one breaks Ogg import again.

**Comment by cra0zy** [comment]
Sigh..

**Comment by cra0zy** [comment]
@tomspilman Is build bot down?

**Comment by tomspilman** [comment]
@cra0zy - Looks like it... the Windows agents are down.  Will try to remote in and fix it.  Thanks for alerting me!

**Comment by tomspilman** [comment]
@cra0zy - This doesn't look like your issue... looks like a build server issue.  Working on it.

**Comment by tomspilman** [comment]
@cra0zy - Error...

```
System.IO.FileNotFoundException : Could not locate audio file rock_loop_stereo.ogg.
```
Looks like you missed adding the `rock_loop_stereo.ogg` to `MonoGame.Tests.definition`.

**Comment by cra0zy** [comment]
Now I don't think it's my fault :/

**Comment by cra0zy** [comment]
@tomspilman Ping

**Comment by tomspilman** [comment]
@cra0zy - There is something going wrong with TeamCity gathering the results from the unit tests which are all passing right now.  Working with the TeamCity people to try to work it out.

**Comment by tomspilman** [comment]
@cra0zy - Can you do me a favor?

https://github.com/mono/MonoGame/blob/develop/Test/Framework/GameComponentTest.cs

I suspect that the `GameComponentTest` class and the `InitializeOrderTest` method need to be `static`.  Can you make this change in this PR?

**Comment by cra0zy** [comment]
Done.

**Comment by tomspilman** [comment]
So I updated to the latest version of TeamCity and the issue we were seeing in this PR seems to have gone away.  

However it reports only 306 tests when it should be running over 700 tests.  I don't think it has anything to do with this PR, so I will merge this anyway.

**Pull request merged**
