### PR TITLE
Nvorbis Song.cs for WindowsGL and Linux

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by Shqrdx** [comment]
One question - OggStreamer and OggStream intended to be public ?

**Comment by cra0zy** [comment]
> One question - OggStreamer and OggStream intended to be public ?

Yes

**Comment by Shqrdx** [comment]
Than where are all comments to public members in these classes ?

**Comment by cra0zy** [comment]
internal it is

**Comment by tomspilman** [comment]
@KonajuGames  - You good with all this?

**Comment by KonajuGames** [comment]
I'm good with it.

**Comment by tomspilman** [comment]
@cra0zy - We need to fix the attribution on `MonoGame.Framework/Utilities/OggStream.cs`

 https://twitter.com/renaudbedard/status/634083489659416576

Please submit a PR adding this comment at the top of the `OggStream.cs` file:

```
// This code originated from:
//
//    http://theinstructionlimit.com/ogg-streaming-using-opentk-and-nvorbis
//    https://github.com/renaudbedard/nvorbis/
//
// It was released to the public domain by the author (Renaud Bedard).
// No other license is intended or required. 
```

**Comment by cra0zy** [comment]
@tomspilman When I was submiting this, I did look at the original code from NVorbis GitHub source and I saw it also had MS-PL license and read http://stackoverflow.com/questions/1424307/how-does-ms-pl-license-work so I thought no headers were needed since MonoGame also uses MS-PL.

I didn't know about attribution till... well now...

**Comment by tomspilman** [comment]
@cra0zy - Yeah... Renaud mentioned it wasn't really clear.  We know it wasn't intentional...  just glad we caught it and fixed it.

**Pull request merged**
