### PR TITLE
[Pipeline Tool] Make PropertyGrid Extendable

### LINKED ISSUE #4946: (PipelineTool) Can not edit (int) type properties.

### PR DESCRIPTION
**Pull request by cra0zy**
Custom cells for propertygrid can now be added from a dll that is referenced in a project, I'll write some documentation on this later on.

Also fixes #4946 and #4947

### CODE REVIEW

**Comment by cra0zy** [comment]
This just makes it so end user can add a cell for editing for anything that is not a built in C# property, since those are the only ones the property grid will support.

**Comment by cra0zy** [comment]
Just FYI, if you don't like the idea all I have to do is remove my changes from PipelineController.cs, the rest of the changes are still needed.

**Comment by KonajuGames** [comment]
I'm ok with this.  I wouldn't expect it to get used a lot though.

**Comment by cra0zy** [comment]
Any chance of this getting merged any time soon? I don't mind removing the few lines from the PipelineController.cs file as I mentioned above if it would help.

**Comment by tomspilman** [comment]
> I don't mind removing the few lines from the PipelineController.cs file as I mentioned above if it would help.

How about you just comment that bit out for now leaving a `TODO` to enable it later once we have time to document and test it all.

I just don't want to introduce more complications until we get the core of the Pipeline tool back to working as well as it used to before the Eto changes.

**Comment by cra0zy** [comment]
> How about you just comment that bit out for now leaving a TODO to enable it later once we have time to document and test it all.

I think just removing it seems cleaner for the code base, anyway done.

**Comment by cra0zy** [comment]
The build finished.

**Comment by tomspilman** [comment]
Thanks... merging!

**Pull request merged**
