### PR TITLE
Fixes logical buffer store when swapping the default framebuffer (iOS)

### PR DESCRIPTION
**Pull request by prollin**
Discards the depth/stencil attached to the main framebuffer (if any) to avoid a [logical buffer store](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/WorkingwithEAGLContexts/WorkingwithEAGLContexts.html#//apple_ref/doc/uid/TP40008793-CH105-SW7) operation when the main framebuffer is swapped.
This also adds proper depth/stencil initialization based on the value of `GraphicsDeviceManager.PreferredDepthFormat`.

### CODE REVIEW

**Comment by tomspilman** [comment]
Restarting this... looks like it got messed up while I was updating the Mac box.

**Comment by tomspilman** [comment]
This is my fault @prollin ...  i'm working on it now.

**Comment by tomspilman** [comment]
@dellis1972 - So upgrading the Mac box screw NAnt up like you expected.

I moved the old NAnt to the new Mono folder, but now I get this error:

```
NAnt output
NAnt 0.92 (Build 0.92.4543.0; release; 6/9/2012)
Copyright (C) 2001-2012 Gerry Shaw
http://nant.sourceforge.net

BUILD FAILED

Mono 4.0 Profile (mono-4.0) is not installed, or not correctly configured.

   The 'System.dll' assembly does not exist in framework assembly directory '/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig/../../lib/mono/4.0'.

For more information regarding the cause of the build failure, run the build again in debug mode.

Try 'nant -help' for more information
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
```

Any ideas on what I should do here?

**Comment by dellis1972** [comment]
@prollin @tomspilman  the Bot is fixed now need to restart this build

**Comment by dellis1972** [comment]
I managed to restart the build. Looking good

**Comment by tomspilman** [comment]
> I managed to restart the build.

Yeah...  all you need to do is hit `Build` for the `Kickoff Build` configuration for the branch of the correct PR number.  It seems you figured that out. :)

**Comment by prollin** [comment]
@tomspilman added an extra commit that fixes an issue that was highlighted by my previous commit. The commit msg should have all the info.

**Comment by dellis1972** [comment]
@prollin just a heads up I'm going to start migrating iOS/Android over to use our own custom GL bindings in the next couple of weeks.

**Comment by tomspilman** [comment]
Thanks @prollin ... merging!

**Pull request merged**
