### PR TITLE
Fix for linux exit errors 2, 3, 4 from #3540

### PR DESCRIPTION
**Pull request by cra0zy**
Fix for linux exit errors 2, 3, 4 from #3540

### CODE REVIEW

**Comment by KonajuGames** [comment]
With this type of change, we need to ensure that Dispose is correctly called and on the correct thread.  If Dispose is not called, the GC will call the finalizer which disposes of unmanaged resources on the GC thread.  That said, the previous code to run on the UI thread probably wouldn't have worked if called by the finalizer.

**Comment by prollin** [comment]
I am not sure we need `GL.IsShader()`; those state query functions should be avoided since they could stall the GPU; Not a huge deal during resource creation/deletion but it can't hurt to remove superfluous code. MonoGame should already know it is a shader since it created it internally.

**Comment by tomspilman** [comment]
> I am not sure we need `GL.IsShader()`

What is it even doing there?  How would our shader handle not be a shader?

We call `GL.IsShader()` in that file too.


> those state query functions should be avoided since they could stall the GPU

Which is extra bad if you are trying to load resources during gameplay.

**Comment by cra0zy** [comment]
So if I understood everything correctly I should:
1) Remove GL.IsShadder, unneeded check
2) Setup 2 dispose events, one for normal disposing(with threads if necessary) and one thats used when the game is exiting

**Comment by tomspilman** [comment]
> So if I understood everything correctly I should:

I'll leave that up to @prollin  and @KonajuGames to decide. :)

**Comment by cra0zy** [comment]
@prollin @KonajuGames Is this ok now?

**Comment by KonajuGames** [comment]
I'm not too keen on the addition of another virtual method in GraphicsResource to do a slightly different  Dispose path.  We could merge this as a temporary fix for the exit issues, but I would like to revisit it soon.

**Comment by cra0zy** [comment]
What do you thing of doing something like: 
> Dispose(bool disposing, bool calledbyfinilizer)

Would that be better?

**Comment by KonajuGames** [comment]
That's what the `disposing` parameter is for.  If `true`, it was called by the app via `Dispose()`.  If `false` it was called by the finalizer (so don't access other managed resources because they may or may not exist).

**Comment by cra0zy** [comment]
@KonajuGames I think I found a solution that you are gonna like

**Comment by tomspilman** [comment]
@cra0zy - So is this a case where no one called `Dispose()` on the shader before shutdown?

**Comment by KonajuGames** [comment]
That looks a lot better.  You confirmed that works for you?

**Comment by cra0zy** [comment]
Works great for me, 15 runs, none showed errors 2,3,4 on exit.

**Comment by tomspilman** [comment]
Seems ok to me... your call to merge @KonajuGames .

**Comment by KonajuGames** [comment]
Merging.  Thanks @cra0zy

**Pull request merged**
