### PR TITLE
Point negation operator

### PR DESCRIPTION
**Pull request by Shqrdx**
Looks like I forgot add negation operator when adding operators to Point.
And this is just a simple commit for check whether or not TomSpilman restricts me from pushing new PR now :) I did not steal code from XNA anyway. Please take me back to contributers.I still love MonoGame !

### CODE REVIEW

**Comment by tomspilman** [comment]
@Shqrdx - Myself and @KonajuGames will discuss it and decide.  We are all really busy right now so it will be a few days.

**Comment by cra0zy** [comment]
> I did not steal code from XNA anyway

At least admit your mistakes instead of saying that... https://github.com/mono/MonoGame/pull/4158#discussion_r40492287

@tomspilman @KonajuGames For the record, I am ok with @Shqrdx submitting documentation stuff or stuff to the Content Pipeline etc, but I am against him submitting any type of code to the MonoGame framework.

**Comment by Shqrdx** [comment]
oh so I've got new enemy.. what a teh drama anyway

**Comment by Shqrdx** [comment]
Looks like this repo is a beehive for me. I better go away from here. How pity that you are not been killed in the Kosovo conflict... @cra0zy

**Comment by tomspilman** [comment]
@Shqrdx - I saw your original comment before you edited it.  We do not tolerate that behavior/attitude on this project.

I've locked this comment thread...  something we've never done before..  to keep this from getting out of hand.

**Pull request closed without merging**
