### PR TITLE
Content file icons based on file type

### PR DESCRIPTION
**Pull request by nkast**
https://github.com/mono/MonoGame/issues/3609

### CODE REVIEW

**Comment by tomspilman** [comment]
This looks great... merging!

**Comment by tomspilman** [comment]
I've been seeing a black background on the file type icons on Windows:

icon

Anyone else seeing this?

**Comment by Vodacek** [comment]
I have same problem

**Comment by nkast** [comment]
Everything seems ok here.
build 3.5.0.222, Tested on 
Win 8.1 - latest updates+optional updates
Win 100074 (VMWare)

**Comment by tomspilman** [comment]
> Everything seems ok here.

This was under a VMWare virtual machine right?

Is anyone else having this issue?

**Comment by nkast** [comment]
Only the Win 10 is VM. The win 8.1 is an AMD CPU with  Radeon R9 video card.

**Comment by nkast** [comment]
It's been a while since I notice this too, going on and of. I found that if you build for x86 the icon background is ok but when you build for x64 icons are black.
fix: https://github.com/mono/MonoGame/pull/4247

**Comment by nkast** [comment]
@cra0zy,
We could set `ItemHeight` of _treeView from 16 to 18 to allow for some space between icons. (17 is hardly noticeable).

**Comment by cra0zy** [comment]
> We could set ItemHeight of _treeView from 16 to 18 to allow for some space between icons. (17 is hardly noticeable).

Do it, sounds good.

**Comment by nkast** [comment]
Done https://github.com/mono/MonoGame/pull/4249

**Pull request merged**
