### PR TITLE
Use Visual Studio's registry keys...

### LINKED ISSUE #4612: Monogame Has all Visual Studio Templates grayed out..
I have windows 10 and visual studio 2015 community. I tried installing monogame 3.4 and this what showed up
screenshot 2016-03-07 06 48 39
 can and one help me?

### PR DESCRIPTION
**Pull request by KonajuGames**
...to locate the project templates folder.  The templates could be anywhere, not just in the user's Documents folder.

Fixes #4612.

### CODE REVIEW

**Comment by Tzenchor** [comment]
I tested it and worked well

**Comment by dellis1972** [comment]
@KonajuGames looks good. Merging thanks

**Comment by cra0zy** [comment]
> @KonajuGames looks good. Merging thanks

Forgetting something? :P

**Comment by dellis1972** [comment]
lol

**Comment by KonajuGames** [comment]
I'm not the only one. :)

**Pull request merged**
