### PR TITLE
Installer VS2015 Support

### PR DESCRIPTION
**Pull request by tomspilman**
This adds VS2015 support to the installer.  Mainly it just copies the templates for VS2010 desktop projects and VS2013 universal apps.

The next step is full Win10 support.

### CODE REVIEW

**Comment by nkast** [comment]
"The next step is full Win10 support."
8-)

Net.Native sounds promising but Windows 10 apps looks a lot like an upgraded .appx  from windows 8.1. You have to push a single app for all targets. I Can't find any info on new features in packaging. 
Here is the win8.1 packaging. if anyone has found info on Win10 changes please share.
https://msdn.microsoft.com/en-us/library/windows/apps/bg182885.aspx

So far you can package assets based on featurelevel,language and DPI, not on actual screensize or target platform (phone/desktop/xbox).
DPI is good only for apps to make icons look crisp but virtually same size, it doesn't suport games where I want to scale a background to fill the screen without pushing the same fat asset to low res phones where disk app size is important. A different case is a 1080 phone (HighDPI) and a 28'' 1080 desktop (mediumDPI), I had to either push a 1920x1080 background on all devices (including 800x480 phones) or end up with a 800x480 background on desktop.

**Comment by tomspilman** [comment]
> You have to push a single app for all targets.

MS has said you don't have to use one app for all targets.  They recommend it, but you don't have to.  In fact C++ coders can't because they have to build EXEs for x86, x64, and ARM.  So some sort of feature exists for this, but I don't know the details beyond that.

**Comment by Shqrdx** [comment]
I guess windows 8 support could be safely omitted in order to 8.1 and 10 implemented and simplification purpose.

**Comment by tomspilman** [comment]
> I guess windows 8 support could be safely omitted for 8.1 and 10 implementation 

Actually I tested and had issues with both the Win 8 and Win 8.1 templates on VS2015.  So i'm thinking I just won't include those.  If you need to write a Windows/Phone 8 or 8.1 project just use VS2013.

We'll be adding Win10 templates as soon as I have the support complete.

**Comment by Shqrdx** [comment]
@tomspilman And (sorry for tiresomeness) could you review my PR ?https://github.com/mono/MonoGame/pull/3705

**Comment by dellis1972** [comment]
@tomspilman this looks ok. I can merge if you like?

**Comment by tomspilman** [comment]
Ok... merging this with just the old VS2010 desktop project templates.

**Pull request merged**
