### PR TITLE
Rename and update WindowsUAP platform to WindowsUniversal

### PR DESCRIPTION
**Pull request by DDReaper**
Prepared for ProtoBuild update including the Windows 10 Universal platform

Once tested, can we get this merged asap @tomspilman to prepare for the ProtoBuild update, once Win 10 and TVOS have been added to protobuild

### CODE REVIEW

**Comment by KonajuGames** [comment]
Looks like a decent change to me.

**Comment by DDReaper** [comment]
Thanks @KonajuGames Just waiting for TeamCity to build so I can verify the installer and templates come out right.
Aim is to add Win10 (and TVOS when ready) to ProtoBuild itself so we can update protobuild to the latest defs and xslt;s
Then I might have a chance of getting the .Core project completed :S #Phew, long road

**Comment by DDReaper** [comment]
Hmm, @dellis1972 @KonajuGames Any ideas why this failed?
All the build scripts were updated successfully and the project builds as expected.  Is there some other server side activity for platform folders? (or have I missed something? as I did a complete file check on source for UAP and everything that should be updated, is)

**Comment by dellis1972** [comment]
@DDReaper 

[exec] File: "..\..\MonoGame.Framework\bin\WindowsUniversal\AnyCPU\Release\*.dll" -> no files found.
[10:10:50][NAnt output]                  [exec] Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
[10:10:50][NAnt output]                  [exec]    /oname=outfile one_file_only)

**Comment by dellis1972** [comment]
@DDReaper probably something to do with x86/x64 vs AnyCPU

**Comment by DDReaper** [comment]
@dellis1972 All I've done is rename the platform, nothing else has changed.  This is why I can't understand why it's suddenly not working.

**Comment by KonajuGames** [comment]
When Protobuild generates the csproj files, is it setting the OutDir variable correctly in those project files?

**Comment by DDReaper** [comment]
I'll double check, but when built manually, it's correct

**Comment by DDReaper** [comment]
Looks fine as far as I can tell.
Windows 8 output dir is - bin\Windows8\AnyCPU\Release
The new WindowsUniversal outputdir is - bin\WindowsUniversal\AnyCPU\Release

The Build log stated it was looking in: File: "..\..\MonoGame.Framework\bin\WindowsUniversal\AnyCPU\Release\*.dll" -> no files found.

Can't see any platform build issues reported in the build log.

What was odd is that the build artefacts were generated but the Windows 10 project is output as WindowsUAP (the old name??)

**Comment by DDReaper** [comment]
Could this be related to the .Net NuGet's.  Were there any issues with the build server for the initial UAP builds?

**Comment by DDReaper** [comment]
Ok, digging in to the build log, this looks weird. Can someone please verify?
mgbuildlogwin10
Each platform calls it's build, then exec's the build.  However, the Win10 build calls the Build_web routine??

Could this be just a dodgy build run or is something amis? (actually checked the previous working builds and they are the same)

**Comment by dellis1972** [comment]
@DDReaper just went through the raw log and saw this

```2887,9): warning APPX1901: The DefaultLanguage property is either missing from the project file or does not have a value. The fallback language is set to the Visual Studio language: en-US. [C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\MonoGame.Framework.Net.WindowsPhone81.csproj]
[09:59:19] :							 [exec] 
[09:59:19] :							 [exec]     66 Warning(s)
[09:59:19] :							 [exec]     0 Error(s)
[09:59:19] :							 [exec] 
[09:59:19] :							 [exec] Time Elapsed 00:00:14.96
[09:59:19] :		 [build_code] call
[09:59:19] :			 [call] clean
[09:59:19] :				 [clean] delete
[09:59:19] :					 [delete] Deleting directory 'C:\TeamCity\buildAgent\work\f26e5a04a66fcbdb\MonoGame.Framework\obj'.
[09:59:19] :			 [call] build_windows10
[09:59:19] :				 [build_windows10] if (running for 13m:46s)
[09:59:19] :		 [build_code] call (7s)
[09:59:19] :			 [call] clean
[09:59:19] :			 [call] build_web (7s)
[09:59:19] :				 [build_web] if (7s)
[09:59:19] :					 [if] exec (3s)
[09:59:19] :						 [exec] Starting resolution of packages...
[09:59:19] :						 [exec] Resolving: https-git://github.com/OutOfOrder/MonoKickstart.git
[09:59:19] :						 [exec] Git repository present at ThirdParty/Kickstart\.git; leaving as source version.
[09:59:19] :						 [exec] Git submodule / repository already present at ThirdParty/Kickstart
[09:59:19] :						 [exec] Resolving: https-git://github.com/Mono-Game/MonoGame.Dependencies.git
[09:59:19] :						 [exec] Git repository present at ThirdParty/Dependencies\.git; leaving as source version.
[09:59:19] :						 [exec] Git submodule / repository already present at ThirdParty/Dependencies
[09:59:19] :						 [exec] Package resolution complete.
[09:59:19] :						 [exec] Starting generation of projects for Web```


note ```[build_windows10] if (running for 13m:46s)``` but there is NO output from protobuild or msbuild. something isn't quite right. 

//cc @tomspilman @KonajuGames

**Comment by dellis1972** [comment]
@DDReaper  ah.. the win 10 build happens on the Win10 bot.. this must have something to do with the artefact downloading still to UAP?

**Comment by DDReaper** [comment]
So is that a server side thing to fix, or is there config somewhere in the repo?
If I understand correctly then, the post event for the build bot is not copying the right folder?

**Comment by dellis1972** [comment]
I'm not sure... in the script for the installers we get the artefacts from the iOS build manually for the windows installer.. but I don't see any reference to getting the Windows 10 artefacts anywhere.

**Comment by DDReaper** [comment]
Any update @dellis1972 / @KonajuGames on this, is this something fixable in source or is there something on the server that needs kicking.
When ready I'll do a touch update to kick off the build again.

**Comment by DDReaper** [comment]
Any chance @tomspilman can have a look at the build server and the Win10 job, to see why it's not picking up the new WindowsUniversal name?

**Comment by hach-que** [comment]
#4282 includes this change now, so if that gets merged, this PR is no longer needed (also #4282 correctly builds WindowsUniversal and has the artifacts picked up by the build server)

**Comment by DDReaper** [comment]
Ok, withdrawing then

**Pull request closed without merging**
