### PR TITLE
Added Input methods for Web platform

### PR DESCRIPTION
**Pull request by cra0zy**
This PR implements the following stuff onto the Web platform:
 - Mouse
 - Keyboard
 - Joystick
 - Gamepad
 - Some very basic window functionality

Notes:
 - General:
   - <s>I renamed Web platform to Jsil platform because protobuild checks if the platform is "Web" and downloads the entire Jsil repo and then builds the source code, which is totally unneeded... we only need it's binaries. Plus one more dumb thing about this is that the repo it chooses is hardcoded inside Protobuild and it's: https://github.com/hach-que/JSIL
     - https://github.com/hach-que/Protobuild/blob/a31b25dbe1630db9b418726f3069e6622d93c603/Protobuild.Internal/Packages/PackageGlobalTool/KnownToolProvider.cs</s>
    - The way I implemented this is different then what was originally imagined, I combined C# with JS calls so all the JS stuff is still inside C#, the original idea was to create Stubs and write JS code separately  which would be weird for a C# repo
   - I tested all the code I wrote with Chrome and Firefox
 - Mouse:
   - Javascript does not contain a function that allows us to set a mouse position, but it does contain a function that allows locking a mouse pointer, so in order to make setting cursor position possible I made the game capture the mouse and just track it's movement, and simulate that onto a fake mouse
 - Game Window:
    - Unless the window size is specified, the game will use the size of the canvas it is drawn onto
   - The canvas that the game will use for drawing is the one with id "mgcanvas"
 - Gamepad:
   - Triggers in Firefox go from -1 to 1, but Firefox default starting position is 0 (possible bug?), so for now the code is tracking trigger from 0 to 1
   - Triggers in Chrome are buttons
   - First time a new gamepad is connected and loaded will be a bit slower

Demo project: https://github.com/cra0zy/MGWeb

Next I will be working on audio stuff. Help from someone with WebGL would be nice, GraphicsDevice is a nightmare....

### CODE REVIEW

**Comment by tomspilman** [comment]
It is great to see someone take the lead on this finally...  i'm excited to see how far you can get it.

> I renamed Web platform to Jsil platform 

I really would like to not have to do that...  maybe @hach-que can tell us how to disable this behavior?


> so all the JS stuff is still inside C#, 

That seems reasonable to me.

**Comment by hach-que** [comment]
> > I renamed Web platform to Jsil platform
> 
> I really would like to not have to do that... maybe @hach-que can tell us how to disable this behavior?

It doesn't download the source files, it just downloads and installs the binaries automatically.  It performs the required configuration in the C# project file to run JSIL on build so that everything is wired up correctly.

**Comment by hach-que** [comment]
For example, that demo page has a README that states:

> build MGWeb.sln
> copy JSIL Libraries folder to MGWeb output folder
> run "JSILc MGWeb.exe" while in MGWeb output folder
> put all the javascript/html files in MGWeb output folder to a web server and run the index.html

If you just generate for the Web platform, all of this is done automatically for you by Protobuild.

**Comment by cra0zy** [comment]
> It doesn't download the source files, it just downloads and installs the binaries automatically. It performs the required configuration in the C# project file to run JSIL on build so that everything is wired up correctly.

Nope: https://youtu.be/bCCeDe5yCk4?t=35s
it downloads the source code, and builds it. La terminal never lies.

It also fails to build on Linux.... and doesn't register if the source code has been downloaded since it only searches for binaries.

> If you just generate for the Web platform, all of this is done automatically for you by Protobuild.

That's useless for the build server... we only need the dll file.

And as for the end users, there will need to be a monodevelop/visual studio addin that will automize this process and make it easy for the user to change stuff.

@hach-que please, just tell us how to disable it...

**Comment by hach-que** [comment]
You have a very old version of Protobuild; this changed on June 14th of this year.  Download the latest version at http://protobuild.org/get.

**Comment by cra0zy** [comment]
> You have a very old version of Protobuild; this changed on June 14th of this year. Download the latest version at http://protobuild.org/get.

That changes things... also that's the Protobuild that is with the MonoGame repo. I'll update Protobuild here I guess...

**Comment by hach-que** [comment]
For example, this has the expected behaviour for me:

```
$ wget http://protobuild.org/get
$ mv get Protobuild.exe
$ mono Protobuild.exe --start http://protobuild.org/commons/Console project
$ mono Protobuild.exe --generate Web
$ vi project/index.htm (uncomment the `asm.project.Program.Main();` line)
$ xbuild *.Web.sln
$ google-chrome project/bin/Web/AnyCPU/Debug/index.htm
```

image

I just pushed a fix for the `Main` line being accidentally commented out, so you'll need to get the latest version again.

**Comment by hach-que** [comment]
Also there is #4128 for a Protobuild update, but it hasn't been merged in yet (I'll push another version of that PR now)

**Comment by cra0zy** [comment]
> Also there is #4128 for a Protobuild update, but it hasn't been merged in yet (I'll push another version of that PR now)

I kind of didn't read the comment and updated the protobuild here...

**Comment by cra0zy** [comment]
This is ready for merging.

**Comment by tomspilman** [comment]
Great... merging!

**Pull request merged**
