### PR TITLE
Joystick API

### PR DESCRIPTION
**Pull request by cra0zy**
#3634

### CODE REVIEW

**Comment by tomspilman** [comment]
@KonajuGames - You never got a chance to chime in on the original issue.  How do you feel about extending controller support for non-GamePad devices?

**Comment by cra0zy** [comment]
@KonajuGames What's your opinion on all of this?

**Comment by KonajuGames** [comment]
Oh sorry.  Completely missed this.

I think it looks good to me.  It is consistent with other input implementations and should fit in well.  My only suggestion is that the plural of Axis is Axes, not Axises.

**Comment by cra0zy** [comment]
@tomspilman Is the build server ok?

**Comment by tomspilman** [comment]
@cra0zy - Yep... you just have a syntax error in your code:

> Joystick.Default.cs(27,17) : error CS0117: `Microsoft.Xna.Framework.Input.JoystickState' does not contain a definition for `Axises'

**Comment by tomspilman** [comment]
@cra0zy - Also you need to merge the latest develop changes in.  The build is expecting win10 stuff to exist now.

**Comment by cra0zy** [comment]
I'm going to just create a new PR.

**Comment by cra0zy** [comment]
> @cra0zy - Yep... you just have a syntax error in your code:

I feel so dumb now...

**Pull request closed without merging**
